// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tscrond/fluxsend-backend/internal/auth (interfaces: AuthProvider)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_auth_provider.go -package=mocks github.com/tscrond/fluxsend-backend/internal/auth AuthProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	auth "github.com/tscrond/fluxsend-backend/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthProvider is a mock of AuthProvider interface.
type MockAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthProviderMockRecorder
	isgomock struct{}
}

// MockAuthProviderMockRecorder is the mock recorder for MockAuthProvider.
type MockAuthProviderMockRecorder struct {
	mock *MockAuthProvider
}

// NewMockAuthProvider creates a new mock instance.
func NewMockAuthProvider(ctrl *gomock.Controller) *MockAuthProvider {
	mock := &MockAuthProvider{ctrl: ctrl}
	mock.recorder = &MockAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthProvider) EXPECT() *MockAuthProviderMockRecorder {
	return m.recorder
}

// GetAuthURL mocks base method.
func (m *MockAuthProvider) GetAuthURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthURL indicates an expected call of GetAuthURL.
func (mr *MockAuthProviderMockRecorder) GetAuthURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthURL", reflect.TypeOf((*MockAuthProvider)(nil).GetAuthURL), state)
}

// HandleCallback mocks base method.
func (m *MockAuthProvider) HandleCallback(ctx context.Context, r *http.Request) (*auth.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, r)
	ret0, _ := ret[0].(*auth.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockAuthProviderMockRecorder) HandleCallback(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockAuthProvider)(nil).HandleCallback), ctx, r)
}

// Logout mocks base method.
func (m *MockAuthProvider) Logout(ctx context.Context, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthProviderMockRecorder) Logout(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthProvider)(nil).Logout), ctx, accessToken)
}

// Name mocks base method.
func (m *MockAuthProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAuthProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAuthProvider)(nil).Name))
}
