// Code generated by MockGen. DO NOT EDIT.
// Source: ../repo/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=../repo/sqlc/querier.go -destination=./mock_querier.go -package=mocks Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	sqlc "github.com/tscrond/fluxsend-backend/internal/repo/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AbortFileUpload mocks base method.
func (m *MockQuerier) AbortFileUpload(ctx context.Context, id uuid.UUID) (sqlc.FileUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortFileUpload", ctx, id)
	ret0, _ := ret[0].(sqlc.FileUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbortFileUpload indicates an expected call of AbortFileUpload.
func (mr *MockQuerierMockRecorder) AbortFileUpload(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortFileUpload", reflect.TypeOf((*MockQuerier)(nil).AbortFileUpload), ctx, id)
}

// AssignAPIKeyToPrivate mocks base method.
func (m *MockQuerier) AssignAPIKeyToPrivate(ctx context.Context, arg sqlc.AssignAPIKeyToPrivateParams) (sqlc.ApiKeyUserAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignAPIKeyToPrivate", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiKeyUserAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignAPIKeyToPrivate indicates an expected call of AssignAPIKeyToPrivate.
func (mr *MockQuerierMockRecorder) AssignAPIKeyToPrivate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignAPIKeyToPrivate", reflect.TypeOf((*MockQuerier)(nil).AssignAPIKeyToPrivate), ctx, arg)
}

// AssignAPIKeyToWorkspace mocks base method.
func (m *MockQuerier) AssignAPIKeyToWorkspace(ctx context.Context, arg sqlc.AssignAPIKeyToWorkspaceParams) (sqlc.ApiKeyWorkspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignAPIKeyToWorkspace", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiKeyWorkspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignAPIKeyToWorkspace indicates an expected call of AssignAPIKeyToWorkspace.
func (mr *MockQuerierMockRecorder) AssignAPIKeyToWorkspace(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignAPIKeyToWorkspace", reflect.TypeOf((*MockQuerier)(nil).AssignAPIKeyToWorkspace), ctx, arg)
}

// BlockUntil mocks base method.
func (m *MockQuerier) BlockUntil(ctx context.Context, arg sqlc.BlockUntilParams) (sqlc.AuthRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUntil", ctx, arg)
	ret0, _ := ret[0].(sqlc.AuthRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockUntil indicates an expected call of BlockUntil.
func (mr *MockQuerierMockRecorder) BlockUntil(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUntil", reflect.TypeOf((*MockQuerier)(nil).BlockUntil), ctx, arg)
}

// CheckPrivateAPIKeyQuota mocks base method.
func (m *MockQuerier) CheckPrivateAPIKeyQuota(ctx context.Context, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrivateAPIKeyQuota", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPrivateAPIKeyQuota indicates an expected call of CheckPrivateAPIKeyQuota.
func (mr *MockQuerierMockRecorder) CheckPrivateAPIKeyQuota(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivateAPIKeyQuota", reflect.TypeOf((*MockQuerier)(nil).CheckPrivateAPIKeyQuota), ctx, userID)
}

// CheckShareQuota mocks base method.
func (m *MockQuerier) CheckShareQuota(ctx context.Context, arg sqlc.CheckShareQuotaParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckShareQuota", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckShareQuota indicates an expected call of CheckShareQuota.
func (mr *MockQuerierMockRecorder) CheckShareQuota(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckShareQuota", reflect.TypeOf((*MockQuerier)(nil).CheckShareQuota), ctx, arg)
}

// CheckUploadQuota mocks base method.
func (m *MockQuerier) CheckUploadQuota(ctx context.Context, arg sqlc.CheckUploadQuotaParams) (sqlc.CheckUploadQuotaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUploadQuota", ctx, arg)
	ret0, _ := ret[0].(sqlc.CheckUploadQuotaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUploadQuota indicates an expected call of CheckUploadQuota.
func (mr *MockQuerierMockRecorder) CheckUploadQuota(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUploadQuota", reflect.TypeOf((*MockQuerier)(nil).CheckUploadQuota), ctx, arg)
}

// CheckWorkspaceAPIKeyQuota mocks base method.
func (m *MockQuerier) CheckWorkspaceAPIKeyQuota(ctx context.Context, workspaceID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWorkspaceAPIKeyQuota", ctx, workspaceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckWorkspaceAPIKeyQuota indicates an expected call of CheckWorkspaceAPIKeyQuota.
func (mr *MockQuerierMockRecorder) CheckWorkspaceAPIKeyQuota(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWorkspaceAPIKeyQuota", reflect.TypeOf((*MockQuerier)(nil).CheckWorkspaceAPIKeyQuota), ctx, workspaceID)
}

// CheckWorkspaceResourceQuota mocks base method.
func (m *MockQuerier) CheckWorkspaceResourceQuota(ctx context.Context, id uuid.UUID) (sqlc.CheckWorkspaceResourceQuotaRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWorkspaceResourceQuota", ctx, id)
	ret0, _ := ret[0].(sqlc.CheckWorkspaceResourceQuotaRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckWorkspaceResourceQuota indicates an expected call of CheckWorkspaceResourceQuota.
func (mr *MockQuerierMockRecorder) CheckWorkspaceResourceQuota(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWorkspaceResourceQuota", reflect.TypeOf((*MockQuerier)(nil).CheckWorkspaceResourceQuota), ctx, id)
}

// CheckWorkspacesPerUserQuota mocks base method.
func (m *MockQuerier) CheckWorkspacesPerUserQuota(ctx context.Context, ownerID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWorkspacesPerUserQuota", ctx, ownerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckWorkspacesPerUserQuota indicates an expected call of CheckWorkspacesPerUserQuota.
func (mr *MockQuerierMockRecorder) CheckWorkspacesPerUserQuota(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWorkspacesPerUserQuota", reflect.TypeOf((*MockQuerier)(nil).CheckWorkspacesPerUserQuota), ctx, ownerID)
}

// CompleteFileUpload mocks base method.
func (m *MockQuerier) CompleteFileUpload(ctx context.Context, arg sqlc.CompleteFileUploadParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteFileUpload", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteFileUpload indicates an expected call of CompleteFileUpload.
func (mr *MockQuerierMockRecorder) CompleteFileUpload(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteFileUpload", reflect.TypeOf((*MockQuerier)(nil).CompleteFileUpload), ctx, arg)
}

// ConsumeEmailVerificationChallenge mocks base method.
func (m *MockQuerier) ConsumeEmailVerificationChallenge(ctx context.Context, id uuid.UUID) (sqlc.EmailVerificationChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeEmailVerificationChallenge", ctx, id)
	ret0, _ := ret[0].(sqlc.EmailVerificationChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeEmailVerificationChallenge indicates an expected call of ConsumeEmailVerificationChallenge.
func (mr *MockQuerierMockRecorder) ConsumeEmailVerificationChallenge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeEmailVerificationChallenge", reflect.TypeOf((*MockQuerier)(nil).ConsumeEmailVerificationChallenge), ctx, id)
}

// CountUnseenShares mocks base method.
func (m *MockQuerier) CountUnseenShares(ctx context.Context, sharedFor sql.NullString) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnseenShares", ctx, sharedFor)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnseenShares indicates an expected call of CountUnseenShares.
func (mr *MockQuerierMockRecorder) CountUnseenShares(ctx, sharedFor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnseenShares", reflect.TypeOf((*MockQuerier)(nil).CountUnseenShares), ctx, sharedFor)
}

// CreateAPIKey mocks base method.
func (m *MockQuerier) CreateAPIKey(ctx context.Context, arg sqlc.CreateAPIKeyParams) (sqlc.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockQuerierMockRecorder) CreateAPIKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockQuerier)(nil).CreateAPIKey), ctx, arg)
}

// CreateAPIKeyScope mocks base method.
func (m *MockQuerier) CreateAPIKeyScope(ctx context.Context, arg sqlc.CreateAPIKeyScopeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKeyScope", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAPIKeyScope indicates an expected call of CreateAPIKeyScope.
func (mr *MockQuerierMockRecorder) CreateAPIKeyScope(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKeyScope", reflect.TypeOf((*MockQuerier)(nil).CreateAPIKeyScope), ctx, arg)
}

// CreateAuthRateLimit mocks base method.
func (m *MockQuerier) CreateAuthRateLimit(ctx context.Context, arg sqlc.CreateAuthRateLimitParams) (sqlc.AuthRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthRateLimit", ctx, arg)
	ret0, _ := ret[0].(sqlc.AuthRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthRateLimit indicates an expected call of CreateAuthRateLimit.
func (mr *MockQuerierMockRecorder) CreateAuthRateLimit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthRateLimit", reflect.TypeOf((*MockQuerier)(nil).CreateAuthRateLimit), ctx, arg)
}

// CreateEmailVerificationChallenge mocks base method.
func (m *MockQuerier) CreateEmailVerificationChallenge(ctx context.Context, arg sqlc.CreateEmailVerificationChallengeParams) (sqlc.EmailVerificationChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailVerificationChallenge", ctx, arg)
	ret0, _ := ret[0].(sqlc.EmailVerificationChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailVerificationChallenge indicates an expected call of CreateEmailVerificationChallenge.
func (mr *MockQuerierMockRecorder) CreateEmailVerificationChallenge(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailVerificationChallenge", reflect.TypeOf((*MockQuerier)(nil).CreateEmailVerificationChallenge), ctx, arg)
}

// CreateFileUpload mocks base method.
func (m *MockQuerier) CreateFileUpload(ctx context.Context, arg sqlc.CreateFileUploadParams) (sqlc.FileUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileUpload", ctx, arg)
	ret0, _ := ret[0].(sqlc.FileUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFileUpload indicates an expected call of CreateFileUpload.
func (mr *MockQuerierMockRecorder) CreateFileUpload(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileUpload", reflect.TypeOf((*MockQuerier)(nil).CreateFileUpload), ctx, arg)
}

// CreateIdentity mocks base method.
func (m *MockQuerier) CreateIdentity(ctx context.Context, arg sqlc.CreateIdentityParams) (sqlc.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentity", ctx, arg)
	ret0, _ := ret[0].(sqlc.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIdentity indicates an expected call of CreateIdentity.
func (mr *MockQuerierMockRecorder) CreateIdentity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentity", reflect.TypeOf((*MockQuerier)(nil).CreateIdentity), ctx, arg)
}

// CreatePasswordCredentials mocks base method.
func (m *MockQuerier) CreatePasswordCredentials(ctx context.Context, arg sqlc.CreatePasswordCredentialsParams) (sqlc.PasswordCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasswordCredentials", ctx, arg)
	ret0, _ := ret[0].(sqlc.PasswordCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePasswordCredentials indicates an expected call of CreatePasswordCredentials.
func (mr *MockQuerierMockRecorder) CreatePasswordCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasswordCredentials", reflect.TypeOf((*MockQuerier)(nil).CreatePasswordCredentials), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockQuerier) CreateSession(ctx context.Context, arg sqlc.CreateSessionParams) (sqlc.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(sqlc.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockQuerierMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockQuerier)(nil).CreateSession), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, userEmail string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userEmail)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, userEmail)
}

// CreateWorkspace mocks base method.
func (m *MockQuerier) CreateWorkspace(ctx context.Context, arg sqlc.CreateWorkspaceParams) (sqlc.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", ctx, arg)
	ret0, _ := ret[0].(sqlc.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockQuerierMockRecorder) CreateWorkspace(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockQuerier)(nil).CreateWorkspace), ctx, arg)
}

// CreateWorkspaceFile mocks base method.
func (m *MockQuerier) CreateWorkspaceFile(ctx context.Context, arg sqlc.CreateWorkspaceFileParams) (sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceFile", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceFile indicates an expected call of CreateWorkspaceFile.
func (mr *MockQuerierMockRecorder) CreateWorkspaceFile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceFile", reflect.TypeOf((*MockQuerier)(nil).CreateWorkspaceFile), ctx, arg)
}

// CreateWorkspaceFolder mocks base method.
func (m *MockQuerier) CreateWorkspaceFolder(ctx context.Context, arg sqlc.CreateWorkspaceFolderParams) (sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceFolder", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceFolder indicates an expected call of CreateWorkspaceFolder.
func (mr *MockQuerierMockRecorder) CreateWorkspaceFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceFolder", reflect.TypeOf((*MockQuerier)(nil).CreateWorkspaceFolder), ctx, arg)
}

// CreateWorkspaceInvite mocks base method.
func (m *MockQuerier) CreateWorkspaceInvite(ctx context.Context, arg sqlc.CreateWorkspaceInviteParams) (sqlc.WorkspaceInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceInvite", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceInvite indicates an expected call of CreateWorkspaceInvite.
func (mr *MockQuerierMockRecorder) CreateWorkspaceInvite(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceInvite", reflect.TypeOf((*MockQuerier)(nil).CreateWorkspaceInvite), ctx, arg)
}

// CreateWorkspaceMember mocks base method.
func (m *MockQuerier) CreateWorkspaceMember(ctx context.Context, arg sqlc.CreateWorkspaceMemberParams) (sqlc.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceMember", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceMember indicates an expected call of CreateWorkspaceMember.
func (mr *MockQuerierMockRecorder) CreateWorkspaceMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceMember", reflect.TypeOf((*MockQuerier)(nil).CreateWorkspaceMember), ctx, arg)
}

// DeleteAccount mocks base method.
func (m *MockQuerier) DeleteAccount(ctx context.Context, id uuid.UUID) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, id)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockQuerierMockRecorder) DeleteAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockQuerier)(nil).DeleteAccount), ctx, id)
}

// DeleteEmailVerificationChallengeById mocks base method.
func (m *MockQuerier) DeleteEmailVerificationChallengeById(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailVerificationChallengeById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailVerificationChallengeById indicates an expected call of DeleteEmailVerificationChallengeById.
func (mr *MockQuerierMockRecorder) DeleteEmailVerificationChallengeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailVerificationChallengeById", reflect.TypeOf((*MockQuerier)(nil).DeleteEmailVerificationChallengeById), ctx, id)
}

// DeleteFileByNameAndId mocks base method.
func (m *MockQuerier) DeleteFileByNameAndId(ctx context.Context, arg sqlc.DeleteFileByNameAndIdParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileByNameAndId", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileByNameAndId indicates an expected call of DeleteFileByNameAndId.
func (mr *MockQuerierMockRecorder) DeleteFileByNameAndId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileByNameAndId", reflect.TypeOf((*MockQuerier)(nil).DeleteFileByNameAndId), ctx, arg)
}

// DeleteFileUploadPartsByUploadID mocks base method.
func (m *MockQuerier) DeleteFileUploadPartsByUploadID(ctx context.Context, uploadID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileUploadPartsByUploadID", ctx, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileUploadPartsByUploadID indicates an expected call of DeleteFileUploadPartsByUploadID.
func (mr *MockQuerierMockRecorder) DeleteFileUploadPartsByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileUploadPartsByUploadID", reflect.TypeOf((*MockQuerier)(nil).DeleteFileUploadPartsByUploadID), ctx, uploadID)
}

// DeletePlan mocks base method.
func (m *MockQuerier) DeletePlan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlan indicates an expected call of DeletePlan.
func (mr *MockQuerierMockRecorder) DeletePlan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlan", reflect.TypeOf((*MockQuerier)(nil).DeletePlan), ctx, id)
}

// DeletePlanFeatures mocks base method.
func (m *MockQuerier) DeletePlanFeatures(ctx context.Context, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlanFeatures", ctx, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlanFeatures indicates an expected call of DeletePlanFeatures.
func (mr *MockQuerierMockRecorder) DeletePlanFeatures(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlanFeatures", reflect.TypeOf((*MockQuerier)(nil).DeletePlanFeatures), ctx, planID)
}

// DeleteSession mocks base method.
func (m *MockQuerier) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockQuerierMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockQuerier)(nil).DeleteSession), ctx, id)
}

// DeleteShareByToken mocks base method.
func (m *MockQuerier) DeleteShareByToken(ctx context.Context, arg sqlc.DeleteShareByTokenParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShareByToken", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteShareByToken indicates an expected call of DeleteShareByToken.
func (mr *MockQuerierMockRecorder) DeleteShareByToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShareByToken", reflect.TypeOf((*MockQuerier)(nil).DeleteShareByToken), ctx, arg)
}

// DeleteUserPlan mocks base method.
func (m *MockQuerier) DeleteUserPlan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserPlan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserPlan indicates an expected call of DeleteUserPlan.
func (mr *MockQuerierMockRecorder) DeleteUserPlan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPlan", reflect.TypeOf((*MockQuerier)(nil).DeleteUserPlan), ctx, id)
}

// DeleteWorkspace mocks base method.
func (m *MockQuerier) DeleteWorkspace(ctx context.Context, id uuid.UUID) (sqlc.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspace", ctx, id)
	ret0, _ := ret[0].(sqlc.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkspace indicates an expected call of DeleteWorkspace.
func (mr *MockQuerierMockRecorder) DeleteWorkspace(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspace", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspace), ctx, id)
}

// DeleteWorkspaceFileById mocks base method.
func (m *MockQuerier) DeleteWorkspaceFileById(ctx context.Context, arg sqlc.DeleteWorkspaceFileByIdParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceFileById", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceFileById indicates an expected call of DeleteWorkspaceFileById.
func (mr *MockQuerierMockRecorder) DeleteWorkspaceFileById(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceFileById", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspaceFileById), ctx, arg)
}

// DeleteWorkspaceFilesByPath mocks base method.
func (m *MockQuerier) DeleteWorkspaceFilesByPath(ctx context.Context, arg sqlc.DeleteWorkspaceFilesByPathParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceFilesByPath", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceFilesByPath indicates an expected call of DeleteWorkspaceFilesByPath.
func (mr *MockQuerierMockRecorder) DeleteWorkspaceFilesByPath(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceFilesByPath", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspaceFilesByPath), ctx, arg)
}

// DeleteWorkspaceFilesByPathPrefix mocks base method.
func (m *MockQuerier) DeleteWorkspaceFilesByPathPrefix(ctx context.Context, arg sqlc.DeleteWorkspaceFilesByPathPrefixParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceFilesByPathPrefix", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceFilesByPathPrefix indicates an expected call of DeleteWorkspaceFilesByPathPrefix.
func (mr *MockQuerierMockRecorder) DeleteWorkspaceFilesByPathPrefix(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceFilesByPathPrefix", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspaceFilesByPathPrefix), ctx, arg)
}

// DeleteWorkspaceInvite mocks base method.
func (m *MockQuerier) DeleteWorkspaceInvite(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceInvite", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceInvite indicates an expected call of DeleteWorkspaceInvite.
func (mr *MockQuerierMockRecorder) DeleteWorkspaceInvite(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceInvite", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspaceInvite), ctx, id)
}

// DeleteWorkspaceInviteByToken mocks base method.
func (m *MockQuerier) DeleteWorkspaceInviteByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceInviteByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceInviteByToken indicates an expected call of DeleteWorkspaceInviteByToken.
func (mr *MockQuerierMockRecorder) DeleteWorkspaceInviteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceInviteByToken", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspaceInviteByToken), ctx, token)
}

// DeleteWorkspaceMember mocks base method.
func (m *MockQuerier) DeleteWorkspaceMember(ctx context.Context, arg sqlc.DeleteWorkspaceMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceMember", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceMember indicates an expected call of DeleteWorkspaceMember.
func (mr *MockQuerierMockRecorder) DeleteWorkspaceMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceMember", reflect.TypeOf((*MockQuerier)(nil).DeleteWorkspaceMember), ctx, arg)
}

// FailFileUpload mocks base method.
func (m *MockQuerier) FailFileUpload(ctx context.Context, id uuid.UUID) (sqlc.FileUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailFileUpload", ctx, id)
	ret0, _ := ret[0].(sqlc.FileUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailFileUpload indicates an expected call of FailFileUpload.
func (mr *MockQuerierMockRecorder) FailFileUpload(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailFileUpload", reflect.TypeOf((*MockQuerier)(nil).FailFileUpload), ctx, id)
}

// GetAPIKey mocks base method.
func (m *MockQuerier) GetAPIKey(ctx context.Context, id uuid.UUID) (sqlc.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey", ctx, id)
	ret0, _ := ret[0].(sqlc.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockQuerierMockRecorder) GetAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockQuerier)(nil).GetAPIKey), ctx, id)
}

// GetAuthRateLimitByKeyAndScope mocks base method.
func (m *MockQuerier) GetAuthRateLimitByKeyAndScope(ctx context.Context, arg sqlc.GetAuthRateLimitByKeyAndScopeParams) (sqlc.AuthRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthRateLimitByKeyAndScope", ctx, arg)
	ret0, _ := ret[0].(sqlc.AuthRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthRateLimitByKeyAndScope indicates an expected call of GetAuthRateLimitByKeyAndScope.
func (mr *MockQuerierMockRecorder) GetAuthRateLimitByKeyAndScope(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthRateLimitByKeyAndScope", reflect.TypeOf((*MockQuerier)(nil).GetAuthRateLimitByKeyAndScope), ctx, arg)
}

// GetAuthorizedCLIUserInfoByAPIKey mocks base method.
func (m *MockQuerier) GetAuthorizedCLIUserInfoByAPIKey(ctx context.Context, crypt string) (sqlc.GetAuthorizedCLIUserInfoByAPIKeyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizedCLIUserInfoByAPIKey", ctx, crypt)
	ret0, _ := ret[0].(sqlc.GetAuthorizedCLIUserInfoByAPIKeyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizedCLIUserInfoByAPIKey indicates an expected call of GetAuthorizedCLIUserInfoByAPIKey.
func (mr *MockQuerierMockRecorder) GetAuthorizedCLIUserInfoByAPIKey(ctx, crypt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizedCLIUserInfoByAPIKey", reflect.TypeOf((*MockQuerier)(nil).GetAuthorizedCLIUserInfoByAPIKey), ctx, crypt)
}

// GetBucketAndObjectFromToken mocks base method.
func (m *MockQuerier) GetBucketAndObjectFromToken(ctx context.Context, sharingToken string) (sqlc.GetBucketAndObjectFromTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketAndObjectFromToken", ctx, sharingToken)
	ret0, _ := ret[0].(sqlc.GetBucketAndObjectFromTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketAndObjectFromToken indicates an expected call of GetBucketAndObjectFromToken.
func (mr *MockQuerierMockRecorder) GetBucketAndObjectFromToken(ctx, sharingToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketAndObjectFromToken", reflect.TypeOf((*MockQuerier)(nil).GetBucketAndObjectFromToken), ctx, sharingToken)
}

// GetBucketObjectAndOwnerFromPrivateToken mocks base method.
func (m *MockQuerier) GetBucketObjectAndOwnerFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (sqlc.GetBucketObjectAndOwnerFromPrivateTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketObjectAndOwnerFromPrivateToken", ctx, privateDownloadToken)
	ret0, _ := ret[0].(sqlc.GetBucketObjectAndOwnerFromPrivateTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketObjectAndOwnerFromPrivateToken indicates an expected call of GetBucketObjectAndOwnerFromPrivateToken.
func (mr *MockQuerierMockRecorder) GetBucketObjectAndOwnerFromPrivateToken(ctx, privateDownloadToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketObjectAndOwnerFromPrivateToken", reflect.TypeOf((*MockQuerier)(nil).GetBucketObjectAndOwnerFromPrivateToken), ctx, privateDownloadToken)
}

// GetEmailVerificationChallengeById mocks base method.
func (m *MockQuerier) GetEmailVerificationChallengeById(ctx context.Context, id uuid.UUID) (sqlc.EmailVerificationChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationChallengeById", ctx, id)
	ret0, _ := ret[0].(sqlc.EmailVerificationChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationChallengeById indicates an expected call of GetEmailVerificationChallengeById.
func (mr *MockQuerierMockRecorder) GetEmailVerificationChallengeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationChallengeById", reflect.TypeOf((*MockQuerier)(nil).GetEmailVerificationChallengeById), ctx, id)
}

// GetEmailVerificationCode mocks base method.
func (m *MockQuerier) GetEmailVerificationCode(ctx context.Context, arg sqlc.GetEmailVerificationCodeParams) (sqlc.EmailVerificationChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationCode", ctx, arg)
	ret0, _ := ret[0].(sqlc.EmailVerificationChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationCode indicates an expected call of GetEmailVerificationCode.
func (mr *MockQuerierMockRecorder) GetEmailVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationCode", reflect.TypeOf((*MockQuerier)(nil).GetEmailVerificationCode), ctx, arg)
}

// GetExistingPublicShare mocks base method.
func (m *MockQuerier) GetExistingPublicShare(ctx context.Context, arg sqlc.GetExistingPublicShareParams) (sqlc.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExistingPublicShare", ctx, arg)
	ret0, _ := ret[0].(sqlc.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExistingPublicShare indicates an expected call of GetExistingPublicShare.
func (mr *MockQuerierMockRecorder) GetExistingPublicShare(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExistingPublicShare", reflect.TypeOf((*MockQuerier)(nil).GetExistingPublicShare), ctx, arg)
}

// GetFileById mocks base method.
func (m *MockQuerier) GetFileById(ctx context.Context, id int32) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileById", ctx, id)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileById indicates an expected call of GetFileById.
func (mr *MockQuerierMockRecorder) GetFileById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileById", reflect.TypeOf((*MockQuerier)(nil).GetFileById), ctx, id)
}

// GetFileByOwnerAndName mocks base method.
func (m *MockQuerier) GetFileByOwnerAndName(ctx context.Context, arg sqlc.GetFileByOwnerAndNameParams) (sqlc.GetFileByOwnerAndNameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByOwnerAndName", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetFileByOwnerAndNameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByOwnerAndName indicates an expected call of GetFileByOwnerAndName.
func (mr *MockQuerierMockRecorder) GetFileByOwnerAndName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByOwnerAndName", reflect.TypeOf((*MockQuerier)(nil).GetFileByOwnerAndName), ctx, arg)
}

// GetFileFromChecksum mocks base method.
func (m *MockQuerier) GetFileFromChecksum(ctx context.Context, arg sqlc.GetFileFromChecksumParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileFromChecksum", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileFromChecksum indicates an expected call of GetFileFromChecksum.
func (mr *MockQuerierMockRecorder) GetFileFromChecksum(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileFromChecksum", reflect.TypeOf((*MockQuerier)(nil).GetFileFromChecksum), ctx, arg)
}

// GetFileFromPrivateToken mocks base method.
func (m *MockQuerier) GetFileFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileFromPrivateToken", ctx, privateDownloadToken)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileFromPrivateToken indicates an expected call of GetFileFromPrivateToken.
func (mr *MockQuerierMockRecorder) GetFileFromPrivateToken(ctx, privateDownloadToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileFromPrivateToken", reflect.TypeOf((*MockQuerier)(nil).GetFileFromPrivateToken), ctx, privateDownloadToken)
}

// GetFileIdFromToken mocks base method.
func (m *MockQuerier) GetFileIdFromToken(ctx context.Context, privateDownloadToken sql.NullString) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileIdFromToken", ctx, privateDownloadToken)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileIdFromToken indicates an expected call of GetFileIdFromToken.
func (mr *MockQuerierMockRecorder) GetFileIdFromToken(ctx, privateDownloadToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileIdFromToken", reflect.TypeOf((*MockQuerier)(nil).GetFileIdFromToken), ctx, privateDownloadToken)
}

// GetFileUploadById mocks base method.
func (m *MockQuerier) GetFileUploadById(ctx context.Context, id uuid.UUID) (sqlc.FileUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileUploadById", ctx, id)
	ret0, _ := ret[0].(sqlc.FileUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileUploadById indicates an expected call of GetFileUploadById.
func (mr *MockQuerierMockRecorder) GetFileUploadById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileUploadById", reflect.TypeOf((*MockQuerier)(nil).GetFileUploadById), ctx, id)
}

// GetFilesByOwner mocks base method.
func (m *MockQuerier) GetFilesByOwner(ctx context.Context, ownerID uuid.UUID) ([]sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesByOwner", ctx, ownerID)
	ret0, _ := ret[0].([]sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesByOwner indicates an expected call of GetFilesByOwner.
func (mr *MockQuerierMockRecorder) GetFilesByOwner(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesByOwner", reflect.TypeOf((*MockQuerier)(nil).GetFilesByOwner), ctx, ownerID)
}

// GetFilesSharedByUser mocks base method.
func (m *MockQuerier) GetFilesSharedByUser(ctx context.Context, sharedBy sql.NullString) ([]sqlc.GetFilesSharedByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesSharedByUser", ctx, sharedBy)
	ret0, _ := ret[0].([]sqlc.GetFilesSharedByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesSharedByUser indicates an expected call of GetFilesSharedByUser.
func (mr *MockQuerierMockRecorder) GetFilesSharedByUser(ctx, sharedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesSharedByUser", reflect.TypeOf((*MockQuerier)(nil).GetFilesSharedByUser), ctx, sharedBy)
}

// GetFilesSharedWithUser mocks base method.
func (m *MockQuerier) GetFilesSharedWithUser(ctx context.Context, sharedFor sql.NullString) ([]sqlc.GetFilesSharedWithUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesSharedWithUser", ctx, sharedFor)
	ret0, _ := ret[0].([]sqlc.GetFilesSharedWithUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesSharedWithUser indicates an expected call of GetFilesSharedWithUser.
func (mr *MockQuerierMockRecorder) GetFilesSharedWithUser(ctx, sharedFor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesSharedWithUser", reflect.TypeOf((*MockQuerier)(nil).GetFilesSharedWithUser), ctx, sharedFor)
}

// GetIdentitiesByUserEmail mocks base method.
func (m *MockQuerier) GetIdentitiesByUserEmail(ctx context.Context, email sql.NullString) ([]sqlc.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentitiesByUserEmail", ctx, email)
	ret0, _ := ret[0].([]sqlc.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentitiesByUserEmail indicates an expected call of GetIdentitiesByUserEmail.
func (mr *MockQuerierMockRecorder) GetIdentitiesByUserEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentitiesByUserEmail", reflect.TypeOf((*MockQuerier)(nil).GetIdentitiesByUserEmail), ctx, email)
}

// GetIdentitiesByUserID mocks base method.
func (m *MockQuerier) GetIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]sqlc.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentitiesByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentitiesByUserID indicates an expected call of GetIdentitiesByUserID.
func (mr *MockQuerierMockRecorder) GetIdentitiesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentitiesByUserID", reflect.TypeOf((*MockQuerier)(nil).GetIdentitiesByUserID), ctx, userID)
}

// GetIdentityByProvider mocks base method.
func (m *MockQuerier) GetIdentityByProvider(ctx context.Context, arg sqlc.GetIdentityByProviderParams) (sqlc.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityByProvider", ctx, arg)
	ret0, _ := ret[0].(sqlc.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityByProvider indicates an expected call of GetIdentityByProvider.
func (mr *MockQuerierMockRecorder) GetIdentityByProvider(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityByProvider", reflect.TypeOf((*MockQuerier)(nil).GetIdentityByProvider), ctx, arg)
}

// GetIdentityByUserID mocks base method.
func (m *MockQuerier) GetIdentityByUserID(ctx context.Context, userID uuid.UUID) (sqlc.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityByUserID", ctx, userID)
	ret0, _ := ret[0].(sqlc.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityByUserID indicates an expected call of GetIdentityByUserID.
func (mr *MockQuerierMockRecorder) GetIdentityByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityByUserID", reflect.TypeOf((*MockQuerier)(nil).GetIdentityByUserID), ctx, userID)
}

// GetNoteForFileById mocks base method.
func (m *MockQuerier) GetNoteForFileById(ctx context.Context, arg sqlc.GetNoteForFileByIdParams) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteForFileById", ctx, arg)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteForFileById indicates an expected call of GetNoteForFileById.
func (mr *MockQuerierMockRecorder) GetNoteForFileById(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteForFileById", reflect.TypeOf((*MockQuerier)(nil).GetNoteForFileById), ctx, arg)
}

// GetPasswordCredentialsByUserId mocks base method.
func (m *MockQuerier) GetPasswordCredentialsByUserId(ctx context.Context, userID uuid.UUID) (sqlc.PasswordCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordCredentialsByUserId", ctx, userID)
	ret0, _ := ret[0].(sqlc.PasswordCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordCredentialsByUserId indicates an expected call of GetPasswordCredentialsByUserId.
func (mr *MockQuerierMockRecorder) GetPasswordCredentialsByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordCredentialsByUserId", reflect.TypeOf((*MockQuerier)(nil).GetPasswordCredentialsByUserId), ctx, userID)
}

// GetPlanByID mocks base method.
func (m *MockQuerier) GetPlanByID(ctx context.Context, id uuid.UUID) (sqlc.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanByID indicates an expected call of GetPlanByID.
func (mr *MockQuerierMockRecorder) GetPlanByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanByID", reflect.TypeOf((*MockQuerier)(nil).GetPlanByID), ctx, id)
}

// GetPlanByName mocks base method.
func (m *MockQuerier) GetPlanByName(ctx context.Context, name string) (sqlc.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanByName", ctx, name)
	ret0, _ := ret[0].(sqlc.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanByName indicates an expected call of GetPlanByName.
func (mr *MockQuerierMockRecorder) GetPlanByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanByName", reflect.TypeOf((*MockQuerier)(nil).GetPlanByName), ctx, name)
}

// GetPlanFeatures mocks base method.
func (m *MockQuerier) GetPlanFeatures(ctx context.Context, planID uuid.UUID) ([]sqlc.PlanFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanFeatures", ctx, planID)
	ret0, _ := ret[0].([]sqlc.PlanFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanFeatures indicates an expected call of GetPlanFeatures.
func (mr *MockQuerierMockRecorder) GetPlanFeatures(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanFeatures", reflect.TypeOf((*MockQuerier)(nil).GetPlanFeatures), ctx, planID)
}

// GetPlans mocks base method.
func (m *MockQuerier) GetPlans(ctx context.Context) ([]sqlc.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlans", ctx)
	ret0, _ := ret[0].([]sqlc.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlans indicates an expected call of GetPlans.
func (mr *MockQuerierMockRecorder) GetPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlans", reflect.TypeOf((*MockQuerier)(nil).GetPlans), ctx)
}

// GetPrivateDownloadTokenByFileName mocks base method.
func (m *MockQuerier) GetPrivateDownloadTokenByFileName(ctx context.Context, arg sqlc.GetPrivateDownloadTokenByFileNameParams) (sql.NullString, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateDownloadTokenByFileName", ctx, arg)
	ret0, _ := ret[0].(sql.NullString)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateDownloadTokenByFileName indicates an expected call of GetPrivateDownloadTokenByFileName.
func (mr *MockQuerierMockRecorder) GetPrivateDownloadTokenByFileName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateDownloadTokenByFileName", reflect.TypeOf((*MockQuerier)(nil).GetPrivateDownloadTokenByFileName), ctx, arg)
}

// GetPublicShareMetadata mocks base method.
func (m *MockQuerier) GetPublicShareMetadata(ctx context.Context, sharingToken string) (sqlc.GetPublicShareMetadataRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicShareMetadata", ctx, sharingToken)
	ret0, _ := ret[0].(sqlc.GetPublicShareMetadataRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicShareMetadata indicates an expected call of GetPublicShareMetadata.
func (mr *MockQuerierMockRecorder) GetPublicShareMetadata(ctx, sharingToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicShareMetadata", reflect.TypeOf((*MockQuerier)(nil).GetPublicShareMetadata), ctx, sharingToken)
}

// GetSession mocks base method.
func (m *MockQuerier) GetSession(ctx context.Context, id uuid.UUID) (sqlc.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(sqlc.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockQuerierMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockQuerier)(nil).GetSession), ctx, id)
}

// GetSharedFileIdFromToken mocks base method.
func (m *MockQuerier) GetSharedFileIdFromToken(ctx context.Context, sharingToken string) (sql.NullInt32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedFileIdFromToken", ctx, sharingToken)
	ret0, _ := ret[0].(sql.NullInt32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedFileIdFromToken indicates an expected call of GetSharedFileIdFromToken.
func (mr *MockQuerierMockRecorder) GetSharedFileIdFromToken(ctx, sharingToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedFileIdFromToken", reflect.TypeOf((*MockQuerier)(nil).GetSharedFileIdFromToken), ctx, sharingToken)
}

// GetTokenExpirationTime mocks base method.
func (m *MockQuerier) GetTokenExpirationTime(ctx context.Context, sharingToken string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenExpirationTime", ctx, sharingToken)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenExpirationTime indicates an expected call of GetTokenExpirationTime.
func (mr *MockQuerierMockRecorder) GetTokenExpirationTime(ctx, sharingToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenExpirationTime", reflect.TypeOf((*MockQuerier)(nil).GetTokenExpirationTime), ctx, sharingToken)
}

// GetUserBucketById mocks base method.
func (m *MockQuerier) GetUserBucketById(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBucketById", ctx, id)
	ret0, _ := ret[0].(sql.NullString)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBucketById indicates an expected call of GetUserBucketById.
func (mr *MockQuerierMockRecorder) GetUserBucketById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBucketById", reflect.TypeOf((*MockQuerier)(nil).GetUserBucketById), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, userEmail string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, userEmail)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, userEmail)
}

// GetUserById mocks base method.
func (m *MockQuerier) GetUserById(ctx context.Context, id uuid.UUID) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockQuerierMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockQuerier)(nil).GetUserById), ctx, id)
}

// GetUserDailyShares mocks base method.
func (m *MockQuerier) GetUserDailyShares(ctx context.Context, id uuid.UUID) ([]sqlc.GetUserDailySharesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDailyShares", ctx, id)
	ret0, _ := ret[0].([]sqlc.GetUserDailySharesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDailyShares indicates an expected call of GetUserDailyShares.
func (mr *MockQuerierMockRecorder) GetUserDailyShares(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDailyShares", reflect.TypeOf((*MockQuerier)(nil).GetUserDailyShares), ctx, id)
}

// GetUserDailyUploads mocks base method.
func (m *MockQuerier) GetUserDailyUploads(ctx context.Context, ownerID uuid.UUID) ([]sqlc.GetUserDailyUploadsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDailyUploads", ctx, ownerID)
	ret0, _ := ret[0].([]sqlc.GetUserDailyUploadsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDailyUploads indicates an expected call of GetUserDailyUploads.
func (mr *MockQuerierMockRecorder) GetUserDailyUploads(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDailyUploads", reflect.TypeOf((*MockQuerier)(nil).GetUserDailyUploads), ctx, ownerID)
}

// GetUserInvitesByEmail mocks base method.
func (m *MockQuerier) GetUserInvitesByEmail(ctx context.Context, email string) ([]sqlc.GetUserInvitesByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInvitesByEmail", ctx, email)
	ret0, _ := ret[0].([]sqlc.GetUserInvitesByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInvitesByEmail indicates an expected call of GetUserInvitesByEmail.
func (mr *MockQuerierMockRecorder) GetUserInvitesByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInvitesByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserInvitesByEmail), ctx, email)
}

// GetUserPlan mocks base method.
func (m *MockQuerier) GetUserPlan(ctx context.Context, id uuid.UUID) (sqlc.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPlan", ctx, id)
	ret0, _ := ret[0].(sqlc.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPlan indicates an expected call of GetUserPlan.
func (mr *MockQuerierMockRecorder) GetUserPlan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPlan", reflect.TypeOf((*MockQuerier)(nil).GetUserPlan), ctx, id)
}

// GetUserStats mocks base method.
func (m *MockQuerier) GetUserStats(ctx context.Context, ownerID uuid.UUID) (sqlc.GetUserStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStats", ctx, ownerID)
	ret0, _ := ret[0].(sqlc.GetUserStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockQuerierMockRecorder) GetUserStats(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockQuerier)(nil).GetUserStats), ctx, ownerID)
}

// GetUserWithPlan mocks base method.
func (m *MockQuerier) GetUserWithPlan(ctx context.Context, id uuid.UUID) (sqlc.GetUserWithPlanRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithPlan", ctx, id)
	ret0, _ := ret[0].(sqlc.GetUserWithPlanRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithPlan indicates an expected call of GetUserWithPlan.
func (mr *MockQuerierMockRecorder) GetUserWithPlan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithPlan", reflect.TypeOf((*MockQuerier)(nil).GetUserWithPlan), ctx, id)
}

// GetUserWorkspaceRole mocks base method.
func (m *MockQuerier) GetUserWorkspaceRole(ctx context.Context, arg sqlc.GetUserWorkspaceRoleParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWorkspaceRole", ctx, arg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWorkspaceRole indicates an expected call of GetUserWorkspaceRole.
func (mr *MockQuerierMockRecorder) GetUserWorkspaceRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWorkspaceRole", reflect.TypeOf((*MockQuerier)(nil).GetUserWorkspaceRole), ctx, arg)
}

// GetUserWorkspaces mocks base method.
func (m *MockQuerier) GetUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]sqlc.GetUserWorkspacesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWorkspaces", ctx, userID)
	ret0, _ := ret[0].([]sqlc.GetUserWorkspacesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWorkspaces indicates an expected call of GetUserWorkspaces.
func (mr *MockQuerierMockRecorder) GetUserWorkspaces(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWorkspaces", reflect.TypeOf((*MockQuerier)(nil).GetUserWorkspaces), ctx, userID)
}

// GetWorkspaceById mocks base method.
func (m *MockQuerier) GetWorkspaceById(ctx context.Context, id uuid.UUID) (sqlc.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceById", ctx, id)
	ret0, _ := ret[0].(sqlc.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceById indicates an expected call of GetWorkspaceById.
func (mr *MockQuerierMockRecorder) GetWorkspaceById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceById", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceById), ctx, id)
}

// GetWorkspaceBySlug mocks base method.
func (m *MockQuerier) GetWorkspaceBySlug(ctx context.Context, slug string) (sqlc.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlc.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceBySlug indicates an expected call of GetWorkspaceBySlug.
func (mr *MockQuerierMockRecorder) GetWorkspaceBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceBySlug", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceBySlug), ctx, slug)
}

// GetWorkspaceFileById mocks base method.
func (m *MockQuerier) GetWorkspaceFileById(ctx context.Context, arg sqlc.GetWorkspaceFileByIdParams) (sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFileById", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFileById indicates an expected call of GetWorkspaceFileById.
func (mr *MockQuerierMockRecorder) GetWorkspaceFileById(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFileById", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFileById), ctx, arg)
}

// GetWorkspaceFileByName mocks base method.
func (m *MockQuerier) GetWorkspaceFileByName(ctx context.Context, arg sqlc.GetWorkspaceFileByNameParams) (sqlc.GetWorkspaceFileByNameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFileByName", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetWorkspaceFileByNameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFileByName indicates an expected call of GetWorkspaceFileByName.
func (mr *MockQuerierMockRecorder) GetWorkspaceFileByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFileByName", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFileByName), ctx, arg)
}

// GetWorkspaceFiles mocks base method.
func (m *MockQuerier) GetWorkspaceFiles(ctx context.Context, workspaceID uuid.UUID) ([]sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFiles", ctx, workspaceID)
	ret0, _ := ret[0].([]sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFiles indicates an expected call of GetWorkspaceFiles.
func (mr *MockQuerierMockRecorder) GetWorkspaceFiles(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFiles", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFiles), ctx, workspaceID)
}

// GetWorkspaceFilesAtPathWithUploaders mocks base method.
func (m *MockQuerier) GetWorkspaceFilesAtPathWithUploaders(ctx context.Context, arg sqlc.GetWorkspaceFilesAtPathWithUploadersParams) ([]sqlc.GetWorkspaceFilesAtPathWithUploadersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFilesAtPathWithUploaders", ctx, arg)
	ret0, _ := ret[0].([]sqlc.GetWorkspaceFilesAtPathWithUploadersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFilesAtPathWithUploaders indicates an expected call of GetWorkspaceFilesAtPathWithUploaders.
func (mr *MockQuerierMockRecorder) GetWorkspaceFilesAtPathWithUploaders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFilesAtPathWithUploaders", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFilesAtPathWithUploaders), ctx, arg)
}

// GetWorkspaceFilesByPath mocks base method.
func (m *MockQuerier) GetWorkspaceFilesByPath(ctx context.Context, arg sqlc.GetWorkspaceFilesByPathParams) ([]sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFilesByPath", ctx, arg)
	ret0, _ := ret[0].([]sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFilesByPath indicates an expected call of GetWorkspaceFilesByPath.
func (mr *MockQuerierMockRecorder) GetWorkspaceFilesByPath(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFilesByPath", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFilesByPath), ctx, arg)
}

// GetWorkspaceFolderByPathAndName mocks base method.
func (m *MockQuerier) GetWorkspaceFolderByPathAndName(ctx context.Context, arg sqlc.GetWorkspaceFolderByPathAndNameParams) (sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFolderByPathAndName", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFolderByPathAndName indicates an expected call of GetWorkspaceFolderByPathAndName.
func (mr *MockQuerierMockRecorder) GetWorkspaceFolderByPathAndName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFolderByPathAndName", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFolderByPathAndName), ctx, arg)
}

// GetWorkspaceFoldersAtPathWithCreators mocks base method.
func (m *MockQuerier) GetWorkspaceFoldersAtPathWithCreators(ctx context.Context, arg sqlc.GetWorkspaceFoldersAtPathWithCreatorsParams) ([]sqlc.GetWorkspaceFoldersAtPathWithCreatorsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFoldersAtPathWithCreators", ctx, arg)
	ret0, _ := ret[0].([]sqlc.GetWorkspaceFoldersAtPathWithCreatorsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFoldersAtPathWithCreators indicates an expected call of GetWorkspaceFoldersAtPathWithCreators.
func (mr *MockQuerierMockRecorder) GetWorkspaceFoldersAtPathWithCreators(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFoldersAtPathWithCreators", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFoldersAtPathWithCreators), ctx, arg)
}

// GetWorkspaceFoldersByPath mocks base method.
func (m *MockQuerier) GetWorkspaceFoldersByPath(ctx context.Context, arg sqlc.GetWorkspaceFoldersByPathParams) ([]sqlc.WorkspaceFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFoldersByPath", ctx, arg)
	ret0, _ := ret[0].([]sqlc.WorkspaceFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFoldersByPath indicates an expected call of GetWorkspaceFoldersByPath.
func (mr *MockQuerierMockRecorder) GetWorkspaceFoldersByPath(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFoldersByPath", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceFoldersByPath), ctx, arg)
}

// GetWorkspaceInviteByToken mocks base method.
func (m *MockQuerier) GetWorkspaceInviteByToken(ctx context.Context, token string) (sqlc.WorkspaceInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceInviteByToken", ctx, token)
	ret0, _ := ret[0].(sqlc.WorkspaceInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceInviteByToken indicates an expected call of GetWorkspaceInviteByToken.
func (mr *MockQuerierMockRecorder) GetWorkspaceInviteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceInviteByToken", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceInviteByToken), ctx, token)
}

// GetWorkspaceInvites mocks base method.
func (m *MockQuerier) GetWorkspaceInvites(ctx context.Context, workspaceID uuid.UUID) ([]sqlc.WorkspaceInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceInvites", ctx, workspaceID)
	ret0, _ := ret[0].([]sqlc.WorkspaceInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceInvites indicates an expected call of GetWorkspaceInvites.
func (mr *MockQuerierMockRecorder) GetWorkspaceInvites(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceInvites", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceInvites), ctx, workspaceID)
}

// GetWorkspaceMember mocks base method.
func (m *MockQuerier) GetWorkspaceMember(ctx context.Context, arg sqlc.GetWorkspaceMemberParams) (sqlc.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMember", ctx, arg)
	ret0, _ := ret[0].(sqlc.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMember indicates an expected call of GetWorkspaceMember.
func (mr *MockQuerierMockRecorder) GetWorkspaceMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMember", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceMember), ctx, arg)
}

// GetWorkspaceMembers mocks base method.
func (m *MockQuerier) GetWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]sqlc.GetWorkspaceMembersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMembers", ctx, workspaceID)
	ret0, _ := ret[0].([]sqlc.GetWorkspaceMembersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMembers indicates an expected call of GetWorkspaceMembers.
func (mr *MockQuerierMockRecorder) GetWorkspaceMembers(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMembers", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceMembers), ctx, workspaceID)
}

// GetWorkspaceQuotaDetails mocks base method.
func (m *MockQuerier) GetWorkspaceQuotaDetails(ctx context.Context, id uuid.UUID) (sqlc.GetWorkspaceQuotaDetailsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceQuotaDetails", ctx, id)
	ret0, _ := ret[0].(sqlc.GetWorkspaceQuotaDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceQuotaDetails indicates an expected call of GetWorkspaceQuotaDetails.
func (mr *MockQuerierMockRecorder) GetWorkspaceQuotaDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceQuotaDetails", reflect.TypeOf((*MockQuerier)(nil).GetWorkspaceQuotaDetails), ctx, id)
}

// IncrementAuthRateLimitAttemptCount mocks base method.
func (m *MockQuerier) IncrementAuthRateLimitAttemptCount(ctx context.Context, arg sqlc.IncrementAuthRateLimitAttemptCountParams) (sqlc.AuthRateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAuthRateLimitAttemptCount", ctx, arg)
	ret0, _ := ret[0].(sqlc.AuthRateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAuthRateLimitAttemptCount indicates an expected call of IncrementAuthRateLimitAttemptCount.
func (mr *MockQuerierMockRecorder) IncrementAuthRateLimitAttemptCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAuthRateLimitAttemptCount", reflect.TypeOf((*MockQuerier)(nil).IncrementAuthRateLimitAttemptCount), ctx, arg)
}

// IncrementShareFailedAttempts mocks base method.
func (m *MockQuerier) IncrementShareFailedAttempts(ctx context.Context, sharingToken string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementShareFailedAttempts", ctx, sharingToken)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementShareFailedAttempts indicates an expected call of IncrementShareFailedAttempts.
func (mr *MockQuerierMockRecorder) IncrementShareFailedAttempts(ctx, sharingToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementShareFailedAttempts", reflect.TypeOf((*MockQuerier)(nil).IncrementShareFailedAttempts), ctx, sharingToken)
}

// InsertFile mocks base method.
func (m *MockQuerier) InsertFile(ctx context.Context, arg sqlc.InsertFileParams) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFile", ctx, arg)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertFile indicates an expected call of InsertFile.
func (mr *MockQuerierMockRecorder) InsertFile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFile", reflect.TypeOf((*MockQuerier)(nil).InsertFile), ctx, arg)
}

// InsertPublicShare mocks base method.
func (m *MockQuerier) InsertPublicShare(ctx context.Context, arg sqlc.InsertPublicShareParams) (sqlc.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPublicShare", ctx, arg)
	ret0, _ := ret[0].(sqlc.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPublicShare indicates an expected call of InsertPublicShare.
func (mr *MockQuerierMockRecorder) InsertPublicShare(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPublicShare", reflect.TypeOf((*MockQuerier)(nil).InsertPublicShare), ctx, arg)
}

// InsertPublicSharePasswordProtected mocks base method.
func (m *MockQuerier) InsertPublicSharePasswordProtected(ctx context.Context, arg sqlc.InsertPublicSharePasswordProtectedParams) (sqlc.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPublicSharePasswordProtected", ctx, arg)
	ret0, _ := ret[0].(sqlc.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPublicSharePasswordProtected indicates an expected call of InsertPublicSharePasswordProtected.
func (mr *MockQuerierMockRecorder) InsertPublicSharePasswordProtected(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPublicSharePasswordProtected", reflect.TypeOf((*MockQuerier)(nil).InsertPublicSharePasswordProtected), ctx, arg)
}

// InsertShare mocks base method.
func (m *MockQuerier) InsertShare(ctx context.Context, arg sqlc.InsertShareParams) (sqlc.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertShare", ctx, arg)
	ret0, _ := ret[0].(sqlc.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertShare indicates an expected call of InsertShare.
func (mr *MockQuerierMockRecorder) InsertShare(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertShare", reflect.TypeOf((*MockQuerier)(nil).InsertShare), ctx, arg)
}

// InsertShareWithPassword mocks base method.
func (m *MockQuerier) InsertShareWithPassword(ctx context.Context, arg sqlc.InsertShareWithPasswordParams) (sqlc.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertShareWithPassword", ctx, arg)
	ret0, _ := ret[0].(sqlc.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertShareWithPassword indicates an expected call of InsertShareWithPassword.
func (mr *MockQuerierMockRecorder) InsertShareWithPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertShareWithPassword", reflect.TypeOf((*MockQuerier)(nil).InsertShareWithPassword), ctx, arg)
}

// ListAPIKeyScopes mocks base method.
func (m *MockQuerier) ListAPIKeyScopes(ctx context.Context, apiKeyID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIKeyScopes", ctx, apiKeyID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIKeyScopes indicates an expected call of ListAPIKeyScopes.
func (mr *MockQuerierMockRecorder) ListAPIKeyScopes(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeyScopes", reflect.TypeOf((*MockQuerier)(nil).ListAPIKeyScopes), ctx, apiKeyID)
}

// ListFileIDsWithoutPrivateToken mocks base method.
func (m *MockQuerier) ListFileIDsWithoutPrivateToken(ctx context.Context) ([]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFileIDsWithoutPrivateToken", ctx)
	ret0, _ := ret[0].([]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFileIDsWithoutPrivateToken indicates an expected call of ListFileIDsWithoutPrivateToken.
func (mr *MockQuerierMockRecorder) ListFileIDsWithoutPrivateToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFileIDsWithoutPrivateToken", reflect.TypeOf((*MockQuerier)(nil).ListFileIDsWithoutPrivateToken), ctx)
}

// ListFileUploadPartsByUploadID mocks base method.
func (m *MockQuerier) ListFileUploadPartsByUploadID(ctx context.Context, uploadID uuid.UUID) ([]sqlc.FileUploadPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFileUploadPartsByUploadID", ctx, uploadID)
	ret0, _ := ret[0].([]sqlc.FileUploadPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFileUploadPartsByUploadID indicates an expected call of ListFileUploadPartsByUploadID.
func (mr *MockQuerierMockRecorder) ListFileUploadPartsByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFileUploadPartsByUploadID", reflect.TypeOf((*MockQuerier)(nil).ListFileUploadPartsByUploadID), ctx, uploadID)
}

// ListPrivateAPIKeysByUserID mocks base method.
func (m *MockQuerier) ListPrivateAPIKeysByUserID(ctx context.Context, userID uuid.UUID) ([]sqlc.ListPrivateAPIKeysByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrivateAPIKeysByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.ListPrivateAPIKeysByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrivateAPIKeysByUserID indicates an expected call of ListPrivateAPIKeysByUserID.
func (mr *MockQuerierMockRecorder) ListPrivateAPIKeysByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrivateAPIKeysByUserID", reflect.TypeOf((*MockQuerier)(nil).ListPrivateAPIKeysByUserID), ctx, userID)
}

// ListWorkspaceAPIKeys mocks base method.
func (m *MockQuerier) ListWorkspaceAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]sqlc.ListWorkspaceAPIKeysRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspaceAPIKeys", ctx, workspaceID)
	ret0, _ := ret[0].([]sqlc.ListWorkspaceAPIKeysRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaceAPIKeys indicates an expected call of ListWorkspaceAPIKeys.
func (mr *MockQuerierMockRecorder) ListWorkspaceAPIKeys(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaceAPIKeys", reflect.TypeOf((*MockQuerier)(nil).ListWorkspaceAPIKeys), ctx, workspaceID)
}

// MarkShareSeen mocks base method.
func (m *MockQuerier) MarkShareSeen(ctx context.Context, arg sqlc.MarkShareSeenParams) (sqlc.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkShareSeen", ctx, arg)
	ret0, _ := ret[0].(sqlc.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkShareSeen indicates an expected call of MarkShareSeen.
func (mr *MockQuerierMockRecorder) MarkShareSeen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkShareSeen", reflect.TypeOf((*MockQuerier)(nil).MarkShareSeen), ctx, arg)
}

// MoveWorkspaceFile mocks base method.
func (m *MockQuerier) MoveWorkspaceFile(ctx context.Context, arg sqlc.MoveWorkspaceFileParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWorkspaceFile", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveWorkspaceFile indicates an expected call of MoveWorkspaceFile.
func (mr *MockQuerierMockRecorder) MoveWorkspaceFile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWorkspaceFile", reflect.TypeOf((*MockQuerier)(nil).MoveWorkspaceFile), ctx, arg)
}

// MoveWorkspaceFilesByPathPrefix mocks base method.
func (m *MockQuerier) MoveWorkspaceFilesByPathPrefix(ctx context.Context, arg sqlc.MoveWorkspaceFilesByPathPrefixParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWorkspaceFilesByPathPrefix", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveWorkspaceFilesByPathPrefix indicates an expected call of MoveWorkspaceFilesByPathPrefix.
func (mr *MockQuerierMockRecorder) MoveWorkspaceFilesByPathPrefix(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWorkspaceFilesByPathPrefix", reflect.TypeOf((*MockQuerier)(nil).MoveWorkspaceFilesByPathPrefix), ctx, arg)
}

// RenameWorkspace mocks base method.
func (m *MockQuerier) RenameWorkspace(ctx context.Context, arg sqlc.RenameWorkspaceParams) (sqlc.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameWorkspace", ctx, arg)
	ret0, _ := ret[0].(sqlc.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameWorkspace indicates an expected call of RenameWorkspace.
func (mr *MockQuerierMockRecorder) RenameWorkspace(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameWorkspace", reflect.TypeOf((*MockQuerier)(nil).RenameWorkspace), ctx, arg)
}

// RenameWorkspaceWithSlug mocks base method.
func (m *MockQuerier) RenameWorkspaceWithSlug(ctx context.Context, arg sqlc.RenameWorkspaceWithSlugParams) (sqlc.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameWorkspaceWithSlug", ctx, arg)
	ret0, _ := ret[0].(sqlc.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameWorkspaceWithSlug indicates an expected call of RenameWorkspaceWithSlug.
func (mr *MockQuerierMockRecorder) RenameWorkspaceWithSlug(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameWorkspaceWithSlug", reflect.TypeOf((*MockQuerier)(nil).RenameWorkspaceWithSlug), ctx, arg)
}

// RevokePrivateAPIKey mocks base method.
func (m *MockQuerier) RevokePrivateAPIKey(ctx context.Context, arg sqlc.RevokePrivateAPIKeyParams) (sqlc.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokePrivateAPIKey", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokePrivateAPIKey indicates an expected call of RevokePrivateAPIKey.
func (mr *MockQuerierMockRecorder) RevokePrivateAPIKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokePrivateAPIKey", reflect.TypeOf((*MockQuerier)(nil).RevokePrivateAPIKey), ctx, arg)
}

// RevokeWorkspaceAPIKey mocks base method.
func (m *MockQuerier) RevokeWorkspaceAPIKey(ctx context.Context, arg sqlc.RevokeWorkspaceAPIKeyParams) (sqlc.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeWorkspaceAPIKey", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeWorkspaceAPIKey indicates an expected call of RevokeWorkspaceAPIKey.
func (mr *MockQuerierMockRecorder) RevokeWorkspaceAPIKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeWorkspaceAPIKey", reflect.TypeOf((*MockQuerier)(nil).RevokeWorkspaceAPIKey), ctx, arg)
}

// SaveFileUploadPart mocks base method.
func (m *MockQuerier) SaveFileUploadPart(ctx context.Context, arg sqlc.SaveFileUploadPartParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFileUploadPart", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFileUploadPart indicates an expected call of SaveFileUploadPart.
func (mr *MockQuerierMockRecorder) SaveFileUploadPart(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileUploadPart", reflect.TypeOf((*MockQuerier)(nil).SaveFileUploadPart), ctx, arg)
}

// UpdateFileNameByID mocks base method.
func (m *MockQuerier) UpdateFileNameByID(ctx context.Context, arg sqlc.UpdateFileNameByIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileNameByID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFileNameByID indicates an expected call of UpdateFileNameByID.
func (mr *MockQuerierMockRecorder) UpdateFileNameByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileNameByID", reflect.TypeOf((*MockQuerier)(nil).UpdateFileNameByID), ctx, arg)
}

// UpdateFileNameByOwnerAndName mocks base method.
func (m *MockQuerier) UpdateFileNameByOwnerAndName(ctx context.Context, arg sqlc.UpdateFileNameByOwnerAndNameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileNameByOwnerAndName", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFileNameByOwnerAndName indicates an expected call of UpdateFileNameByOwnerAndName.
func (mr *MockQuerierMockRecorder) UpdateFileNameByOwnerAndName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileNameByOwnerAndName", reflect.TypeOf((*MockQuerier)(nil).UpdateFileNameByOwnerAndName), ctx, arg)
}

// UpdateFileUploadParts mocks base method.
func (m *MockQuerier) UpdateFileUploadParts(ctx context.Context, arg sqlc.UpdateFileUploadPartsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileUploadParts", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFileUploadParts indicates an expected call of UpdateFileUploadParts.
func (mr *MockQuerierMockRecorder) UpdateFileUploadParts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileUploadParts", reflect.TypeOf((*MockQuerier)(nil).UpdateFileUploadParts), ctx, arg)
}

// UpdateNoteForFile mocks base method.
func (m *MockQuerier) UpdateNoteForFile(ctx context.Context, arg sqlc.UpdateNoteForFileParams) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNoteForFile", ctx, arg)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNoteForFile indicates an expected call of UpdateNoteForFile.
func (mr *MockQuerierMockRecorder) UpdateNoteForFile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNoteForFile", reflect.TypeOf((*MockQuerier)(nil).UpdateNoteForFile), ctx, arg)
}

// UpdatePasswordCredentials mocks base method.
func (m *MockQuerier) UpdatePasswordCredentials(ctx context.Context, arg sqlc.UpdatePasswordCredentialsParams) (sqlc.PasswordCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordCredentials", ctx, arg)
	ret0, _ := ret[0].(sqlc.PasswordCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordCredentials indicates an expected call of UpdatePasswordCredentials.
func (mr *MockQuerierMockRecorder) UpdatePasswordCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordCredentials", reflect.TypeOf((*MockQuerier)(nil).UpdatePasswordCredentials), ctx, arg)
}

// UpdatePrivateDownloadToken mocks base method.
func (m *MockQuerier) UpdatePrivateDownloadToken(ctx context.Context, arg sqlc.UpdatePrivateDownloadTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrivateDownloadToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrivateDownloadToken indicates an expected call of UpdatePrivateDownloadToken.
func (mr *MockQuerierMockRecorder) UpdatePrivateDownloadToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrivateDownloadToken", reflect.TypeOf((*MockQuerier)(nil).UpdatePrivateDownloadToken), ctx, arg)
}

// UpdateResendAvailableAt mocks base method.
func (m *MockQuerier) UpdateResendAvailableAt(ctx context.Context, arg sqlc.UpdateResendAvailableAtParams) (sqlc.EmailVerificationChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResendAvailableAt", ctx, arg)
	ret0, _ := ret[0].(sqlc.EmailVerificationChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResendAvailableAt indicates an expected call of UpdateResendAvailableAt.
func (mr *MockQuerierMockRecorder) UpdateResendAvailableAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResendAvailableAt", reflect.TypeOf((*MockQuerier)(nil).UpdateResendAvailableAt), ctx, arg)
}

// UpdateUserBucketNameById mocks base method.
func (m *MockQuerier) UpdateUserBucketNameById(ctx context.Context, arg sqlc.UpdateUserBucketNameByIdParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserBucketNameById", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserBucketNameById indicates an expected call of UpdateUserBucketNameById.
func (mr *MockQuerierMockRecorder) UpdateUserBucketNameById(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserBucketNameById", reflect.TypeOf((*MockQuerier)(nil).UpdateUserBucketNameById), ctx, arg)
}

// UpdateUserPlan mocks base method.
func (m *MockQuerier) UpdateUserPlan(ctx context.Context, arg sqlc.UpdateUserPlanParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPlan", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPlan indicates an expected call of UpdateUserPlan.
func (mr *MockQuerierMockRecorder) UpdateUserPlan(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPlan", reflect.TypeOf((*MockQuerier)(nil).UpdateUserPlan), ctx, arg)
}

// UpdateWorkspaceFileName mocks base method.
func (m *MockQuerier) UpdateWorkspaceFileName(ctx context.Context, arg sqlc.UpdateWorkspaceFileNameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspaceFileName", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkspaceFileName indicates an expected call of UpdateWorkspaceFileName.
func (mr *MockQuerierMockRecorder) UpdateWorkspaceFileName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspaceFileName", reflect.TypeOf((*MockQuerier)(nil).UpdateWorkspaceFileName), ctx, arg)
}

// UpdateWorkspaceFolderLocation mocks base method.
func (m *MockQuerier) UpdateWorkspaceFolderLocation(ctx context.Context, arg sqlc.UpdateWorkspaceFolderLocationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspaceFolderLocation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkspaceFolderLocation indicates an expected call of UpdateWorkspaceFolderLocation.
func (mr *MockQuerierMockRecorder) UpdateWorkspaceFolderLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspaceFolderLocation", reflect.TypeOf((*MockQuerier)(nil).UpdateWorkspaceFolderLocation), ctx, arg)
}

// UpdateWorkspaceMemberRole mocks base method.
func (m *MockQuerier) UpdateWorkspaceMemberRole(ctx context.Context, arg sqlc.UpdateWorkspaceMemberRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspaceMemberRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkspaceMemberRole indicates an expected call of UpdateWorkspaceMemberRole.
func (mr *MockQuerierMockRecorder) UpdateWorkspaceMemberRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspaceMemberRole", reflect.TypeOf((*MockQuerier)(nil).UpdateWorkspaceMemberRole), ctx, arg)
}
