// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tscrond/fluxsend-backend/internal/cloud_storage/types (interfaces: ObjectStorage)
//
// Generated by this command:
//
//	mockgen -destination=./mock_object_storage.go -package=mocks github.com/tscrond/fluxsend-backend/internal/cloud_storage/types ObjectStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	types "github.com/tscrond/fluxsend-backend/internal/cloud_storage/types"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockObjectStorage) AbortMultipartUpload(ctx context.Context, bucket, key, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, bucket, key, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockObjectStorageMockRecorder) AbortMultipartUpload(ctx, bucket, key, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockObjectStorage)(nil).AbortMultipartUpload), ctx, bucket, key, uploadID)
}

// BucketExists mocks base method.
func (m *MockObjectStorage) BucketExists(ctx context.Context, fullBucketName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", ctx, fullBucketName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockObjectStorageMockRecorder) BucketExists(ctx, fullBucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockObjectStorage)(nil).BucketExists), ctx, fullBucketName)
}

// Close mocks base method.
func (m *MockObjectStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockObjectStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObjectStorage)(nil).Close))
}

// CompleteMultipartUpload mocks base method.
func (m *MockObjectStorage) CompleteMultipartUpload(ctx context.Context, bucket, key, uploadID string, parts []types.CompletedPart) (*types.CompleteMultipartUploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, bucket, key, uploadID, parts)
	ret0, _ := ret[0].(*types.CompleteMultipartUploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockObjectStorageMockRecorder) CompleteMultipartUpload(ctx, bucket, key, uploadID, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockObjectStorage)(nil).CompleteMultipartUpload), ctx, bucket, key, uploadID, parts)
}

// CreateBucketIfNotExists mocks base method.
func (m *MockObjectStorage) CreateBucketIfNotExists(ctx context.Context, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucketIfNotExists", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucketIfNotExists indicates an expected call of CreateBucketIfNotExists.
func (mr *MockObjectStorageMockRecorder) CreateBucketIfNotExists(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucketIfNotExists", reflect.TypeOf((*MockObjectStorage)(nil).CreateBucketIfNotExists), ctx, userId)
}

// CreateMultipartUpload mocks base method.
func (m *MockObjectStorage) CreateMultipartUpload(ctx context.Context, bucket, uploadPath, contentType string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, bucket, uploadPath, contentType)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockObjectStorageMockRecorder) CreateMultipartUpload(ctx, bucket, uploadPath, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockObjectStorage)(nil).CreateMultipartUpload), ctx, bucket, uploadPath, contentType)
}

// DeleteBucket mocks base method.
func (m *MockObjectStorage) DeleteBucket(ctx context.Context, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBucket", ctx, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBucket indicates an expected call of DeleteBucket.
func (mr *MockObjectStorageMockRecorder) DeleteBucket(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBucket", reflect.TypeOf((*MockObjectStorage)(nil).DeleteBucket), ctx, bucket)
}

// DeleteObjectFromBucket mocks base method.
func (m *MockObjectStorage) DeleteObjectFromBucket(ctx context.Context, object, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectFromBucket", ctx, object, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectFromBucket indicates an expected call of DeleteObjectFromBucket.
func (mr *MockObjectStorageMockRecorder) DeleteObjectFromBucket(ctx, object, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectFromBucket", reflect.TypeOf((*MockObjectStorage)(nil).DeleteObjectFromBucket), ctx, object, bucket)
}

// DeleteObjectsFromBucket mocks base method.
func (m *MockObjectStorage) DeleteObjectsFromBucket(ctx context.Context, objects []string, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsFromBucket", ctx, objects, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectsFromBucket indicates an expected call of DeleteObjectsFromBucket.
func (mr *MockObjectStorageMockRecorder) DeleteObjectsFromBucket(ctx, objects, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsFromBucket", reflect.TypeOf((*MockObjectStorage)(nil).DeleteObjectsFromBucket), ctx, objects, bucket)
}

// GenerateSignedURL mocks base method.
func (m *MockObjectStorage) GenerateSignedURL(ctx context.Context, bucket, object string, expiresAt time.Time, contentDisposition string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSignedURL", ctx, bucket, object, expiresAt, contentDisposition)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSignedURL indicates an expected call of GenerateSignedURL.
func (mr *MockObjectStorageMockRecorder) GenerateSignedURL(ctx, bucket, object, expiresAt, contentDisposition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSignedURL", reflect.TypeOf((*MockObjectStorage)(nil).GenerateSignedURL), ctx, bucket, object, expiresAt, contentDisposition)
}

// GetBucketBaseName mocks base method.
func (m *MockObjectStorage) GetBucketBaseName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketBaseName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBucketBaseName indicates an expected call of GetBucketBaseName.
func (mr *MockObjectStorageMockRecorder) GetBucketBaseName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketBaseName", reflect.TypeOf((*MockObjectStorage)(nil).GetBucketBaseName))
}

// GetUserBucketData mocks base method.
func (m *MockObjectStorage) GetUserBucketData(ctx context.Context, id string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBucketData", ctx, id)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBucketData indicates an expected call of GetUserBucketData.
func (mr *MockObjectStorageMockRecorder) GetUserBucketData(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBucketData", reflect.TypeOf((*MockObjectStorage)(nil).GetUserBucketData), ctx, id)
}

// MoveObjectInBucket mocks base method.
func (m *MockObjectStorage) MoveObjectInBucket(ctx context.Context, source, destination, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveObjectInBucket", ctx, source, destination, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveObjectInBucket indicates an expected call of MoveObjectInBucket.
func (mr *MockObjectStorageMockRecorder) MoveObjectInBucket(ctx, source, destination, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObjectInBucket", reflect.TypeOf((*MockObjectStorage)(nil).MoveObjectInBucket), ctx, source, destination, bucket)
}

// PutObject mocks base method.
func (m *MockObjectStorage) PutObject(ctx context.Context, bucket, key string, r io.Reader, size int64, contentType string) (*types.PutObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucket, key, r, size, contentType)
	ret0, _ := ret[0].(*types.PutObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectStorageMockRecorder) PutObject(ctx, bucket, key, r, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectStorage)(nil).PutObject), ctx, bucket, key, r, size, contentType)
}

// UploadPart mocks base method.
func (m *MockObjectStorage) UploadPart(ctx context.Context, bucket, key, uploadID string, partNumber int32, body io.Reader, size int64) (*types.UploadPartResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPart", ctx, bucket, key, uploadID, partNumber, body, size)
	ret0, _ := ret[0].(*types.UploadPartResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockObjectStorageMockRecorder) UploadPart(ctx, bucket, key, uploadID, partNumber, body, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPart", reflect.TypeOf((*MockObjectStorage)(nil).UploadPart), ctx, bucket, key, uploadID, partNumber, body, size)
}
