services:
  frontend:
    image: fluxsend-frontend:dev
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8000:8000/tcp
    environment:
      - BACKEND_ENDPOINT=http://localhost:3000
      - NGINX_BACKEND_HOST=backend
      - NGINX_BACKEND_PORT=3000
      - NGINX_BACKEND_API_PORT=8091

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    depends_on:
      - postgres
    image: fluxsend-backend:dev
    container_name: backend
    restart: always
    ports:
      - 3000:3000/tcp
      - 8091:8091/tcp
    command: ["./fluxsend", "--config", "/config/config.yaml"]
    volumes:
      - /home/tskr/wazne/bucket-auth.json:/config/bucket-auth.json:ro
      - /home/tskr/wazne/fluxsend_private_key.pem:/config/fluxsend_private_key.pem:ro
    mounts:
      - type: bind
        source: ./config.example.full.yaml
        target: /config/config.yaml

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    volumes:
      - minio_data:/data
  
  docs:
    image: fluxsend-docs:dev
    container_name: docs
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - 8080:80/tcp

# networks:
#   proxy:
#     external: true
volumes:
  minio_data: