services:
  frontend:
    image: fluxsend-frontend:dev
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8000:8000/tcp
    environment:
      - BACKEND_ENDPOINT=http://localhost:3000
      - NGINX_BACKEND_HOST=backend
      - NGINX_BACKEND_PORT=3000
      - NGINX_BACKEND_API_PORT=8091

  dev-postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    depends_on:
      - dev-postgres
    image: fluxsend-backend:dev
    container_name: backend
    restart: always
    ports:
      - 3000:3000/tcp
      - 8091:8091/tcp
    environment:
      - FRONTEND_ENDPOINT=http://localhost:8000
      - BACKEND_ENDPOINT=http://localhost:3000
      - STORAGE_PROVIDER=${STORAGE_PROVIDER:-gcs}
      # GCS config
      - GOOGLE_APPLICATION_CREDENTIALS=/config/bucket-auth.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      # Google OAuth config
      - GOOGLE_COOKIE_SECRET=${GOOGLE_COOKIE_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # Github OAuth config
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      # S3 config
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - ENABLE_CLOUDFRONT_DOWNLOADS=${ENABLE_CLOUDFRONT_DOWNLOADS:-false}
      - CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN:-}
      - CLOUDFRONT_KEY_PAIR_ID=${CLOUDFRONT_KEY_PAIR_ID:-}
      - CLOUDFRONT_PRIVATE_KEY_PATH=${CLOUDFRONT_PRIVATE_KEY_PATH:-}
      # Mail config
      - MAIL_FROM=${MAIL_FROM:-noreply@fluxsend.com}
      # DB config
      - DB_HOST=dev-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_ENV=production

    volumes:
      - ./config/bucket-auth.json:/config/bucket-auth.json:ro
      - /home/tskr/wazne/fluxsend_private_key.pem:/config/fluxsend_private_key.pem:ro

    
# networks:
#   proxy:
#     external: true
