services:
  frontend:
    image: fluxsend-frontend:local
    container_name: frontend
    ports:
      - 8000:8000/tcp
    environment:
      - BACKEND_ENDPOINT=http://localhost:3000
      - NGINX_BACKEND_HOST=backend
      - NGINX_BACKEND_PORT=3000

  dev-postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    depends_on:
      - dev-postgres
    image: fluxsend-backend:local
    container_name: backend
    restart: always
    ports:
      - 3000:3000/tcp
    environment:
      - FRONTEND_ENDPOINT=http://localhost:8000
      - BACKEND_ENDPOINT=http://localhost:3000
      - STORAGE_PROVIDER=${STORAGE_PROVIDER:-gcs}
      # GCS config
      - GOOGLE_APPLICATION_CREDENTIALS=/config/bucket-auth.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOOGLE_COOKIE_SECRET=${GOOGLE_COOKIE_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # S3 config
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      # DB config
      - DB_HOST=dev-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - ./config/bucket-auth.json:/config/bucket-auth.json:ro

    
# networks:
#   proxy:
#     external: true
