// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tscrond/fluxsend-backend/internal/service (interfaces: FileService,ShareService,WorkspaceService,UserService,WorkspaceFileService,APIKeyService)
//
// Generated by this command:
//
//	mockgen -destination=./mock_services.go -package=apimocks github.com/tscrond/fluxsend-backend/internal/service FileService,ShareService,WorkspaceService,UserService,WorkspaceFileService,APIKeyService
//

// Package apimocks is a generated GoMock package.
package apimocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	apikeydata "github.com/tscrond/fluxsend-backend/internal/apikeydata"
	filedata "github.com/tscrond/fluxsend-backend/internal/filedata"
	mappings "github.com/tscrond/fluxsend-backend/internal/mappings"
	service "github.com/tscrond/fluxsend-backend/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
	isgomock struct{}
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// CreateUploadWithId mocks base method.
func (m *MockFileService) CreateUploadWithId(ctx context.Context, fd *filedata.CreateUploadIdParams) (*filedata.CreateUploadIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUploadWithId", ctx, fd)
	ret0, _ := ret[0].(*filedata.CreateUploadIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUploadWithId indicates an expected call of CreateUploadWithId.
func (mr *MockFileServiceMockRecorder) CreateUploadWithId(ctx, fd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUploadWithId", reflect.TypeOf((*MockFileService)(nil).CreateUploadWithId), ctx, fd)
}

// DeleteFile mocks base method.
func (m *MockFileService) DeleteFile(ctx context.Context, userID uuid.UUID, userInternalID, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, userID, userInternalID, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceMockRecorder) DeleteFile(ctx, userID, userInternalID, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileService)(nil).DeleteFile), ctx, userID, userInternalID, fileName)
}

// DeleteFiles mocks base method.
func (m *MockFileService) DeleteFiles(ctx context.Context, userID uuid.UUID, userInternalID string, fileNames []string) ([]string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFiles", ctx, userID, userInternalID, fileNames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteFiles indicates an expected call of DeleteFiles.
func (mr *MockFileServiceMockRecorder) DeleteFiles(ctx, userID, userInternalID, fileNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFiles", reflect.TypeOf((*MockFileService)(nil).DeleteFiles), ctx, userID, userInternalID, fileNames)
}

// DeleteFolder mocks base method.
func (m *MockFileService) DeleteFolder(ctx context.Context, userID uuid.UUID, userInternalID, folderPath string, recursive bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", ctx, userID, userInternalID, folderPath, recursive)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockFileServiceMockRecorder) DeleteFolder(ctx, userID, userInternalID, folderPath, recursive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockFileService)(nil).DeleteFolder), ctx, userID, userInternalID, folderPath, recursive)
}

// GetFilesTree mocks base method.
func (m *MockFileService) GetFilesTree(ctx context.Context, userID uuid.UUID, path string) (*service.FilesTree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesTree", ctx, userID, path)
	ret0, _ := ret[0].(*service.FilesTree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesTree indicates an expected call of GetFilesTree.
func (mr *MockFileServiceMockRecorder) GetFilesTree(ctx, userID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesTree", reflect.TypeOf((*MockFileService)(nil).GetFilesTree), ctx, userID, path)
}

// GetFolders mocks base method.
func (m *MockFileService) GetFolders(ctx context.Context, userID uuid.UUID, path string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolders", ctx, userID, path)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolders indicates an expected call of GetFolders.
func (mr *MockFileServiceMockRecorder) GetFolders(ctx, userID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolders", reflect.TypeOf((*MockFileService)(nil).GetFolders), ctx, userID, path)
}

// GetNote mocks base method.
func (m *MockFileService) GetNote(ctx context.Context, userID uuid.UUID, checksum string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, userID, checksum)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockFileServiceMockRecorder) GetNote(ctx, userID, checksum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockFileService)(nil).GetNote), ctx, userID, checksum)
}

// MoveFile mocks base method.
func (m *MockFileService) MoveFile(ctx context.Context, userID uuid.UUID, source, destination string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveFile", ctx, userID, source, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveFile indicates an expected call of MoveFile.
func (mr *MockFileServiceMockRecorder) MoveFile(ctx, userID, source, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveFile", reflect.TypeOf((*MockFileService)(nil).MoveFile), ctx, userID, source, destination)
}

// MoveFolder mocks base method.
func (m *MockFileService) MoveFolder(ctx context.Context, userID uuid.UUID, source, destination string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveFolder", ctx, userID, source, destination)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveFolder indicates an expected call of MoveFolder.
func (mr *MockFileServiceMockRecorder) MoveFolder(ctx, userID, source, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveFolder", reflect.TypeOf((*MockFileService)(nil).MoveFolder), ctx, userID, source, destination)
}

// Upload mocks base method.
func (m *MockFileService) Upload(ctx context.Context, fd *filedata.FileData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, fd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockFileServiceMockRecorder) Upload(ctx, fd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileService)(nil).Upload), ctx, fd)
}

// UpsertNote mocks base method.
func (m *MockFileService) UpsertNote(ctx context.Context, userID uuid.UUID, checksum, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNote", ctx, userID, checksum, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertNote indicates an expected call of UpsertNote.
func (mr *MockFileServiceMockRecorder) UpsertNote(ctx, userID, checksum, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNote", reflect.TypeOf((*MockFileService)(nil).UpsertNote), ctx, userID, checksum, content)
}

// MockShareService is a mock of ShareService interface.
type MockShareService struct {
	ctrl     *gomock.Controller
	recorder *MockShareServiceMockRecorder
	isgomock struct{}
}

// MockShareServiceMockRecorder is the mock recorder for MockShareService.
type MockShareServiceMockRecorder struct {
	mock *MockShareService
}

// NewMockShareService creates a new mock instance.
func NewMockShareService(ctrl *gomock.Controller) *MockShareService {
	mock := &MockShareService{ctrl: ctrl}
	mock.recorder = &MockShareServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareService) EXPECT() *MockShareServiceMockRecorder {
	return m.recorder
}

// CountUnseen mocks base method.
func (m *MockShareService) CountUnseen(ctx context.Context, email string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnseen", ctx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnseen indicates an expected call of CountUnseen.
func (mr *MockShareServiceMockRecorder) CountUnseen(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnseen", reflect.TypeOf((*MockShareService)(nil).CountUnseen), ctx, email)
}

// GetPublicShareInfo mocks base method.
func (m *MockShareService) GetPublicShareInfo(ctx context.Context, token string) (*service.ShareInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicShareInfo", ctx, token)
	ret0, _ := ret[0].(*service.ShareInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicShareInfo indicates an expected call of GetPublicShareInfo.
func (mr *MockShareServiceMockRecorder) GetPublicShareInfo(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicShareInfo", reflect.TypeOf((*MockShareService)(nil).GetPublicShareInfo), ctx, token)
}

// GetSharedByUser mocks base method.
func (m *MockShareService) GetSharedByUser(ctx context.Context, email string) ([]service.SharedFileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedByUser", ctx, email)
	ret0, _ := ret[0].([]service.SharedFileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedByUser indicates an expected call of GetSharedByUser.
func (mr *MockShareServiceMockRecorder) GetSharedByUser(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedByUser", reflect.TypeOf((*MockShareService)(nil).GetSharedByUser), ctx, email)
}

// GetSharedForUser mocks base method.
func (m *MockShareService) GetSharedForUser(ctx context.Context, email string) ([]service.SharedFileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedForUser", ctx, email)
	ret0, _ := ret[0].([]service.SharedFileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedForUser indicates an expected call of GetSharedForUser.
func (mr *MockShareServiceMockRecorder) GetSharedForUser(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedForUser", reflect.TypeOf((*MockShareService)(nil).GetSharedForUser), ctx, email)
}

// MarkSeen mocks base method.
func (m *MockShareService) MarkSeen(ctx context.Context, email, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSeen", ctx, email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSeen indicates an expected call of MarkSeen.
func (mr *MockShareServiceMockRecorder) MarkSeen(ctx, email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSeen", reflect.TypeOf((*MockShareService)(nil).MarkSeen), ctx, email, token)
}

// QuickShare mocks base method.
func (m *MockShareService) QuickShare(ctx context.Context, sharedByEmail string, ownerID uuid.UUID, object, duration, password string) (*service.QuickShareResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuickShare", ctx, sharedByEmail, ownerID, object, duration, password)
	ret0, _ := ret[0].(*service.QuickShareResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuickShare indicates an expected call of QuickShare.
func (mr *MockShareServiceMockRecorder) QuickShare(ctx, sharedByEmail, ownerID, object, duration, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuickShare", reflect.TypeOf((*MockShareService)(nil).QuickShare), ctx, sharedByEmail, ownerID, object, duration, password)
}

// ResolvePersonalDownload mocks base method.
func (m *MockShareService) ResolvePersonalDownload(ctx context.Context, ownerID uuid.UUID, token, mode string) (*service.DownloadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePersonalDownload", ctx, ownerID, token, mode)
	ret0, _ := ret[0].(*service.DownloadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePersonalDownload indicates an expected call of ResolvePersonalDownload.
func (mr *MockShareServiceMockRecorder) ResolvePersonalDownload(ctx, ownerID, token, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePersonalDownload", reflect.TypeOf((*MockShareService)(nil).ResolvePersonalDownload), ctx, ownerID, token, mode)
}

// ResolvePublicDownload mocks base method.
func (m *MockShareService) ResolvePublicDownload(ctx context.Context, token, mode, password string) (*service.DownloadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePublicDownload", ctx, token, mode, password)
	ret0, _ := ret[0].(*service.DownloadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePublicDownload indicates an expected call of ResolvePublicDownload.
func (mr *MockShareServiceMockRecorder) ResolvePublicDownload(ctx, token, mode, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePublicDownload", reflect.TypeOf((*MockShareService)(nil).ResolvePublicDownload), ctx, token, mode, password)
}

// RevokeShare mocks base method.
func (m *MockShareService) RevokeShare(ctx context.Context, token, ownerEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeShare", ctx, token, ownerEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeShare indicates an expected call of RevokeShare.
func (mr *MockShareServiceMockRecorder) RevokeShare(ctx, token, ownerEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeShare", reflect.TypeOf((*MockShareService)(nil).RevokeShare), ctx, token, ownerEmail)
}

// ShareWith mocks base method.
func (m *MockShareService) ShareWith(ctx context.Context, sharedByEmail string, ownerID uuid.UUID, forUser string, objects []string, duration, password string, sendEmail bool) ([]service.ShareResult, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareWith", ctx, sharedByEmail, ownerID, forUser, objects, duration, password, sendEmail)
	ret0, _ := ret[0].([]service.ShareResult)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ShareWith indicates an expected call of ShareWith.
func (mr *MockShareServiceMockRecorder) ShareWith(ctx, sharedByEmail, ownerID, forUser, objects, duration, password, sendEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareWith", reflect.TypeOf((*MockShareService)(nil).ShareWith), ctx, sharedByEmail, ownerID, forUser, objects, duration, password, sendEmail)
}

// MockWorkspaceService is a mock of WorkspaceService interface.
type MockWorkspaceService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceServiceMockRecorder
	isgomock struct{}
}

// MockWorkspaceServiceMockRecorder is the mock recorder for MockWorkspaceService.
type MockWorkspaceServiceMockRecorder struct {
	mock *MockWorkspaceService
}

// NewMockWorkspaceService creates a new mock instance.
func NewMockWorkspaceService(ctrl *gomock.Controller) *MockWorkspaceService {
	mock := &MockWorkspaceService{ctrl: ctrl}
	mock.recorder = &MockWorkspaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceService) EXPECT() *MockWorkspaceServiceMockRecorder {
	return m.recorder
}

// AcceptWorkspaceInvite mocks base method.
func (m *MockWorkspaceService) AcceptWorkspaceInvite(ctx context.Context, token string, userID uuid.UUID, userEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptWorkspaceInvite", ctx, token, userID, userEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptWorkspaceInvite indicates an expected call of AcceptWorkspaceInvite.
func (mr *MockWorkspaceServiceMockRecorder) AcceptWorkspaceInvite(ctx, token, userID, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptWorkspaceInvite", reflect.TypeOf((*MockWorkspaceService)(nil).AcceptWorkspaceInvite), ctx, token, userID, userEmail)
}

// CreateWorkspace mocks base method.
func (m *MockWorkspaceService) CreateWorkspace(ctx context.Context, userID uuid.UUID, name, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", ctx, userID, name, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) CreateWorkspace(ctx, userID, name, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).CreateWorkspace), ctx, userID, name, slug)
}

// CreateWorkspaceInvite mocks base method.
func (m *MockWorkspaceService) CreateWorkspaceInvite(ctx context.Context, workspaceID uuid.UUID, email, token, role string) (*service.WorkspaceInviteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceInvite", ctx, workspaceID, email, token, role)
	ret0, _ := ret[0].(*service.WorkspaceInviteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceInvite indicates an expected call of CreateWorkspaceInvite.
func (mr *MockWorkspaceServiceMockRecorder) CreateWorkspaceInvite(ctx, workspaceID, email, token, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceInvite", reflect.TypeOf((*MockWorkspaceService)(nil).CreateWorkspaceInvite), ctx, workspaceID, email, token, role)
}

// DeleteWorkspace mocks base method.
func (m *MockWorkspaceService) DeleteWorkspace(ctx context.Context, workspaceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspace indicates an expected call of DeleteWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) DeleteWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).DeleteWorkspace), ctx, workspaceID)
}

// DeleteWorkspaceInvite mocks base method.
func (m *MockWorkspaceService) DeleteWorkspaceInvite(ctx context.Context, inviteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceInvite", ctx, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceInvite indicates an expected call of DeleteWorkspaceInvite.
func (mr *MockWorkspaceServiceMockRecorder) DeleteWorkspaceInvite(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceInvite", reflect.TypeOf((*MockWorkspaceService)(nil).DeleteWorkspaceInvite), ctx, inviteID)
}

// GetUserInvites mocks base method.
func (m *MockWorkspaceService) GetUserInvites(ctx context.Context, email string) ([]service.UserInviteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInvites", ctx, email)
	ret0, _ := ret[0].([]service.UserInviteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInvites indicates an expected call of GetUserInvites.
func (mr *MockWorkspaceServiceMockRecorder) GetUserInvites(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInvites", reflect.TypeOf((*MockWorkspaceService)(nil).GetUserInvites), ctx, email)
}

// GetUserWorkspaceRole mocks base method.
func (m *MockWorkspaceService) GetUserWorkspaceRole(ctx context.Context, userId, workspaceId uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWorkspaceRole", ctx, userId, workspaceId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWorkspaceRole indicates an expected call of GetUserWorkspaceRole.
func (mr *MockWorkspaceServiceMockRecorder) GetUserWorkspaceRole(ctx, userId, workspaceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWorkspaceRole", reflect.TypeOf((*MockWorkspaceService)(nil).GetUserWorkspaceRole), ctx, userId, workspaceId)
}

// GetUserWorkspaces mocks base method.
func (m *MockWorkspaceService) GetUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]service.WorkspaceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWorkspaces", ctx, userID)
	ret0, _ := ret[0].([]service.WorkspaceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWorkspaces indicates an expected call of GetUserWorkspaces.
func (mr *MockWorkspaceServiceMockRecorder) GetUserWorkspaces(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWorkspaces", reflect.TypeOf((*MockWorkspaceService)(nil).GetUserWorkspaces), ctx, userID)
}

// GetWorkspaceInvites mocks base method.
func (m *MockWorkspaceService) GetWorkspaceInvites(ctx context.Context, workspaceID uuid.UUID) ([]service.WorkspaceInviteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceInvites", ctx, workspaceID)
	ret0, _ := ret[0].([]service.WorkspaceInviteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceInvites indicates an expected call of GetWorkspaceInvites.
func (mr *MockWorkspaceServiceMockRecorder) GetWorkspaceInvites(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceInvites", reflect.TypeOf((*MockWorkspaceService)(nil).GetWorkspaceInvites), ctx, workspaceID)
}

// GetWorkspaceMembers mocks base method.
func (m *MockWorkspaceService) GetWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]service.WorkspaceMemberResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMembers", ctx, workspaceID)
	ret0, _ := ret[0].([]service.WorkspaceMemberResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMembers indicates an expected call of GetWorkspaceMembers.
func (mr *MockWorkspaceServiceMockRecorder) GetWorkspaceMembers(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMembers", reflect.TypeOf((*MockWorkspaceService)(nil).GetWorkspaceMembers), ctx, workspaceID)
}

// RejectWorkspaceInvite mocks base method.
func (m *MockWorkspaceService) RejectWorkspaceInvite(ctx context.Context, token, userEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectWorkspaceInvite", ctx, token, userEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectWorkspaceInvite indicates an expected call of RejectWorkspaceInvite.
func (mr *MockWorkspaceServiceMockRecorder) RejectWorkspaceInvite(ctx, token, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectWorkspaceInvite", reflect.TypeOf((*MockWorkspaceService)(nil).RejectWorkspaceInvite), ctx, token, userEmail)
}

// RemoveWorkspaceMember mocks base method.
func (m *MockWorkspaceService) RemoveWorkspaceMember(ctx context.Context, workspaceID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkspaceMember", ctx, workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWorkspaceMember indicates an expected call of RemoveWorkspaceMember.
func (mr *MockWorkspaceServiceMockRecorder) RemoveWorkspaceMember(ctx, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkspaceMember", reflect.TypeOf((*MockWorkspaceService)(nil).RemoveWorkspaceMember), ctx, workspaceID, userID)
}

// RenameWorkspace mocks base method.
func (m *MockWorkspaceService) RenameWorkspace(ctx context.Context, workspaceID uuid.UUID, newName, newSlug string) (*service.WorkspaceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameWorkspace", ctx, workspaceID, newName, newSlug)
	ret0, _ := ret[0].(*service.WorkspaceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameWorkspace indicates an expected call of RenameWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) RenameWorkspace(ctx, workspaceID, newName, newSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).RenameWorkspace), ctx, workspaceID, newName, newSlug)
}

// UpdateMemberRole mocks base method.
func (m *MockWorkspaceService) UpdateMemberRole(ctx context.Context, workspaceID, targetUserID uuid.UUID, newRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", ctx, workspaceID, targetUserID, newRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockWorkspaceServiceMockRecorder) UpdateMemberRole(ctx, workspaceID, targetUserID, newRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockWorkspaceService)(nil).UpdateMemberRole), ctx, workspaceID, targetUserID, newRole)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// DeleteAccount mocks base method.
func (m *MockUserService) DeleteAccount(ctx context.Context, userID uuid.UUID, userInternalID, userName string, deleteStorageData bool) (*service.DeleteAccountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID, userInternalID, userName, deleteStorageData)
	ret0, _ := ret[0].(*service.DeleteAccountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockUserServiceMockRecorder) DeleteAccount(ctx, userID, userInternalID, userName, deleteStorageData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockUserService)(nil).DeleteAccount), ctx, userID, userInternalID, userName, deleteStorageData)
}

// GetBucketData mocks base method.
func (m *MockUserService) GetBucketData(ctx context.Context, userID uuid.UUID, userInternalID string) (*mappings.BucketData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketData", ctx, userID, userInternalID)
	ret0, _ := ret[0].(*mappings.BucketData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketData indicates an expected call of GetBucketData.
func (mr *MockUserServiceMockRecorder) GetBucketData(ctx, userID, userInternalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketData", reflect.TypeOf((*MockUserService)(nil).GetBucketData), ctx, userID, userInternalID)
}

// GetPrivateDownloadToken mocks base method.
func (m *MockUserService) GetPrivateDownloadToken(ctx context.Context, userID uuid.UUID, fileName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateDownloadToken", ctx, userID, fileName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateDownloadToken indicates an expected call of GetPrivateDownloadToken.
func (mr *MockUserServiceMockRecorder) GetPrivateDownloadToken(ctx, userID, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateDownloadToken", reflect.TypeOf((*MockUserService)(nil).GetPrivateDownloadToken), ctx, userID, fileName)
}

// MockWorkspaceFileService is a mock of WorkspaceFileService interface.
type MockWorkspaceFileService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceFileServiceMockRecorder
	isgomock struct{}
}

// MockWorkspaceFileServiceMockRecorder is the mock recorder for MockWorkspaceFileService.
type MockWorkspaceFileServiceMockRecorder struct {
	mock *MockWorkspaceFileService
}

// NewMockWorkspaceFileService creates a new mock instance.
func NewMockWorkspaceFileService(ctrl *gomock.Controller) *MockWorkspaceFileService {
	mock := &MockWorkspaceFileService{ctrl: ctrl}
	mock.recorder = &MockWorkspaceFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceFileService) EXPECT() *MockWorkspaceFileServiceMockRecorder {
	return m.recorder
}

// CreateWorkspaceFiles mocks base method.
func (m *MockWorkspaceFileService) CreateWorkspaceFiles(ctx context.Context, workspaceId uuid.UUID, fd []filedata.WorkspaceFileData) ([]service.WorkspaceFileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceFiles", ctx, workspaceId, fd)
	ret0, _ := ret[0].([]service.WorkspaceFileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceFiles indicates an expected call of CreateWorkspaceFiles.
func (mr *MockWorkspaceFileServiceMockRecorder) CreateWorkspaceFiles(ctx, workspaceId, fd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceFiles", reflect.TypeOf((*MockWorkspaceFileService)(nil).CreateWorkspaceFiles), ctx, workspaceId, fd)
}

// CreateWorkspaceFolder mocks base method.
func (m *MockWorkspaceFileService) CreateWorkspaceFolder(ctx context.Context, workspaceId, creatorID uuid.UUID, folderName, parentPath string) (*service.WorkspaceFolderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceFolder", ctx, workspaceId, creatorID, folderName, parentPath)
	ret0, _ := ret[0].(*service.WorkspaceFolderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceFolder indicates an expected call of CreateWorkspaceFolder.
func (mr *MockWorkspaceFileServiceMockRecorder) CreateWorkspaceFolder(ctx, workspaceId, creatorID, folderName, parentPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceFolder", reflect.TypeOf((*MockWorkspaceFileService)(nil).CreateWorkspaceFolder), ctx, workspaceId, creatorID, folderName, parentPath)
}

// GetWorkspaceFileDownloadInfo mocks base method.
func (m *MockWorkspaceFileService) GetWorkspaceFileDownloadInfo(ctx context.Context, workspaceId, fileId uuid.UUID) (*service.WorkspaceFileDownloadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFileDownloadInfo", ctx, workspaceId, fileId)
	ret0, _ := ret[0].(*service.WorkspaceFileDownloadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFileDownloadInfo indicates an expected call of GetWorkspaceFileDownloadInfo.
func (mr *MockWorkspaceFileServiceMockRecorder) GetWorkspaceFileDownloadInfo(ctx, workspaceId, fileId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFileDownloadInfo", reflect.TypeOf((*MockWorkspaceFileService)(nil).GetWorkspaceFileDownloadInfo), ctx, workspaceId, fileId)
}

// GetWorkspaceFiles mocks base method.
func (m *MockWorkspaceFileService) GetWorkspaceFiles(ctx context.Context, workspaceId uuid.UUID) ([]service.WorkspaceFileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFiles", ctx, workspaceId)
	ret0, _ := ret[0].([]service.WorkspaceFileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFiles indicates an expected call of GetWorkspaceFiles.
func (mr *MockWorkspaceFileServiceMockRecorder) GetWorkspaceFiles(ctx, workspaceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFiles", reflect.TypeOf((*MockWorkspaceFileService)(nil).GetWorkspaceFiles), ctx, workspaceId)
}

// GetWorkspaceFilesTree mocks base method.
func (m *MockWorkspaceFileService) GetWorkspaceFilesTree(ctx context.Context, workspaceId uuid.UUID, path string) (service.WorkspaceFilesTree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceFilesTree", ctx, workspaceId, path)
	ret0, _ := ret[0].(service.WorkspaceFilesTree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceFilesTree indicates an expected call of GetWorkspaceFilesTree.
func (mr *MockWorkspaceFileServiceMockRecorder) GetWorkspaceFilesTree(ctx, workspaceId, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceFilesTree", reflect.TypeOf((*MockWorkspaceFileService)(nil).GetWorkspaceFilesTree), ctx, workspaceId, path)
}

// MoveWorkspaceFile mocks base method.
func (m *MockWorkspaceFileService) MoveWorkspaceFile(ctx context.Context, workspaceId, fileId uuid.UUID, destination string, callerID uuid.UUID, callerRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWorkspaceFile", ctx, workspaceId, fileId, destination, callerID, callerRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveWorkspaceFile indicates an expected call of MoveWorkspaceFile.
func (mr *MockWorkspaceFileServiceMockRecorder) MoveWorkspaceFile(ctx, workspaceId, fileId, destination, callerID, callerRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWorkspaceFile", reflect.TypeOf((*MockWorkspaceFileService)(nil).MoveWorkspaceFile), ctx, workspaceId, fileId, destination, callerID, callerRole)
}

// MoveWorkspaceFolder mocks base method.
func (m *MockWorkspaceFileService) MoveWorkspaceFolder(ctx context.Context, workspaceId uuid.UUID, sourcePath, destPath string, callerID uuid.UUID, callerRole string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveWorkspaceFolder", ctx, workspaceId, sourcePath, destPath, callerID, callerRole)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveWorkspaceFolder indicates an expected call of MoveWorkspaceFolder.
func (mr *MockWorkspaceFileServiceMockRecorder) MoveWorkspaceFolder(ctx, workspaceId, sourcePath, destPath, callerID, callerRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveWorkspaceFolder", reflect.TypeOf((*MockWorkspaceFileService)(nil).MoveWorkspaceFolder), ctx, workspaceId, sourcePath, destPath, callerID, callerRole)
}

// RemoveWorkspaceFile mocks base method.
func (m *MockWorkspaceFileService) RemoveWorkspaceFile(ctx context.Context, workspaceId, fileId, callerID uuid.UUID, callerRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkspaceFile", ctx, workspaceId, fileId, callerID, callerRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWorkspaceFile indicates an expected call of RemoveWorkspaceFile.
func (mr *MockWorkspaceFileServiceMockRecorder) RemoveWorkspaceFile(ctx, workspaceId, fileId, callerID, callerRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkspaceFile", reflect.TypeOf((*MockWorkspaceFileService)(nil).RemoveWorkspaceFile), ctx, workspaceId, fileId, callerID, callerRole)
}

// RemoveWorkspaceFolder mocks base method.
func (m *MockWorkspaceFileService) RemoveWorkspaceFolder(ctx context.Context, workspaceId uuid.UUID, folderPath string, callerID uuid.UUID, callerRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkspaceFolder", ctx, workspaceId, folderPath, callerID, callerRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWorkspaceFolder indicates an expected call of RemoveWorkspaceFolder.
func (mr *MockWorkspaceFileServiceMockRecorder) RemoveWorkspaceFolder(ctx, workspaceId, folderPath, callerID, callerRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkspaceFolder", reflect.TypeOf((*MockWorkspaceFileService)(nil).RemoveWorkspaceFolder), ctx, workspaceId, folderPath, callerID, callerRole)
}

// MockAPIKeyService is a mock of APIKeyService interface.
type MockAPIKeyService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyServiceMockRecorder
	isgomock struct{}
}

// MockAPIKeyServiceMockRecorder is the mock recorder for MockAPIKeyService.
type MockAPIKeyServiceMockRecorder struct {
	mock *MockAPIKeyService
}

// NewMockAPIKeyService creates a new mock instance.
func NewMockAPIKeyService(ctrl *gomock.Controller) *MockAPIKeyService {
	mock := &MockAPIKeyService{ctrl: ctrl}
	mock.recorder = &MockAPIKeyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyService) EXPECT() *MockAPIKeyServiceMockRecorder {
	return m.recorder
}

// CreatePrivateAPIKey mocks base method.
func (m *MockAPIKeyService) CreatePrivateAPIKey(ctx context.Context, akd *apikeydata.APIKeyData) (*service.CreateAPIKeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateAPIKey", ctx, akd)
	ret0, _ := ret[0].(*service.CreateAPIKeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateAPIKey indicates an expected call of CreatePrivateAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) CreatePrivateAPIKey(ctx, akd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).CreatePrivateAPIKey), ctx, akd)
}

// CreateWorkspaceAPIKey mocks base method.
func (m *MockAPIKeyService) CreateWorkspaceAPIKey(ctx context.Context, akd *apikeydata.APIKeyData) (*service.CreateAPIKeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceAPIKey", ctx, akd)
	ret0, _ := ret[0].(*service.CreateAPIKeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceAPIKey indicates an expected call of CreateWorkspaceAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) CreateWorkspaceAPIKey(ctx, akd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).CreateWorkspaceAPIKey), ctx, akd)
}

// DeletePrivateAPIKey mocks base method.
func (m *MockAPIKeyService) DeletePrivateAPIKey(ctx context.Context, userID, apiKeyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateAPIKey", ctx, userID, apiKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateAPIKey indicates an expected call of DeletePrivateAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) DeletePrivateAPIKey(ctx, userID, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).DeletePrivateAPIKey), ctx, userID, apiKeyID)
}

// DeleteWorkspaceAPIKey mocks base method.
func (m *MockAPIKeyService) DeleteWorkspaceAPIKey(ctx context.Context, workspaceID, apiKeyID, revokedBy uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceAPIKey", ctx, workspaceID, apiKeyID, revokedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspaceAPIKey indicates an expected call of DeleteWorkspaceAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) DeleteWorkspaceAPIKey(ctx, workspaceID, apiKeyID, revokedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).DeleteWorkspaceAPIKey), ctx, workspaceID, apiKeyID, revokedBy)
}

// ListPrivateAPIKeys mocks base method.
func (m *MockAPIKeyService) ListPrivateAPIKeys(ctx context.Context, userID uuid.UUID) ([]service.APIKeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrivateAPIKeys", ctx, userID)
	ret0, _ := ret[0].([]service.APIKeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrivateAPIKeys indicates an expected call of ListPrivateAPIKeys.
func (mr *MockAPIKeyServiceMockRecorder) ListPrivateAPIKeys(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrivateAPIKeys", reflect.TypeOf((*MockAPIKeyService)(nil).ListPrivateAPIKeys), ctx, userID)
}

// ListWorkspaceAPIKeys mocks base method.
func (m *MockAPIKeyService) ListWorkspaceAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]service.APIKeyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspaceAPIKeys", ctx, workspaceID)
	ret0, _ := ret[0].([]service.APIKeyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaceAPIKeys indicates an expected call of ListWorkspaceAPIKeys.
func (mr *MockAPIKeyServiceMockRecorder) ListWorkspaceAPIKeys(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaceAPIKeys", reflect.TypeOf((*MockAPIKeyService)(nil).ListWorkspaceAPIKeys), ctx, workspaceID)
}
