server {
    listen 80;
    server_name _;

    # Serve the preview UI
    root /usr/share/nginx/html;
    
    # Specify the default file to serve
    index index.html;

    location = /admin {
        return 301 /admin/;
    }

    location ^~ /admin/ {
        proxy_pass http://${UPSTREAM_ADMIN_HOST}:${UPSTREAM_ADMIN_PORT};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri /index.html;
    }
}   
