// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPlanAdmin = `-- name: CreatePlanAdmin :one
INSERT INTO plans (
    name,
    max_total_storage_bytes,
    max_file_size_bytes,
    max_files,
    max_files_sent_per_day,
    max_shares_per_day,
    max_files_workspace,
    max_user_workspaces,
    max_total_storage_bytes_workspace,
    max_users_workspace,
    max_workspace_folders,
    max_private_api_keys,
    max_workspace_api_keys
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, name, max_total_storage_bytes, max_file_size_bytes, max_files, max_files_sent_per_day, max_shares_per_day, created_at, max_files_workspace, max_user_workspaces, max_total_storage_bytes_workspace, max_users_workspace, max_workspace_folders, max_private_api_keys, max_workspace_api_keys
`

type CreatePlanAdminParams struct {
	Name                          string `json:"name"`
	MaxTotalStorageBytes          int64  `json:"max_total_storage_bytes"`
	MaxFileSizeBytes              int64  `json:"max_file_size_bytes"`
	MaxFiles                      int32  `json:"max_files"`
	MaxFilesSentPerDay            int32  `json:"max_files_sent_per_day"`
	MaxSharesPerDay               int32  `json:"max_shares_per_day"`
	MaxFilesWorkspace             int64  `json:"max_files_workspace"`
	MaxUserWorkspaces             int64  `json:"max_user_workspaces"`
	MaxTotalStorageBytesWorkspace int64  `json:"max_total_storage_bytes_workspace"`
	MaxUsersWorkspace             int64  `json:"max_users_workspace"`
	MaxWorkspaceFolders           int64  `json:"max_workspace_folders"`
	MaxPrivateApiKeys             int64  `json:"max_private_api_keys"`
	MaxWorkspaceApiKeys           int64  `json:"max_workspace_api_keys"`
}

func (q *Queries) CreatePlanAdmin(ctx context.Context, arg CreatePlanAdminParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlanAdmin,
		arg.Name,
		arg.MaxTotalStorageBytes,
		arg.MaxFileSizeBytes,
		arg.MaxFiles,
		arg.MaxFilesSentPerDay,
		arg.MaxSharesPerDay,
		arg.MaxFilesWorkspace,
		arg.MaxUserWorkspaces,
		arg.MaxTotalStorageBytesWorkspace,
		arg.MaxUsersWorkspace,
		arg.MaxWorkspaceFolders,
		arg.MaxPrivateApiKeys,
		arg.MaxWorkspaceApiKeys,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxTotalStorageBytes,
		&i.MaxFileSizeBytes,
		&i.MaxFiles,
		&i.MaxFilesSentPerDay,
		&i.MaxSharesPerDay,
		&i.CreatedAt,
		&i.MaxFilesWorkspace,
		&i.MaxUserWorkspaces,
		&i.MaxTotalStorageBytesWorkspace,
		&i.MaxUsersWorkspace,
		&i.MaxWorkspaceFolders,
		&i.MaxPrivateApiKeys,
		&i.MaxWorkspaceApiKeys,
	)
	return i, err
}

const getUserAdminByID = `-- name: GetUserAdminByID :one
SELECT
    u.id,
    u.user_email,
    u.created_at,
    u.plan_id,
    p.name AS plan_name,
    COUNT(f.id) AS file_count,
    COALESCE(SUM(f.size), 0)::BIGINT AS total_storage_bytes
FROM users u
LEFT JOIN plans p ON p.id = u.plan_id
LEFT JOIN files f ON f.owner_id = u.id
WHERE u.id = $1
GROUP BY u.id, u.user_email, u.created_at, u.plan_id, p.name
`

type GetUserAdminByIDRow struct {
	ID                uuid.UUID      `json:"id"`
	UserEmail         string         `json:"user_email"`
	CreatedAt         time.Time      `json:"created_at"`
	PlanID            uuid.NullUUID  `json:"plan_id"`
	PlanName          sql.NullString `json:"plan_name"`
	FileCount         int64          `json:"file_count"`
	TotalStorageBytes int64          `json:"total_storage_bytes"`
}

func (q *Queries) GetUserAdminByID(ctx context.Context, id uuid.UUID) (GetUserAdminByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAdminByID, id)
	var i GetUserAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.CreatedAt,
		&i.PlanID,
		&i.PlanName,
		&i.FileCount,
		&i.TotalStorageBytes,
	)
	return i, err
}

const listPlansAdmin = `-- name: ListPlansAdmin :many
SELECT id, name, max_total_storage_bytes, max_file_size_bytes, max_files, max_files_sent_per_day, max_shares_per_day, created_at, max_files_workspace, max_user_workspaces, max_total_storage_bytes_workspace, max_users_workspace, max_workspace_folders, max_private_api_keys, max_workspace_api_keys
FROM plans
ORDER BY created_at DESC
`

func (q *Queries) ListPlansAdmin(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxTotalStorageBytes,
			&i.MaxFileSizeBytes,
			&i.MaxFiles,
			&i.MaxFilesSentPerDay,
			&i.MaxSharesPerDay,
			&i.CreatedAt,
			&i.MaxFilesWorkspace,
			&i.MaxUserWorkspaces,
			&i.MaxTotalStorageBytesWorkspace,
			&i.MaxUsersWorkspace,
			&i.MaxWorkspaceFolders,
			&i.MaxPrivateApiKeys,
			&i.MaxWorkspaceApiKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT
    u.id,
    u.user_email,
    u.created_at,
    u.plan_id,
    p.name AS plan_name,
    COUNT(f.id) AS file_count,
    COALESCE(SUM(f.size), 0)::BIGINT AS total_storage_bytes
FROM users u
LEFT JOIN plans p ON p.id = u.plan_id
LEFT JOIN files f ON f.owner_id = u.id
GROUP BY u.id, u.user_email, u.created_at, u.plan_id, p.name
ORDER BY u.created_at DESC
`

type ListUsersAdminRow struct {
	ID                uuid.UUID      `json:"id"`
	UserEmail         string         `json:"user_email"`
	CreatedAt         time.Time      `json:"created_at"`
	PlanID            uuid.NullUUID  `json:"plan_id"`
	PlanName          sql.NullString `json:"plan_name"`
	FileCount         int64          `json:"file_count"`
	TotalStorageBytes int64          `json:"total_storage_bytes"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context) ([]ListUsersAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.CreatedAt,
			&i.PlanID,
			&i.PlanName,
			&i.FileCount,
			&i.TotalStorageBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverCapacitySummary = `-- name: ServerCapacitySummary :one
SELECT
    COUNT(u.id)::BIGINT AS total_users,
    COUNT(f.id)::BIGINT AS total_files,
    COALESCE(SUM(f.size), 0)::BIGINT AS total_storage_bytes
FROM users u
LEFT JOIN files f ON f.owner_id = u.id
`

type ServerCapacitySummaryRow struct {
	TotalUsers        int64 `json:"total_users"`
	TotalFiles        int64 `json:"total_files"`
	TotalStorageBytes int64 `json:"total_storage_bytes"`
}

func (q *Queries) ServerCapacitySummary(ctx context.Context) (ServerCapacitySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, serverCapacitySummary)
	var i ServerCapacitySummaryRow
	err := row.Scan(&i.TotalUsers, &i.TotalFiles, &i.TotalStorageBytes)
	return i, err
}

const updatePlanAdmin = `-- name: UpdatePlanAdmin :exec
UPDATE plans
SET
    name = $1,
    max_total_storage_bytes = $2,
    max_file_size_bytes = $3,
    max_files = $4,
    max_files_sent_per_day = $5,
    max_shares_per_day = $6,
    max_files_workspace = $7,
    max_user_workspaces = $8,
    max_total_storage_bytes_workspace = $9,
    max_users_workspace = $10,
    max_workspace_folders = $11,
    max_private_api_keys = $12,
    max_workspace_api_keys = $13
WHERE id = $14
`

type UpdatePlanAdminParams struct {
	Name                          string    `json:"name"`
	MaxTotalStorageBytes          int64     `json:"max_total_storage_bytes"`
	MaxFileSizeBytes              int64     `json:"max_file_size_bytes"`
	MaxFiles                      int32     `json:"max_files"`
	MaxFilesSentPerDay            int32     `json:"max_files_sent_per_day"`
	MaxSharesPerDay               int32     `json:"max_shares_per_day"`
	MaxFilesWorkspace             int64     `json:"max_files_workspace"`
	MaxUserWorkspaces             int64     `json:"max_user_workspaces"`
	MaxTotalStorageBytesWorkspace int64     `json:"max_total_storage_bytes_workspace"`
	MaxUsersWorkspace             int64     `json:"max_users_workspace"`
	MaxWorkspaceFolders           int64     `json:"max_workspace_folders"`
	MaxPrivateApiKeys             int64     `json:"max_private_api_keys"`
	MaxWorkspaceApiKeys           int64     `json:"max_workspace_api_keys"`
	ID                            uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePlanAdmin(ctx context.Context, arg UpdatePlanAdminParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanAdmin,
		arg.Name,
		arg.MaxTotalStorageBytes,
		arg.MaxFileSizeBytes,
		arg.MaxFiles,
		arg.MaxFilesSentPerDay,
		arg.MaxSharesPerDay,
		arg.MaxFilesWorkspace,
		arg.MaxUserWorkspaces,
		arg.MaxTotalStorageBytesWorkspace,
		arg.MaxUsersWorkspace,
		arg.MaxWorkspaceFolders,
		arg.MaxPrivateApiKeys,
		arg.MaxWorkspaceApiKeys,
		arg.ID,
	)
	return err
}
