// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key_identity.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getIdentityByAPIKey = `-- name: GetIdentityByAPIKey :one
SELECT id, user_id, provider, provider_user_id, email, email_verified, name, avatar_url, created_at FROM identities WHERE user_id = $1
`

// - PLACEHOLDER FOR QUERY
func (q *Queries) GetIdentityByAPIKey(ctx context.Context, userID uuid.UUID) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByAPIKey, userID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
