// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const assignAPIKeyToPrivate = `-- name: AssignAPIKeyToPrivate :one
INSERT INTO api_key_user_assignments (api_key_id, user_id)
VALUES ($1, $2)
RETURNING api_key_id, user_id, assigned_at
`

type AssignAPIKeyToPrivateParams struct {
	ApiKeyID uuid.UUID `json:"api_key_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) AssignAPIKeyToPrivate(ctx context.Context, arg AssignAPIKeyToPrivateParams) (ApiKeyUserAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignAPIKeyToPrivate, arg.ApiKeyID, arg.UserID)
	var i ApiKeyUserAssignment
	err := row.Scan(&i.ApiKeyID, &i.UserID, &i.AssignedAt)
	return i, err
}

const assignAPIKeyToWorkspace = `-- name: AssignAPIKeyToWorkspace :one
INSERT INTO api_key_workspaces (api_key_id, workspace_id)
VALUES ($1, $2)
RETURNING api_key_id, workspace_id
`

type AssignAPIKeyToWorkspaceParams struct {
	ApiKeyID    uuid.UUID `json:"api_key_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) AssignAPIKeyToWorkspace(ctx context.Context, arg AssignAPIKeyToWorkspaceParams) (ApiKeyWorkspace, error) {
	row := q.db.QueryRowContext(ctx, assignAPIKeyToWorkspace, arg.ApiKeyID, arg.WorkspaceID)
	var i ApiKeyWorkspace
	err := row.Scan(&i.ApiKeyID, &i.WorkspaceID)
	return i, err
}

const checkPrivateAPIKeyQuota = `-- name: CheckPrivateAPIKeyQuota :one
SELECT (
	SELECT COUNT(*)
	FROM api_key_user_assignments a
	JOIN api_keys ak ON ak.id = a.api_key_id
	WHERE a.user_id = $1
		AND ak.revoked_at IS NULL
) >= p.max_private_api_keys AS api_keys_exceeded
FROM users u
JOIN plans p ON u.plan_id = p.id
WHERE u.id = $1
`

func (q *Queries) CheckPrivateAPIKeyQuota(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPrivateAPIKeyQuota, userID)
	var api_keys_exceeded bool
	err := row.Scan(&api_keys_exceeded)
	return api_keys_exceeded, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (created_by_user_id, name, key_hash, description, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_by_user_id, created_at, name, key_hash, description, status, last_used_at, revoked_at, revoked_by_user_id
`

type CreateAPIKeyParams struct {
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	Name            string         `json:"name"`
	KeyHash         string         `json:"key_hash"`
	Description     sql.NullString `json:"description"`
	Status          string         `json:"status"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.CreatedByUserID,
		arg.Name,
		arg.KeyHash,
		arg.Description,
		arg.Status,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Name,
		&i.KeyHash,
		&i.Description,
		&i.Status,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
	)
	return i, err
}

const createAPIKeyScope = `-- name: CreateAPIKeyScope :exec
INSERT INTO api_key_scopes (api_key_id, scope) VALUES ($1,$2)
`

type CreateAPIKeyScopeParams struct {
	ApiKeyID uuid.UUID `json:"api_key_id"`
	Scope    string    `json:"scope"`
}

func (q *Queries) CreateAPIKeyScope(ctx context.Context, arg CreateAPIKeyScopeParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKeyScope, arg.ApiKeyID, arg.Scope)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, created_by_user_id, created_at, name, key_hash, description, status, last_used_at, revoked_at, revoked_by_user_id FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Name,
		&i.KeyHash,
		&i.Description,
		&i.Status,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
	)
	return i, err
}

const listAPIKeyScopes = `-- name: ListAPIKeyScopes :many
SELECT scope
FROM api_key_scopes
WHERE api_key_id = $1
ORDER BY scope
`

func (q *Queries) ListAPIKeyScopes(ctx context.Context, apiKeyID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeyScopes, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAPIKeys = `-- name: ListWorkspaceAPIKeys :many
SELECT
	ak.id,
	ak.created_by_user_id,
	ak.created_at,
	ak.name,
	ak.description,
	ak.status,
	ak.last_used_at
FROM api_keys ak
JOIN api_key_workspaces akw ON akw.api_key_id = ak.id
WHERE akw.workspace_id = $1
	AND ak.revoked_at IS NULL
ORDER BY ak.created_at DESC
`

type ListWorkspaceAPIKeysRow struct {
	ID              uuid.UUID      `json:"id"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	CreatedAt       time.Time      `json:"created_at"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Status          string         `json:"status"`
	LastUsedAt      sql.NullTime   `json:"last_used_at"`
}

func (q *Queries) ListWorkspaceAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceAPIKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceAPIKeysRow
	for rows.Next() {
		var i ListWorkspaceAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkspaceAPIKey = `-- name: RevokeWorkspaceAPIKey :one
UPDATE api_keys ak
SET status = 'revoked',
	revoked_at = now(),
	revoked_by_user_id = $3
FROM api_key_workspaces akw
WHERE ak.id = $1
	AND akw.api_key_id = ak.id
	AND akw.workspace_id = $2
	AND ak.revoked_at IS NULL
RETURNING ak.id, ak.created_by_user_id, ak.created_at, ak.name, ak.key_hash, ak.description, ak.status, ak.last_used_at, ak.revoked_at, ak.revoked_by_user_id
`

type RevokeWorkspaceAPIKeyParams struct {
	ID              uuid.UUID     `json:"id"`
	WorkspaceID     uuid.UUID     `json:"workspace_id"`
	RevokedByUserID uuid.NullUUID `json:"revoked_by_user_id"`
}

func (q *Queries) RevokeWorkspaceAPIKey(ctx context.Context, arg RevokeWorkspaceAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, revokeWorkspaceAPIKey, arg.ID, arg.WorkspaceID, arg.RevokedByUserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Name,
		&i.KeyHash,
		&i.Description,
		&i.Status,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
	)
	return i, err
}
