// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteFileByNameAndId = `-- name: DeleteFileByNameAndId :exec
DELETE FROM files WHERE owner_id = $1 AND file_name = $2
`

type DeleteFileByNameAndIdParams struct {
	OwnerID  uuid.UUID `json:"owner_id"`
	FileName string    `json:"file_name"`
}

func (q *Queries) DeleteFileByNameAndId(ctx context.Context, arg DeleteFileByNameAndIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileByNameAndId, arg.OwnerID, arg.FileName)
	return err
}

const getFileById = `-- name: GetFileById :one
SELECT id, file_name, file_type, size, md5_checksum, private_download_token, owner_id FROM files WHERE id = $1
`

func (q *Queries) GetFileById(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileById, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.PrivateDownloadToken,
		&i.OwnerID,
	)
	return i, err
}

const getFileByOwnerAndName = `-- name: GetFileByOwnerAndName :one
SELECT id, md5_checksum
FROM files
WHERE owner_id = $1 AND file_name = $2
`

type GetFileByOwnerAndNameParams struct {
	OwnerID  uuid.UUID `json:"owner_id"`
	FileName string    `json:"file_name"`
}

type GetFileByOwnerAndNameRow struct {
	ID          int32  `json:"id"`
	Md5Checksum string `json:"md5_checksum"`
}

func (q *Queries) GetFileByOwnerAndName(ctx context.Context, arg GetFileByOwnerAndNameParams) (GetFileByOwnerAndNameRow, error) {
	row := q.db.QueryRowContext(ctx, getFileByOwnerAndName, arg.OwnerID, arg.FileName)
	var i GetFileByOwnerAndNameRow
	err := row.Scan(&i.ID, &i.Md5Checksum)
	return i, err
}

const getFileFromChecksum = `-- name: GetFileFromChecksum :one
SELECT id FROM files WHERE md5_checksum = $1
`

func (q *Queries) GetFileFromChecksum(ctx context.Context, md5Checksum string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getFileFromChecksum, md5Checksum)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getFileIdFromToken = `-- name: GetFileIdFromToken :one
SELECT id FROM files WHERE private_download_token = $1
`

func (q *Queries) GetFileIdFromToken(ctx context.Context, privateDownloadToken sql.NullString) (int32, error) {
	row := q.db.QueryRowContext(ctx, getFileIdFromToken, privateDownloadToken)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getFilesByOwner = `-- name: GetFilesByOwner :many

SELECT id, file_name, file_type, size, md5_checksum, private_download_token, owner_id FROM files WHERE owner_id = $1
`

// -- name: InsertFileReturningID :one
// INSERT INTO files (owner_id, file_name, file_type, size, md5_checksum, private_download_token)
// VALUES ($1, $2, $3, $4, $5, $6)
// ON CONFLICT (owner_id, md5_checksum) DO NOTHING
// RETURNING id;
func (q *Queries) GetFilesByOwner(ctx context.Context, ownerID uuid.UUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.PrivateDownloadToken,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (owner_id, file_name, file_type, size, md5_checksum, private_download_token)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, file_name, file_type, size, md5_checksum, private_download_token, owner_id
`

type InsertFileParams struct {
	OwnerID              uuid.UUID      `json:"owner_id"`
	FileName             string         `json:"file_name"`
	FileType             sql.NullString `json:"file_type"`
	Size                 sql.NullInt64  `json:"size"`
	Md5Checksum          string         `json:"md5_checksum"`
	PrivateDownloadToken sql.NullString `json:"private_download_token"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile,
		arg.OwnerID,
		arg.FileName,
		arg.FileType,
		arg.Size,
		arg.Md5Checksum,
		arg.PrivateDownloadToken,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.PrivateDownloadToken,
		&i.OwnerID,
	)
	return i, err
}

const updateFileNameByOwnerAndName = `-- name: UpdateFileNameByOwnerAndName :exec
UPDATE files
SET file_name = $1
WHERE owner_id = $2 AND file_name = $3
`

type UpdateFileNameByOwnerAndNameParams struct {
	FileName   string    `json:"file_name"`
	OwnerID    uuid.UUID `json:"owner_id"`
	FileName_2 string    `json:"file_name_2"`
}

func (q *Queries) UpdateFileNameByOwnerAndName(ctx context.Context, arg UpdateFileNameByOwnerAndNameParams) error {
	_, err := q.db.ExecContext(ctx, updateFileNameByOwnerAndName, arg.FileName, arg.OwnerID, arg.FileName_2)
	return err
}
