// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_uploads.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFileUpload = `-- name: CreateFileUpload :one
INSERT INTO file_uploads
(
  owner_id,
  storage_backend,
  storage_upload_id,
  storage_mapping,
  file_name,
  file_type,
  expected_size,
  status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, storage_backend, storage_upload_id, storage_mapping, file_name, file_type, expected_size, uploaded_size, status, created_at, updated_at
`

type CreateFileUploadParams struct {
	OwnerID         uuid.UUID      `json:"owner_id"`
	StorageBackend  string         `json:"storage_backend"`
	StorageUploadID sql.NullString `json:"storage_upload_id"`
	StorageMapping  uuid.UUID      `json:"storage_mapping"`
	FileName        string         `json:"file_name"`
	FileType        sql.NullString `json:"file_type"`
	ExpectedSize    int64          `json:"expected_size"`
	Status          string         `json:"status"`
}

func (q *Queries) CreateFileUpload(ctx context.Context, arg CreateFileUploadParams) (FileUpload, error) {
	row := q.db.QueryRowContext(ctx, createFileUpload,
		arg.OwnerID,
		arg.StorageBackend,
		arg.StorageUploadID,
		arg.StorageMapping,
		arg.FileName,
		arg.FileType,
		arg.ExpectedSize,
		arg.Status,
	)
	var i FileUpload
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StorageBackend,
		&i.StorageUploadID,
		&i.StorageMapping,
		&i.FileName,
		&i.FileType,
		&i.ExpectedSize,
		&i.UploadedSize,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
