// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (user_id, provider, provider_user_id, email, email_verified, name, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, provider, provider_user_id, email, email_verified, name, avatar_url, created_at
`

type CreateIdentityParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	Email          sql.NullString `json:"email"`
	EmailVerified  sql.NullBool   `json:"email_verified"`
	Name           sql.NullString `json:"name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.EmailVerified,
		arg.Name,
		arg.AvatarUrl,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByProvider = `-- name: GetIdentityByProvider :one
SELECT id, user_id, provider, provider_user_id, email, email_verified, name, avatar_url, created_at FROM identities WHERE provider = $1 AND provider_user_id = $2
`

type GetIdentityByProviderParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByUserID = `-- name: GetIdentityByUserID :one
SELECT id, user_id, provider, provider_user_id, email, email_verified, name, avatar_url, created_at FROM identities WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetIdentityByUserID(ctx context.Context, userID uuid.UUID) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByUserID, userID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
