// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlc

import (
	"context"
)

const metricsActiveAPIKeysByDomain = `-- name: MetricsActiveAPIKeysByDomain :many
SELECT domain, active_count
FROM (
    SELECT 'private'::TEXT AS domain, COUNT(DISTINCT ak.id)::BIGINT AS active_count
    FROM api_keys ak
    JOIN api_key_user_assignments akua ON akua.api_key_id = ak.id
    WHERE ak.revoked_at IS NULL

    UNION ALL

    SELECT 'workspace'::TEXT AS domain, COUNT(DISTINCT ak.id)::BIGINT AS active_count
    FROM api_keys ak
    JOIN api_key_workspaces akw ON akw.api_key_id = ak.id
    WHERE ak.revoked_at IS NULL
) AS counts
ORDER BY domain
`

type MetricsActiveAPIKeysByDomainRow struct {
	Domain      string `json:"domain"`
	ActiveCount int64  `json:"active_count"`
}

func (q *Queries) MetricsActiveAPIKeysByDomain(ctx context.Context) ([]MetricsActiveAPIKeysByDomainRow, error) {
	rows, err := q.db.QueryContext(ctx, metricsActiveAPIKeysByDomain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricsActiveAPIKeysByDomainRow
	for rows.Next() {
		var i MetricsActiveAPIKeysByDomainRow
		if err := rows.Scan(&i.Domain, &i.ActiveCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsActiveSharesTotal = `-- name: MetricsActiveSharesTotal :one
SELECT COUNT(*)::BIGINT AS active_shares
FROM shares
WHERE expires_at > NOW()
`

func (q *Queries) MetricsActiveSharesTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, metricsActiveSharesTotal)
	var active_shares int64
	err := row.Scan(&active_shares)
	return active_shares, err
}

const metricsFilesAndStorageTotals = `-- name: MetricsFilesAndStorageTotals :one
SELECT
    (
        (SELECT COUNT(*)::BIGINT FROM files) +
        (SELECT COUNT(*)::BIGINT FROM workspace_files WHERE file_type != 'inode/directory')
    )::BIGINT AS total_files,
    (
        (SELECT COALESCE(SUM(size), 0)::BIGINT FROM files) +
        (SELECT COALESCE(SUM(size), 0)::BIGINT FROM workspace_files WHERE file_type != 'inode/directory')
    )::BIGINT AS total_storage_bytes
`

type MetricsFilesAndStorageTotalsRow struct {
	TotalFiles        int64 `json:"total_files"`
	TotalStorageBytes int64 `json:"total_storage_bytes"`
}

func (q *Queries) MetricsFilesAndStorageTotals(ctx context.Context) (MetricsFilesAndStorageTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, metricsFilesAndStorageTotals)
	var i MetricsFilesAndStorageTotalsRow
	err := row.Scan(&i.TotalFiles, &i.TotalStorageBytes)
	return i, err
}

const metricsUsersByPlan = `-- name: MetricsUsersByPlan :many
SELECT
    COALESCE(p.name, 'unassigned') AS plan_name,
    COUNT(*)::BIGINT AS user_count
FROM users u
LEFT JOIN plans p ON p.id = u.plan_id
GROUP BY COALESCE(p.name, 'unassigned')
ORDER BY plan_name
`

type MetricsUsersByPlanRow struct {
	PlanName  string `json:"plan_name"`
	UserCount int64  `json:"user_count"`
}

func (q *Queries) MetricsUsersByPlan(ctx context.Context) ([]MetricsUsersByPlanRow, error) {
	rows, err := q.db.QueryContext(ctx, metricsUsersByPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricsUsersByPlanRow
	for rows.Next() {
		var i MetricsUsersByPlanRow
		if err := rows.Scan(&i.PlanName, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsUsersTotal = `-- name: MetricsUsersTotal :one
SELECT COUNT(*)::BIGINT AS total_users
FROM users
`

func (q *Queries) MetricsUsersTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, metricsUsersTotal)
	var total_users int64
	err := row.Scan(&total_users)
	return total_users, err
}

const metricsWorkspacesTotal = `-- name: MetricsWorkspacesTotal :one
SELECT COUNT(*)::BIGINT AS total_workspaces
FROM workspaces
`

func (q *Queries) MetricsWorkspacesTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, metricsWorkspacesTotal)
	var total_workspaces int64
	err := row.Scan(&total_workspaces)
	return total_workspaces, err
}
