// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID              uuid.UUID      `json:"id"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	CreatedAt       time.Time      `json:"created_at"`
	Name            string         `json:"name"`
	KeyHash         string         `json:"key_hash"`
	Description     sql.NullString `json:"description"`
	Status          string         `json:"status"`
	LastUsedAt      sql.NullTime   `json:"last_used_at"`
	RevokedAt       sql.NullTime   `json:"revoked_at"`
	RevokedByUserID uuid.NullUUID  `json:"revoked_by_user_id"`
}

type ApiKeyScope struct {
	ApiKeyID uuid.UUID `json:"api_key_id"`
	Scope    string    `json:"scope"`
}

type ApiKeyUserAssignment struct {
	ApiKeyID   uuid.UUID `json:"api_key_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type ApiKeyWorkspace struct {
	ApiKeyID    uuid.UUID `json:"api_key_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type File struct {
	ID                   int32          `json:"id"`
	FileName             string         `json:"file_name"`
	FileType             sql.NullString `json:"file_type"`
	Size                 sql.NullInt64  `json:"size"`
	Md5Checksum          string         `json:"md5_checksum"`
	PrivateDownloadToken sql.NullString `json:"private_download_token"`
	OwnerID              uuid.UUID      `json:"owner_id"`
	StorageMapping       uuid.UUID      `json:"storage_mapping"`
	CreatedAt            time.Time      `json:"created_at"`
}

type Identity struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	Email          sql.NullString `json:"email"`
	EmailVerified  sql.NullBool   `json:"email_verified"`
	Name           sql.NullString `json:"name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Note struct {
	ID      int32         `json:"id"`
	FileID  sql.NullInt32 `json:"file_id"`
	Content string        `json:"content"`
	UserID  uuid.UUID     `json:"user_id"`
}

type Plan struct {
	ID                            uuid.UUID `json:"id"`
	Name                          string    `json:"name"`
	MaxTotalStorageBytes          int64     `json:"max_total_storage_bytes"`
	MaxFileSizeBytes              int64     `json:"max_file_size_bytes"`
	MaxFiles                      int32     `json:"max_files"`
	MaxFilesSentPerDay            int32     `json:"max_files_sent_per_day"`
	MaxSharesPerDay               int32     `json:"max_shares_per_day"`
	CreatedAt                     time.Time `json:"created_at"`
	MaxFilesWorkspace             int64     `json:"max_files_workspace"`
	MaxUserWorkspaces             int64     `json:"max_user_workspaces"`
	MaxTotalStorageBytesWorkspace int64     `json:"max_total_storage_bytes_workspace"`
	MaxUsersWorkspace             int64     `json:"max_users_workspace"`
	MaxWorkspaceFolders           int64     `json:"max_workspace_folders"`
	MaxPrivateApiKeys             int64     `json:"max_private_api_keys"`
	MaxWorkspaceApiKeys           int64     `json:"max_workspace_api_keys"`
}

type PlanFeature struct {
	PlanID  uuid.UUID `json:"plan_id"`
	Feature string    `json:"feature"`
}

type Session struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Provider            string         `json:"provider"`
	ProviderAccessToken sql.NullString `json:"provider_access_token"`
	ExpiresAt           time.Time      `json:"expires_at"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Share struct {
	ID             int32          `json:"id"`
	SharedBy       sql.NullString `json:"shared_by"`
	SharedFor      sql.NullString `json:"shared_for"`
	SharingToken   string         `json:"sharing_token"`
	FileID         sql.NullInt32  `json:"file_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	ReceivedSeenAt sql.NullTime   `json:"received_seen_at"`
	SharedByUserID uuid.NullUUID  `json:"shared_by_user_id"`
	PasswordHash   sql.NullString `json:"password_hash"`
	FailedAttempts int32          `json:"failed_attempts"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	UserBucket sql.NullString `json:"user_bucket"`
	UserEmail  string         `json:"user_email"`
	CreatedAt  time.Time      `json:"created_at"`
	PlanID     uuid.NullUUID  `json:"plan_id"`
}

type UsersOld struct {
	GoogleID   string         `json:"google_id"`
	UserName   sql.NullString `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserBucket sql.NullString `json:"user_bucket"`
	ID         uuid.UUID      `json:"id"`
}

type Workspace struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	OwnerID   uuid.UUID `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
}

type WorkspaceFile struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	UploadedBy  uuid.UUID      `json:"uploaded_by"`
	FileName    string         `json:"file_name"`
	FileType    sql.NullString `json:"file_type"`
	Size        int64          `json:"size"`
	Md5Checksum sql.NullString `json:"md5_checksum"`
	Path        string         `json:"path"`
	CreatedAt   time.Time      `json:"created_at"`
}

type WorkspaceInvite struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Email       string    `json:"email"`
	Token       string    `json:"token"`
	Role        string    `json:"role"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	JoinedAt    time.Time `json:"joined_at"`
}
