// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const blockUntil = `-- name: BlockUntil :one
UPDATE auth_rate_limits
SET blocked_until = $3,
    updated_at = now()
WHERE key = $1 AND scope = $2
RETURNING id, key, scope, attempt_count, blocked_until, created_at, updated_at
`

type BlockUntilParams struct {
	Key          string       `json:"key"`
	Scope        string       `json:"scope"`
	BlockedUntil sql.NullTime `json:"blocked_until"`
}

func (q *Queries) BlockUntil(ctx context.Context, arg BlockUntilParams) (AuthRateLimit, error) {
	row := q.db.QueryRowContext(ctx, blockUntil, arg.Key, arg.Scope, arg.BlockedUntil)
	var i AuthRateLimit
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.AttemptCount,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeEmailVerificationChallenge = `-- name: ConsumeEmailVerificationChallenge :one
UPDATE email_verification_challenges
SET consumed_at = now()
WHERE id = $1
RETURNING id, email, user_id, purpose, code_hash, expires_at, max_attempts, resend_available_at, requested_by_ip, request_context, consumed_at, created_at
`

func (q *Queries) ConsumeEmailVerificationChallenge(ctx context.Context, id uuid.UUID) (EmailVerificationChallenge, error) {
	row := q.db.QueryRowContext(ctx, consumeEmailVerificationChallenge, id)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.ResendAvailableAt,
		&i.RequestedByIp,
		&i.RequestContext,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthRateLimit = `-- name: CreateAuthRateLimit :one
INSERT INTO auth_rate_limits (key, scope, attempt_count)
VALUES ($1, $2, $3)
RETURNING id, key, scope, attempt_count, blocked_until, created_at, updated_at
`

type CreateAuthRateLimitParams struct {
	Key          string `json:"key"`
	Scope        string `json:"scope"`
	AttemptCount int32  `json:"attempt_count"`
}

func (q *Queries) CreateAuthRateLimit(ctx context.Context, arg CreateAuthRateLimitParams) (AuthRateLimit, error) {
	row := q.db.QueryRowContext(ctx, createAuthRateLimit, arg.Key, arg.Scope, arg.AttemptCount)
	var i AuthRateLimit
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.AttemptCount,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailVerificationChallenge = `-- name: CreateEmailVerificationChallenge :one
INSERT INTO email_verification_challenges (email, user_id, purpose, code_hash, expires_at, requested_by_ip, request_context, resend_available_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, user_id, purpose, code_hash, expires_at, max_attempts, resend_available_at, requested_by_ip, request_context, consumed_at, created_at
`

type CreateEmailVerificationChallengeParams struct {
	Email             string          `json:"email"`
	UserID            uuid.NullUUID   `json:"user_id"`
	Purpose           string          `json:"purpose"`
	CodeHash          string          `json:"code_hash"`
	ExpiresAt         time.Time       `json:"expires_at"`
	RequestedByIp     string          `json:"requested_by_ip"`
	RequestContext    json.RawMessage `json:"request_context"`
	ResendAvailableAt time.Time       `json:"resend_available_at"`
}

func (q *Queries) CreateEmailVerificationChallenge(ctx context.Context, arg CreateEmailVerificationChallengeParams) (EmailVerificationChallenge, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerificationChallenge,
		arg.Email,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.RequestedByIp,
		arg.RequestContext,
		arg.ResendAvailableAt,
	)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.ResendAvailableAt,
		&i.RequestedByIp,
		&i.RequestContext,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordCredentials = `-- name: CreatePasswordCredentials :one
INSERT INTO password_credentials (user_id, password_hash, password_set_by)
VALUES ($1, $2, $3)
RETURNING id, user_id, password_hash, password_set_by, last_password_login_verified_at, updated_at, created_at
`

type CreatePasswordCredentialsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PasswordHash  string    `json:"password_hash"`
	PasswordSetBy string    `json:"password_set_by"`
}

func (q *Queries) CreatePasswordCredentials(ctx context.Context, arg CreatePasswordCredentialsParams) (PasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, createPasswordCredentials, arg.UserID, arg.PasswordHash, arg.PasswordSetBy)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordSetBy,
		&i.LastPasswordLoginVerifiedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationChallengeById = `-- name: DeleteEmailVerificationChallengeById :exec
DELETE FROM email_verification_challenges
WHERE id = $1
`

func (q *Queries) DeleteEmailVerificationChallengeById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerificationChallengeById, id)
	return err
}

const getAuthRateLimitByKeyAndScope = `-- name: GetAuthRateLimitByKeyAndScope :one
SELECT id, key, scope, attempt_count, blocked_until, created_at, updated_at FROM auth_rate_limits
WHERE key = $1 AND scope = $2
`

type GetAuthRateLimitByKeyAndScopeParams struct {
	Key   string `json:"key"`
	Scope string `json:"scope"`
}

func (q *Queries) GetAuthRateLimitByKeyAndScope(ctx context.Context, arg GetAuthRateLimitByKeyAndScopeParams) (AuthRateLimit, error) {
	row := q.db.QueryRowContext(ctx, getAuthRateLimitByKeyAndScope, arg.Key, arg.Scope)
	var i AuthRateLimit
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.AttemptCount,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailVerificationChallengeById = `-- name: GetEmailVerificationChallengeById :one
SELECT id, email, user_id, purpose, code_hash, expires_at, max_attempts, resend_available_at, requested_by_ip, request_context, consumed_at, created_at FROM email_verification_challenges
WHERE id = $1
`

func (q *Queries) GetEmailVerificationChallengeById(ctx context.Context, id uuid.UUID) (EmailVerificationChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationChallengeById, id)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.ResendAvailableAt,
		&i.RequestedByIp,
		&i.RequestContext,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationCode = `-- name: GetEmailVerificationCode :one
SELECT id, email, user_id, purpose, code_hash, expires_at, max_attempts, resend_available_at, requested_by_ip, request_context, consumed_at, created_at FROM email_verification_challenges
WHERE email = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetEmailVerificationCodeParams struct {
	Email   string `json:"email"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetEmailVerificationCode(ctx context.Context, arg GetEmailVerificationCodeParams) (EmailVerificationChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationCode, arg.Email, arg.Purpose)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.ResendAvailableAt,
		&i.RequestedByIp,
		&i.RequestContext,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordCredentialsByUserId = `-- name: GetPasswordCredentialsByUserId :one
SELECT id, user_id, password_hash, password_set_by, last_password_login_verified_at, updated_at, created_at
FROM password_credentials
WHERE user_id = $1
`

func (q *Queries) GetPasswordCredentialsByUserId(ctx context.Context, userID uuid.UUID) (PasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredentialsByUserId, userID)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordSetBy,
		&i.LastPasswordLoginVerifiedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAuthRateLimitAttemptCount = `-- name: IncrementAuthRateLimitAttemptCount :one
UPDATE auth_rate_limits
SET attempt_count = attempt_count + 1,
    updated_at = now()
WHERE key = $1 AND scope = $2
RETURNING id, key, scope, attempt_count, blocked_until, created_at, updated_at
`

type IncrementAuthRateLimitAttemptCountParams struct {
	Key   string `json:"key"`
	Scope string `json:"scope"`
}

func (q *Queries) IncrementAuthRateLimitAttemptCount(ctx context.Context, arg IncrementAuthRateLimitAttemptCountParams) (AuthRateLimit, error) {
	row := q.db.QueryRowContext(ctx, incrementAuthRateLimitAttemptCount, arg.Key, arg.Scope)
	var i AuthRateLimit
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.AttemptCount,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordCredentials = `-- name: UpdatePasswordCredentials :one
UPDATE password_credentials
SET password_hash = $2,
    password_set_by = $3,
    updated_at = now()
WHERE user_id = $1
RETURNING id, user_id, password_hash, password_set_by, last_password_login_verified_at, updated_at, created_at
`

type UpdatePasswordCredentialsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PasswordHash  string    `json:"password_hash"`
	PasswordSetBy string    `json:"password_set_by"`
}

func (q *Queries) UpdatePasswordCredentials(ctx context.Context, arg UpdatePasswordCredentialsParams) (PasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, updatePasswordCredentials, arg.UserID, arg.PasswordHash, arg.PasswordSetBy)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordSetBy,
		&i.LastPasswordLoginVerifiedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateResendAvailableAt = `-- name: UpdateResendAvailableAt :one
UPDATE email_verification_challenges
SET resend_available_at = $2
WHERE id = $1
RETURNING id, email, user_id, purpose, code_hash, expires_at, max_attempts, resend_available_at, requested_by_ip, request_context, consumed_at, created_at
`

type UpdateResendAvailableAtParams struct {
	ID                uuid.UUID `json:"id"`
	ResendAvailableAt time.Time `json:"resend_available_at"`
}

func (q *Queries) UpdateResendAvailableAt(ctx context.Context, arg UpdateResendAvailableAtParams) (EmailVerificationChallenge, error) {
	row := q.db.QueryRowContext(ctx, updateResendAvailableAt, arg.ID, arg.ResendAvailableAt)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.MaxAttempts,
		&i.ResendAvailableAt,
		&i.RequestedByIp,
		&i.RequestContext,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
