// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkShareQuota = `-- name: CheckShareQuota :one
SELECT
    (
        SELECT COUNT(*)
        FROM shares
        WHERE shared_by = $1
          AND created_at >= NOW() - INTERVAL '1 day'
    ) >= p.max_shares_per_day AS shares_exceeded
FROM plans p
WHERE p.id = $2
`

type CheckShareQuotaParams struct {
	SharedBy sql.NullString `json:"shared_by"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) CheckShareQuota(ctx context.Context, arg CheckShareQuotaParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkShareQuota, arg.SharedBy, arg.ID)
	var shares_exceeded bool
	err := row.Scan(&shares_exceeded)
	return shares_exceeded, err
}

const checkUploadQuota = `-- name: CheckUploadQuota :one
WITH usage AS (
    SELECT
        COUNT(*)                            AS file_count,
        COALESCE(SUM(size), 0)              AS total_bytes,
        COUNT(*) FILTER (
            WHERE created_at >= NOW() - INTERVAL '1 day'
        )                                   AS files_today
    FROM files
    WHERE owner_id = $1
)
SELECT
    (u.file_count    >= p.max_files)              AS files_exceeded,
    (u.total_bytes   >= p.max_total_storage_bytes) AS storage_exceeded,
    (u.files_today   >= p.max_files_sent_per_day)  AS daily_exceeded
FROM usage u, plans p
WHERE p.id = $2
`

type CheckUploadQuotaParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

type CheckUploadQuotaRow struct {
	FilesExceeded   bool `json:"files_exceeded"`
	StorageExceeded bool `json:"storage_exceeded"`
	DailyExceeded   bool `json:"daily_exceeded"`
}

func (q *Queries) CheckUploadQuota(ctx context.Context, arg CheckUploadQuotaParams) (CheckUploadQuotaRow, error) {
	row := q.db.QueryRowContext(ctx, checkUploadQuota, arg.OwnerID, arg.ID)
	var i CheckUploadQuotaRow
	err := row.Scan(&i.FilesExceeded, &i.StorageExceeded, &i.DailyExceeded)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const deletePlanFeatures = `-- name: DeletePlanFeatures :exec
DELETE FROM plan_features WHERE plan_id = $1
`

func (q *Queries) DeletePlanFeatures(ctx context.Context, planID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlanFeatures, planID)
	return err
}

const deleteUserPlan = `-- name: DeleteUserPlan :exec
UPDATE users SET plan_id = NULL WHERE id = $1
`

func (q *Queries) DeleteUserPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserPlan, id)
	return err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, max_total_storage_bytes, max_file_size_bytes, max_files, max_files_sent_per_day, max_shares_per_day, created_at, max_files_workspace, max_user_workspaces, max_total_storage_bytes_workspace, max_users_workspace, max_workspace_folders FROM plans WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxTotalStorageBytes,
		&i.MaxFileSizeBytes,
		&i.MaxFiles,
		&i.MaxFilesSentPerDay,
		&i.MaxSharesPerDay,
		&i.CreatedAt,
		&i.MaxFilesWorkspace,
		&i.MaxUserWorkspaces,
		&i.MaxTotalStorageBytesWorkspace,
		&i.MaxUsersWorkspace,
		&i.MaxWorkspaceFolders,
	)
	return i, err
}

const getPlanFeatures = `-- name: GetPlanFeatures :many
SELECT plan_id, feature FROM plan_features WHERE plan_id = $1
`

func (q *Queries) GetPlanFeatures(ctx context.Context, planID uuid.UUID) ([]PlanFeature, error) {
	rows, err := q.db.QueryContext(ctx, getPlanFeatures, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanFeature
	for rows.Next() {
		var i PlanFeature
		if err := rows.Scan(&i.PlanID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlans = `-- name: GetPlans :many
SELECT id, name, max_total_storage_bytes, max_file_size_bytes, max_files, max_files_sent_per_day, max_shares_per_day, created_at, max_files_workspace, max_user_workspaces, max_total_storage_bytes_workspace, max_users_workspace, max_workspace_folders FROM plans
`

func (q *Queries) GetPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxTotalStorageBytes,
			&i.MaxFileSizeBytes,
			&i.MaxFiles,
			&i.MaxFilesSentPerDay,
			&i.MaxSharesPerDay,
			&i.CreatedAt,
			&i.MaxFilesWorkspace,
			&i.MaxUserWorkspaces,
			&i.MaxTotalStorageBytesWorkspace,
			&i.MaxUsersWorkspace,
			&i.MaxWorkspaceFolders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDailyShares = `-- name: GetUserDailyShares :many
SELECT
    shares.created_at::date AS day,
    COUNT(*)::BIGINT         AS shares
FROM shares
WHERE shares.shared_by = (SELECT user_email FROM users WHERE users.id = $1)
  AND shares.created_at >= NOW() - INTERVAL '7 days'
GROUP BY shares.created_at::date
ORDER BY day
`

type GetUserDailySharesRow struct {
	Day    time.Time `json:"day"`
	Shares int64     `json:"shares"`
}

func (q *Queries) GetUserDailyShares(ctx context.Context, id uuid.UUID) ([]GetUserDailySharesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserDailyShares, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDailySharesRow
	for rows.Next() {
		var i GetUserDailySharesRow
		if err := rows.Scan(&i.Day, &i.Shares); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDailyUploads = `-- name: GetUserDailyUploads :many
SELECT
    files.created_at::date AS day,
    COUNT(*)::BIGINT        AS uploads
FROM files
WHERE files.owner_id = $1
  AND files.created_at >= NOW() - INTERVAL '7 days'
GROUP BY files.created_at::date
ORDER BY day
`

type GetUserDailyUploadsRow struct {
	Day     time.Time `json:"day"`
	Uploads int64     `json:"uploads"`
}

func (q *Queries) GetUserDailyUploads(ctx context.Context, ownerID uuid.UUID) ([]GetUserDailyUploadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserDailyUploads, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDailyUploadsRow
	for rows.Next() {
		var i GetUserDailyUploadsRow
		if err := rows.Scan(&i.Day, &i.Uploads); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
WITH file_usage AS (
    SELECT
        COUNT(*)                                                              AS total_files,
        COALESCE(SUM(size), 0)::BIGINT                                        AS total_bytes,
        COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '1 day')       AS files_today,
        COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '7 days')      AS files_last_7d,
        COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '30 days')     AS files_last_30d
    FROM files
    WHERE files.owner_id = $1
),
share_usage AS (
    SELECT
        COUNT(*)                                                              AS total_shares_sent,
        COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '1 day')       AS shares_today,
        COUNT(*) FILTER (WHERE shared_for IS NOT NULL)                        AS targeted_shares,
        COUNT(*) FILTER (WHERE shared_for IS NULL)                            AS public_shares,
        COUNT(*) FILTER (WHERE expires_at > NOW())                            AS active_shares
    FROM shares
    WHERE shares.shared_by = (SELECT user_email FROM users WHERE users.id = $1)
),
received_usage AS (
    SELECT
        COUNT(*) AS total_received
    FROM shares s
    JOIN files f ON f.id = s.file_id
    WHERE s.shared_for = (SELECT user_email FROM users WHERE id = $1)
),
workspace_usage AS (
    SELECT
        COUNT(*) AS owned_workspaces
    FROM workspaces
    WHERE workspaces.owner_id = $1
)
SELECT
    f.total_files,
    f.total_bytes,
    f.files_today,
    f.files_last_7d,
    f.files_last_30d,
    s.total_shares_sent,
    s.shares_today,
    s.targeted_shares,
    s.public_shares,
    s.active_shares,
    r.total_received,
    w.owned_workspaces
FROM file_usage f, share_usage s, received_usage r, workspace_usage w
`

type GetUserStatsRow struct {
	TotalFiles      int64 `json:"total_files"`
	TotalBytes      int64 `json:"total_bytes"`
	FilesToday      int64 `json:"files_today"`
	FilesLast7d     int64 `json:"files_last_7d"`
	FilesLast30d    int64 `json:"files_last_30d"`
	TotalSharesSent int64 `json:"total_shares_sent"`
	SharesToday     int64 `json:"shares_today"`
	TargetedShares  int64 `json:"targeted_shares"`
	PublicShares    int64 `json:"public_shares"`
	ActiveShares    int64 `json:"active_shares"`
	TotalReceived   int64 `json:"total_received"`
	OwnedWorkspaces int64 `json:"owned_workspaces"`
}

func (q *Queries) GetUserStats(ctx context.Context, ownerID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, ownerID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.TotalBytes,
		&i.FilesToday,
		&i.FilesLast7d,
		&i.FilesLast30d,
		&i.TotalSharesSent,
		&i.SharesToday,
		&i.TargetedShares,
		&i.PublicShares,
		&i.ActiveShares,
		&i.TotalReceived,
		&i.OwnedWorkspaces,
	)
	return i, err
}

const getUserWithPlan = `-- name: GetUserWithPlan :one
SELECT
    u.id,
    u.user_email,
    u.user_bucket,
    u.created_at,
    p.id AS plan_id,
    p.name AS plan_name,
    p.max_file_size_bytes,
    p.max_total_storage_bytes,
    p.max_files,
    p.max_files_sent_per_day,
    p.max_shares_per_day,
    p.max_user_workspaces,
    p.max_files_workspace,
    p.max_total_storage_bytes_workspace,
    p.max_users_workspace,
    p.max_workspace_folders
FROM users u
JOIN plans p ON u.plan_id = p.id
WHERE u.id = $1
`

type GetUserWithPlanRow struct {
	ID                            uuid.UUID      `json:"id"`
	UserEmail                     string         `json:"user_email"`
	UserBucket                    sql.NullString `json:"user_bucket"`
	CreatedAt                     time.Time      `json:"created_at"`
	PlanID                        uuid.UUID      `json:"plan_id"`
	PlanName                      string         `json:"plan_name"`
	MaxFileSizeBytes              int64          `json:"max_file_size_bytes"`
	MaxTotalStorageBytes          int64          `json:"max_total_storage_bytes"`
	MaxFiles                      int32          `json:"max_files"`
	MaxFilesSentPerDay            int32          `json:"max_files_sent_per_day"`
	MaxSharesPerDay               int32          `json:"max_shares_per_day"`
	MaxUserWorkspaces             int64          `json:"max_user_workspaces"`
	MaxFilesWorkspace             int64          `json:"max_files_workspace"`
	MaxTotalStorageBytesWorkspace int64          `json:"max_total_storage_bytes_workspace"`
	MaxUsersWorkspace             int64          `json:"max_users_workspace"`
	MaxWorkspaceFolders           int64          `json:"max_workspace_folders"`
}

func (q *Queries) GetUserWithPlan(ctx context.Context, id uuid.UUID) (GetUserWithPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithPlan, id)
	var i GetUserWithPlanRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.UserBucket,
		&i.CreatedAt,
		&i.PlanID,
		&i.PlanName,
		&i.MaxFileSizeBytes,
		&i.MaxTotalStorageBytes,
		&i.MaxFiles,
		&i.MaxFilesSentPerDay,
		&i.MaxSharesPerDay,
		&i.MaxUserWorkspaces,
		&i.MaxFilesWorkspace,
		&i.MaxTotalStorageBytesWorkspace,
		&i.MaxUsersWorkspace,
		&i.MaxWorkspaceFolders,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :exec
UPDATE users SET plan_id = $1 WHERE id = $2
`

type UpdateUserPlanParams struct {
	PlanID uuid.NullUUID `json:"plan_id"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPlan, arg.PlanID, arg.ID)
	return err
}
