// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkShareQuota = `-- name: CheckShareQuota :one
SELECT
    (
        SELECT COUNT(*)
        FROM shares
        WHERE shared_by = $1
          AND created_at >= NOW() - INTERVAL '1 day'
    ) >= p.max_shares_per_day AS shares_exceeded
FROM plans p
WHERE p.id = $2
`

type CheckShareQuotaParams struct {
	SharedBy sql.NullString `json:"shared_by"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) CheckShareQuota(ctx context.Context, arg CheckShareQuotaParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkShareQuota, arg.SharedBy, arg.ID)
	var shares_exceeded bool
	err := row.Scan(&shares_exceeded)
	return shares_exceeded, err
}

const checkUploadQuota = `-- name: CheckUploadQuota :one
WITH usage AS (
    SELECT
        COUNT(*)                            AS file_count,
        COALESCE(SUM(size), 0)              AS total_bytes,
        COUNT(*) FILTER (
            WHERE created_at >= NOW() - INTERVAL '1 day'
        )                                   AS files_today
    FROM files
    WHERE owner_id = $1
)
SELECT
    (u.file_count    >= p.max_files)              AS files_exceeded,
    (u.total_bytes   >= p.max_total_storage_bytes) AS storage_exceeded,
    (u.files_today   >= p.max_files_sent_per_day)  AS daily_exceeded
FROM usage u, plans p
WHERE p.id = $2
`

type CheckUploadQuotaParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

type CheckUploadQuotaRow struct {
	FilesExceeded   bool `json:"files_exceeded"`
	StorageExceeded bool `json:"storage_exceeded"`
	DailyExceeded   bool `json:"daily_exceeded"`
}

func (q *Queries) CheckUploadQuota(ctx context.Context, arg CheckUploadQuotaParams) (CheckUploadQuotaRow, error) {
	row := q.db.QueryRowContext(ctx, checkUploadQuota, arg.OwnerID, arg.ID)
	var i CheckUploadQuotaRow
	err := row.Scan(&i.FilesExceeded, &i.StorageExceeded, &i.DailyExceeded)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const deletePlanFeatures = `-- name: DeletePlanFeatures :exec
DELETE FROM plan_features WHERE plan_id = $1
`

func (q *Queries) DeletePlanFeatures(ctx context.Context, planID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlanFeatures, planID)
	return err
}

const deleteUserPlan = `-- name: DeleteUserPlan :exec
UPDATE users SET plan_id = NULL WHERE id = $1
`

func (q *Queries) DeleteUserPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserPlan, id)
	return err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, max_total_storage_bytes, max_file_size_bytes, max_files, max_files_sent_per_day, max_shares_per_day, created_at, max_files_workspace, max_user_workspaces, max_total_storage_bytes_workspace, max_users_workspace, max_workspace_folders FROM plans WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxTotalStorageBytes,
		&i.MaxFileSizeBytes,
		&i.MaxFiles,
		&i.MaxFilesSentPerDay,
		&i.MaxSharesPerDay,
		&i.CreatedAt,
		&i.MaxFilesWorkspace,
		&i.MaxUserWorkspaces,
		&i.MaxTotalStorageBytesWorkspace,
		&i.MaxUsersWorkspace,
		&i.MaxWorkspaceFolders,
	)
	return i, err
}

const getPlanFeatures = `-- name: GetPlanFeatures :many
SELECT plan_id, feature FROM plan_features WHERE plan_id = $1
`

func (q *Queries) GetPlanFeatures(ctx context.Context, planID uuid.UUID) ([]PlanFeature, error) {
	rows, err := q.db.QueryContext(ctx, getPlanFeatures, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanFeature
	for rows.Next() {
		var i PlanFeature
		if err := rows.Scan(&i.PlanID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlans = `-- name: GetPlans :many
SELECT id, name, max_total_storage_bytes, max_file_size_bytes, max_files, max_files_sent_per_day, max_shares_per_day, created_at, max_files_workspace, max_user_workspaces, max_total_storage_bytes_workspace, max_users_workspace, max_workspace_folders FROM plans
`

func (q *Queries) GetPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxTotalStorageBytes,
			&i.MaxFileSizeBytes,
			&i.MaxFiles,
			&i.MaxFilesSentPerDay,
			&i.MaxSharesPerDay,
			&i.CreatedAt,
			&i.MaxFilesWorkspace,
			&i.MaxUserWorkspaces,
			&i.MaxTotalStorageBytesWorkspace,
			&i.MaxUsersWorkspace,
			&i.MaxWorkspaceFolders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithPlan = `-- name: GetUserWithPlan :one
SELECT
    u.id,
    u.user_email,
    u.user_bucket,
    u.created_at,
    p.id AS plan_id,
    p.name AS plan_name,
    p.max_file_size_bytes,
    p.max_total_storage_bytes,
    p.max_files,
    p.max_files_sent_per_day,
    p.max_shares_per_day
FROM users u
JOIN plans p ON u.plan_id = p.id
WHERE u.id = $1
`

type GetUserWithPlanRow struct {
	ID                   uuid.UUID      `json:"id"`
	UserEmail            string         `json:"user_email"`
	UserBucket           sql.NullString `json:"user_bucket"`
	CreatedAt            time.Time      `json:"created_at"`
	PlanID               uuid.UUID      `json:"plan_id"`
	PlanName             string         `json:"plan_name"`
	MaxFileSizeBytes     int64          `json:"max_file_size_bytes"`
	MaxTotalStorageBytes int64          `json:"max_total_storage_bytes"`
	MaxFiles             int32          `json:"max_files"`
	MaxFilesSentPerDay   int32          `json:"max_files_sent_per_day"`
	MaxSharesPerDay      int32          `json:"max_shares_per_day"`
}

func (q *Queries) GetUserWithPlan(ctx context.Context, id uuid.UUID) (GetUserWithPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithPlan, id)
	var i GetUserWithPlanRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.UserBucket,
		&i.CreatedAt,
		&i.PlanID,
		&i.PlanName,
		&i.MaxFileSizeBytes,
		&i.MaxTotalStorageBytes,
		&i.MaxFiles,
		&i.MaxFilesSentPerDay,
		&i.MaxSharesPerDay,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :exec
UPDATE users SET plan_id = $1 WHERE id = $2
`

type UpdateUserPlanParams struct {
	PlanID uuid.NullUUID `json:"plan_id"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPlan, arg.PlanID, arg.ID)
	return err
}
