// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AbortFileUpload(ctx context.Context, id uuid.UUID) (FileUpload, error)
	AssignAPIKeyToPrivate(ctx context.Context, arg AssignAPIKeyToPrivateParams) (ApiKeyUserAssignment, error)
	AssignAPIKeyToWorkspace(ctx context.Context, arg AssignAPIKeyToWorkspaceParams) (ApiKeyWorkspace, error)
	BlockUntil(ctx context.Context, arg BlockUntilParams) (AuthRateLimit, error)
	CheckPrivateAPIKeyQuota(ctx context.Context, userID uuid.UUID) (bool, error)
	CheckShareQuota(ctx context.Context, arg CheckShareQuotaParams) (bool, error)
	CheckUploadQuota(ctx context.Context, arg CheckUploadQuotaParams) (CheckUploadQuotaRow, error)
	CheckWorkspaceAPIKeyQuota(ctx context.Context, workspaceID uuid.UUID) (bool, error)
	CheckWorkspaceResourceQuota(ctx context.Context, id uuid.UUID) (CheckWorkspaceResourceQuotaRow, error)
	CheckWorkspacesPerUserQuota(ctx context.Context, ownerID uuid.UUID) (bool, error)
	CompleteFileUpload(ctx context.Context, arg CompleteFileUploadParams) (uuid.UUID, error)
	ConsumeEmailVerificationChallenge(ctx context.Context, id uuid.UUID) (EmailVerificationChallenge, error)
	CountUnseenShares(ctx context.Context, sharedFor sql.NullString) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAPIKeyScope(ctx context.Context, arg CreateAPIKeyScopeParams) error
	CreateAuthRateLimit(ctx context.Context, arg CreateAuthRateLimitParams) (AuthRateLimit, error)
	CreateEmailVerificationChallenge(ctx context.Context, arg CreateEmailVerificationChallengeParams) (EmailVerificationChallenge, error)
	CreateFileUpload(ctx context.Context, arg CreateFileUploadParams) (FileUpload, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	CreatePasswordCredentials(ctx context.Context, arg CreatePasswordCredentialsParams) (PasswordCredential, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, userEmail string) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	CreateWorkspaceFile(ctx context.Context, arg CreateWorkspaceFileParams) (WorkspaceFile, error)
	CreateWorkspaceFolder(ctx context.Context, arg CreateWorkspaceFolderParams) (WorkspaceFile, error)
	CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) (WorkspaceInvite, error)
	CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) (User, error)
	DeleteEmailVerificationChallengeById(ctx context.Context, id uuid.UUID) error
	DeleteFileByNameAndId(ctx context.Context, arg DeleteFileByNameAndIdParams) error
	DeleteFileUploadPartsByUploadID(ctx context.Context, uploadID uuid.UUID) error
	DeletePlan(ctx context.Context, id uuid.UUID) error
	DeletePlanFeatures(ctx context.Context, planID uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteShareByToken(ctx context.Context, arg DeleteShareByTokenParams) (int64, error)
	DeleteUserPlan(ctx context.Context, id uuid.UUID) error
	DeleteWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	DeleteWorkspaceFileById(ctx context.Context, arg DeleteWorkspaceFileByIdParams) error
	DeleteWorkspaceFilesByPath(ctx context.Context, arg DeleteWorkspaceFilesByPathParams) error
	DeleteWorkspaceFilesByPathPrefix(ctx context.Context, arg DeleteWorkspaceFilesByPathPrefixParams) error
	DeleteWorkspaceInvite(ctx context.Context, id uuid.UUID) error
	DeleteWorkspaceInviteByToken(ctx context.Context, token string) error
	DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error
	FailFileUpload(ctx context.Context, id uuid.UUID) (FileUpload, error)
	GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAuthRateLimitByKeyAndScope(ctx context.Context, arg GetAuthRateLimitByKeyAndScopeParams) (AuthRateLimit, error)
	GetAuthorizedCLIUserInfoByAPIKey(ctx context.Context, crypt string) (GetAuthorizedCLIUserInfoByAPIKeyRow, error)
	GetBucketAndObjectFromToken(ctx context.Context, sharingToken string) (GetBucketAndObjectFromTokenRow, error)
	GetBucketObjectAndOwnerFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (GetBucketObjectAndOwnerFromPrivateTokenRow, error)
	GetEmailVerificationChallengeById(ctx context.Context, id uuid.UUID) (EmailVerificationChallenge, error)
	GetEmailVerificationCode(ctx context.Context, arg GetEmailVerificationCodeParams) (EmailVerificationChallenge, error)
	GetExistingPublicShare(ctx context.Context, arg GetExistingPublicShareParams) (Share, error)
	GetFileById(ctx context.Context, id int32) (File, error)
	GetFileByOwnerAndName(ctx context.Context, arg GetFileByOwnerAndNameParams) (GetFileByOwnerAndNameRow, error)
	GetFileFromChecksum(ctx context.Context, arg GetFileFromChecksumParams) (int32, error)
	GetFileFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (File, error)
	GetFileIdFromToken(ctx context.Context, privateDownloadToken sql.NullString) (int32, error)
	GetFileUploadById(ctx context.Context, id uuid.UUID) (FileUpload, error)
	// -- name: InsertFileReturningID :one
	// INSERT INTO files (owner_id, file_name, file_type, size, md5_checksum, private_download_token)
	// VALUES ($1, $2, $3, $4, $5, $6)
	// ON CONFLICT (owner_id, md5_checksum) DO NOTHING
	// RETURNING id;
	GetFilesByOwner(ctx context.Context, ownerID uuid.UUID) ([]File, error)
	GetFilesSharedByUser(ctx context.Context, sharedBy sql.NullString) ([]GetFilesSharedByUserRow, error)
	GetFilesSharedWithUser(ctx context.Context, sharedFor sql.NullString) ([]GetFilesSharedWithUserRow, error)
	GetIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]Identity, error)
	GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (Identity, error)
	GetIdentityByUserID(ctx context.Context, userID uuid.UUID) (Identity, error)
	GetNoteForFileById(ctx context.Context, arg GetNoteForFileByIdParams) (Note, error)
	GetPasswordCredentialsByUserId(ctx context.Context, userID uuid.UUID) (PasswordCredential, error)
	GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
	GetPlanFeatures(ctx context.Context, planID uuid.UUID) ([]PlanFeature, error)
	GetPlans(ctx context.Context) ([]Plan, error)
	GetPrivateDownloadTokenByFileName(ctx context.Context, arg GetPrivateDownloadTokenByFileNameParams) (sql.NullString, error)
	GetPublicShareMetadata(ctx context.Context, sharingToken string) (GetPublicShareMetadataRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSharedFileIdFromToken(ctx context.Context, sharingToken string) (sql.NullInt32, error)
	GetTokenExpirationTime(ctx context.Context, sharingToken string) (time.Time, error)
	GetUserBucketById(ctx context.Context, id uuid.UUID) (sql.NullString, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserDailyShares(ctx context.Context, id uuid.UUID) ([]GetUserDailySharesRow, error)
	GetUserDailyUploads(ctx context.Context, ownerID uuid.UUID) ([]GetUserDailyUploadsRow, error)
	GetUserInvitesByEmail(ctx context.Context, email string) ([]GetUserInvitesByEmailRow, error)
	GetUserPlan(ctx context.Context, id uuid.UUID) (Plan, error)
	GetUserStats(ctx context.Context, ownerID uuid.UUID) (GetUserStatsRow, error)
	GetUserWithPlan(ctx context.Context, id uuid.UUID) (GetUserWithPlanRow, error)
	GetUserWorkspaceRole(ctx context.Context, arg GetUserWorkspaceRoleParams) (string, error)
	GetUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]GetUserWorkspacesRow, error)
	GetWorkspaceById(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceFileById(ctx context.Context, arg GetWorkspaceFileByIdParams) (WorkspaceFile, error)
	GetWorkspaceFileByName(ctx context.Context, arg GetWorkspaceFileByNameParams) (GetWorkspaceFileByNameRow, error)
	GetWorkspaceFiles(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceFile, error)
	GetWorkspaceFilesAtPathWithUploaders(ctx context.Context, arg GetWorkspaceFilesAtPathWithUploadersParams) ([]GetWorkspaceFilesAtPathWithUploadersRow, error)
	GetWorkspaceFilesByPath(ctx context.Context, arg GetWorkspaceFilesByPathParams) ([]WorkspaceFile, error)
	GetWorkspaceFolderByPathAndName(ctx context.Context, arg GetWorkspaceFolderByPathAndNameParams) (WorkspaceFile, error)
	GetWorkspaceFoldersAtPathWithCreators(ctx context.Context, arg GetWorkspaceFoldersAtPathWithCreatorsParams) ([]GetWorkspaceFoldersAtPathWithCreatorsRow, error)
	GetWorkspaceFoldersByPath(ctx context.Context, arg GetWorkspaceFoldersByPathParams) ([]WorkspaceFile, error)
	GetWorkspaceInviteByToken(ctx context.Context, token string) (WorkspaceInvite, error)
	GetWorkspaceInvites(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvite, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	GetWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]GetWorkspaceMembersRow, error)
	GetWorkspaceQuotaDetails(ctx context.Context, id uuid.UUID) (GetWorkspaceQuotaDetailsRow, error)
	IncrementAuthRateLimitAttemptCount(ctx context.Context, arg IncrementAuthRateLimitAttemptCountParams) (AuthRateLimit, error)
	IncrementShareFailedAttempts(ctx context.Context, sharingToken string) (int32, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertPublicShare(ctx context.Context, arg InsertPublicShareParams) (Share, error)
	InsertPublicSharePasswordProtected(ctx context.Context, arg InsertPublicSharePasswordProtectedParams) (Share, error)
	InsertShare(ctx context.Context, arg InsertShareParams) (Share, error)
	InsertShareWithPassword(ctx context.Context, arg InsertShareWithPasswordParams) (Share, error)
	ListAPIKeyScopes(ctx context.Context, apiKeyID uuid.UUID) ([]string, error)
	ListFileIDsWithoutPrivateToken(ctx context.Context) ([]int32, error)
	ListFileUploadPartsByUploadID(ctx context.Context, uploadID uuid.UUID) ([]FileUploadPart, error)
	ListPrivateAPIKeysByUserID(ctx context.Context, userID uuid.UUID) ([]ListPrivateAPIKeysByUserIDRow, error)
	ListWorkspaceAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceAPIKeysRow, error)
	MarkShareSeen(ctx context.Context, arg MarkShareSeenParams) (Share, error)
	MoveWorkspaceFile(ctx context.Context, arg MoveWorkspaceFileParams) error
	MoveWorkspaceFilesByPathPrefix(ctx context.Context, arg MoveWorkspaceFilesByPathPrefixParams) error
	RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error)
	RenameWorkspaceWithSlug(ctx context.Context, arg RenameWorkspaceWithSlugParams) (Workspace, error)
	RevokePrivateAPIKey(ctx context.Context, arg RevokePrivateAPIKeyParams) (ApiKey, error)
	RevokeWorkspaceAPIKey(ctx context.Context, arg RevokeWorkspaceAPIKeyParams) (ApiKey, error)
	SaveFileUploadPart(ctx context.Context, arg SaveFileUploadPartParams) (int64, error)
	UpdateFileNameByID(ctx context.Context, arg UpdateFileNameByIDParams) error
	UpdateFileNameByOwnerAndName(ctx context.Context, arg UpdateFileNameByOwnerAndNameParams) error
	UpdateFileUploadParts(ctx context.Context, arg UpdateFileUploadPartsParams) error
	UpdateNoteForFile(ctx context.Context, arg UpdateNoteForFileParams) (Note, error)
	UpdatePasswordCredentials(ctx context.Context, arg UpdatePasswordCredentialsParams) (PasswordCredential, error)
	UpdatePrivateDownloadToken(ctx context.Context, arg UpdatePrivateDownloadTokenParams) error
	UpdateResendAvailableAt(ctx context.Context, arg UpdateResendAvailableAtParams) (EmailVerificationChallenge, error)
	UpdateUserBucketNameById(ctx context.Context, arg UpdateUserBucketNameByIdParams) error
	UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error
	UpdateWorkspaceFileName(ctx context.Context, arg UpdateWorkspaceFileNameParams) error
	UpdateWorkspaceFolderLocation(ctx context.Context, arg UpdateWorkspaceFolderLocationParams) error
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error
}

var _ Querier = (*Queries)(nil)
