// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUnseenShares = `-- name: CountUnseenShares :one
SELECT COUNT(*) FROM shares
WHERE shared_for = $1 AND received_seen_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountUnseenShares(ctx context.Context, sharedFor sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnseenShares, sharedFor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBucketAndObjectFromToken = `-- name: GetBucketAndObjectFromToken :one
SELECT
u.user_bucket,
f.file_name
FROM shares s
JOIN files f ON s.file_id = f.id
JOIN users u ON f.owner_google_id = u.google_id
WHERE s.sharing_token = $1
`

type GetBucketAndObjectFromTokenRow struct {
	UserBucket sql.NullString `json:"user_bucket"`
	FileName   string         `json:"file_name"`
}

func (q *Queries) GetBucketAndObjectFromToken(ctx context.Context, sharingToken string) (GetBucketAndObjectFromTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getBucketAndObjectFromToken, sharingToken)
	var i GetBucketAndObjectFromTokenRow
	err := row.Scan(&i.UserBucket, &i.FileName)
	return i, err
}

const getBucketObjectAndOwnerFromPrivateToken = `-- name: GetBucketObjectAndOwnerFromPrivateToken :one
SELECT
    u.user_bucket AS bucket_name,
    f.owner_google_id AS owner_google_id,
    f.file_name AS object_name
FROM files f
JOIN users u ON f.owner_google_id = u.google_id
WHERE f.private_download_token = $1
`

type GetBucketObjectAndOwnerFromPrivateTokenRow struct {
	BucketName    sql.NullString `json:"bucket_name"`
	OwnerGoogleID sql.NullString `json:"owner_google_id"`
	ObjectName    string         `json:"object_name"`
}

func (q *Queries) GetBucketObjectAndOwnerFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (GetBucketObjectAndOwnerFromPrivateTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getBucketObjectAndOwnerFromPrivateToken, privateDownloadToken)
	var i GetBucketObjectAndOwnerFromPrivateTokenRow
	err := row.Scan(&i.BucketName, &i.OwnerGoogleID, &i.ObjectName)
	return i, err
}

const getExistingPublicShare = `-- name: GetExistingPublicShare :one
SELECT id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at FROM shares
WHERE shared_by = $1 AND shared_for IS NULL AND file_id = $2 AND expires_at > NOW()
LIMIT 1
`

type GetExistingPublicShareParams struct {
	SharedBy sql.NullString `json:"shared_by"`
	FileID   sql.NullInt32  `json:"file_id"`
}

func (q *Queries) GetExistingPublicShare(ctx context.Context, arg GetExistingPublicShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, getExistingPublicShare, arg.SharedBy, arg.FileID)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
	)
	return i, err
}

const getFileFromPrivateToken = `-- name: GetFileFromPrivateToken :one
SELECT id, owner_google_id, file_name, file_type, size, md5_checksum, private_download_token FROM files WHERE private_download_token = $1
`

func (q *Queries) GetFileFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileFromPrivateToken, privateDownloadToken)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerGoogleID,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.PrivateDownloadToken,
	)
	return i, err
}

const getFilesSharedByUser = `-- name: GetFilesSharedByUser :many
SELECT
    f.id, f.owner_google_id, f.file_name, f.file_type, f.size, f.md5_checksum, f.private_download_token,
    s.id, s.shared_by, s.shared_for, s.sharing_token, s.file_id, s.created_at, s.expires_at, s.received_seen_at
FROM shares s
JOIN files f ON s.file_id = f.id
WHERE s.shared_by = $1
`

type GetFilesSharedByUserRow struct {
	ID                   int32          `json:"id"`
	OwnerGoogleID        sql.NullString `json:"owner_google_id"`
	FileName             string         `json:"file_name"`
	FileType             sql.NullString `json:"file_type"`
	Size                 sql.NullInt64  `json:"size"`
	Md5Checksum          string         `json:"md5_checksum"`
	PrivateDownloadToken sql.NullString `json:"private_download_token"`
	ID_2                 int32          `json:"id_2"`
	SharedBy             sql.NullString `json:"shared_by"`
	SharedFor            sql.NullString `json:"shared_for"`
	SharingToken         string         `json:"sharing_token"`
	FileID               sql.NullInt32  `json:"file_id"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	ExpiresAt            time.Time      `json:"expires_at"`
	ReceivedSeenAt       sql.NullTime   `json:"received_seen_at"`
}

func (q *Queries) GetFilesSharedByUser(ctx context.Context, sharedBy sql.NullString) ([]GetFilesSharedByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesSharedByUser, sharedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesSharedByUserRow
	for rows.Next() {
		var i GetFilesSharedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerGoogleID,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.PrivateDownloadToken,
			&i.ID_2,
			&i.SharedBy,
			&i.SharedFor,
			&i.SharingToken,
			&i.FileID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ReceivedSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesSharedWithUser = `-- name: GetFilesSharedWithUser :many
SELECT
    f.id, f.owner_google_id, f.file_name, f.file_type, f.size, f.md5_checksum, f.private_download_token,
    s.id, s.shared_by, s.shared_for, s.sharing_token, s.file_id, s.created_at, s.expires_at, s.received_seen_at
FROM shares s
JOIN files f ON s.file_id = f.id
WHERE s.shared_for = $1
`

type GetFilesSharedWithUserRow struct {
	ID                   int32          `json:"id"`
	OwnerGoogleID        sql.NullString `json:"owner_google_id"`
	FileName             string         `json:"file_name"`
	FileType             sql.NullString `json:"file_type"`
	Size                 sql.NullInt64  `json:"size"`
	Md5Checksum          string         `json:"md5_checksum"`
	PrivateDownloadToken sql.NullString `json:"private_download_token"`
	ID_2                 int32          `json:"id_2"`
	SharedBy             sql.NullString `json:"shared_by"`
	SharedFor            sql.NullString `json:"shared_for"`
	SharingToken         string         `json:"sharing_token"`
	FileID               sql.NullInt32  `json:"file_id"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	ExpiresAt            time.Time      `json:"expires_at"`
	ReceivedSeenAt       sql.NullTime   `json:"received_seen_at"`
}

func (q *Queries) GetFilesSharedWithUser(ctx context.Context, sharedFor sql.NullString) ([]GetFilesSharedWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesSharedWithUser, sharedFor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesSharedWithUserRow
	for rows.Next() {
		var i GetFilesSharedWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerGoogleID,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.PrivateDownloadToken,
			&i.ID_2,
			&i.SharedBy,
			&i.SharedFor,
			&i.SharingToken,
			&i.FileID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ReceivedSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedFileIdFromToken = `-- name: GetSharedFileIdFromToken :one
SELECT file_id FROM shares WHERE sharing_token = $1
`

func (q *Queries) GetSharedFileIdFromToken(ctx context.Context, sharingToken string) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getSharedFileIdFromToken, sharingToken)
	var file_id sql.NullInt32
	err := row.Scan(&file_id)
	return file_id, err
}

const getTokenExpirationTime = `-- name: GetTokenExpirationTime :one
SELECT expires_at FROM shares WHERE sharing_token = $1
`

func (q *Queries) GetTokenExpirationTime(ctx context.Context, sharingToken string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getTokenExpirationTime, sharingToken)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const insertPublicShare = `-- name: InsertPublicShare :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at, sharing_token)
VALUES ($1, NULL, $2, $3, $4)
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at
`

type InsertPublicShareParams struct {
	SharedBy     sql.NullString `json:"shared_by"`
	FileID       sql.NullInt32  `json:"file_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	SharingToken string         `json:"sharing_token"`
}

func (q *Queries) InsertPublicShare(ctx context.Context, arg InsertPublicShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertPublicShare,
		arg.SharedBy,
		arg.FileID,
		arg.ExpiresAt,
		arg.SharingToken,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
	)
	return i, err
}

const insertShare = `-- name: InsertShare :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at, sharing_token)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (shared_by, shared_for, file_id) DO UPDATE
SET expires_at = EXCLUDED.expires_at
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at
`

type InsertShareParams struct {
	SharedBy     sql.NullString `json:"shared_by"`
	SharedFor    sql.NullString `json:"shared_for"`
	FileID       sql.NullInt32  `json:"file_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	SharingToken string         `json:"sharing_token"`
}

func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertShare,
		arg.SharedBy,
		arg.SharedFor,
		arg.FileID,
		arg.ExpiresAt,
		arg.SharingToken,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
	)
	return i, err
}

const markShareSeen = `-- name: MarkShareSeen :exec
UPDATE shares SET received_seen_at = NOW()
WHERE sharing_token = $1 AND shared_for = $2 AND received_seen_at IS NULL
`

type MarkShareSeenParams struct {
	SharingToken string         `json:"sharing_token"`
	SharedFor    sql.NullString `json:"shared_for"`
}

func (q *Queries) MarkShareSeen(ctx context.Context, arg MarkShareSeenParams) error {
	_, err := q.db.ExecContext(ctx, markShareSeen, arg.SharingToken, arg.SharedFor)
	return err
}
