// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUnseenShares = `-- name: CountUnseenShares :one
SELECT COUNT(*) FROM shares
WHERE shared_for = $1 AND received_seen_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountUnseenShares(ctx context.Context, sharedFor sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnseenShares, sharedFor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteShareByToken = `-- name: DeleteShareByToken :execrows
DELETE FROM shares WHERE sharing_token = $1 AND shared_by = $2
`

type DeleteShareByTokenParams struct {
	SharingToken string         `json:"sharing_token"`
	SharedBy     sql.NullString `json:"shared_by"`
}

func (q *Queries) DeleteShareByToken(ctx context.Context, arg DeleteShareByTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteShareByToken, arg.SharingToken, arg.SharedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBucketAndObjectFromToken = `-- name: GetBucketAndObjectFromToken :one
SELECT
u.user_bucket,
f.storage_mapping,
f.file_name,
s.password_hash,
s.failed_attempts,
s.shared_by
FROM shares s
JOIN files f ON s.file_id = f.id
JOIN users u ON f.owner_id = u.id
WHERE s.sharing_token = $1
`

type GetBucketAndObjectFromTokenRow struct {
	UserBucket     sql.NullString `json:"user_bucket"`
	StorageMapping uuid.UUID      `json:"storage_mapping"`
	FileName       string         `json:"file_name"`
	PasswordHash   sql.NullString `json:"password_hash"`
	FailedAttempts int32          `json:"failed_attempts"`
	SharedBy       sql.NullString `json:"shared_by"`
}

func (q *Queries) GetBucketAndObjectFromToken(ctx context.Context, sharingToken string) (GetBucketAndObjectFromTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getBucketAndObjectFromToken, sharingToken)
	var i GetBucketAndObjectFromTokenRow
	err := row.Scan(
		&i.UserBucket,
		&i.StorageMapping,
		&i.FileName,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.SharedBy,
	)
	return i, err
}

const getBucketObjectAndOwnerFromPrivateToken = `-- name: GetBucketObjectAndOwnerFromPrivateToken :one
SELECT
    u.user_bucket AS bucket_name,
    u.id AS owner_id,
    f.storage_mapping AS object_name,
    f.file_name AS file_name
FROM files f
JOIN users u ON f.owner_id = u.id
WHERE f.private_download_token = $1
`

type GetBucketObjectAndOwnerFromPrivateTokenRow struct {
	BucketName sql.NullString `json:"bucket_name"`
	OwnerID    uuid.UUID      `json:"owner_id"`
	ObjectName uuid.UUID      `json:"object_name"`
	FileName   string         `json:"file_name"`
}

func (q *Queries) GetBucketObjectAndOwnerFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (GetBucketObjectAndOwnerFromPrivateTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getBucketObjectAndOwnerFromPrivateToken, privateDownloadToken)
	var i GetBucketObjectAndOwnerFromPrivateTokenRow
	err := row.Scan(
		&i.BucketName,
		&i.OwnerID,
		&i.ObjectName,
		&i.FileName,
	)
	return i, err
}

const getExistingPublicShare = `-- name: GetExistingPublicShare :one
SELECT id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at, shared_by_user_id, password_hash, failed_attempts FROM shares
WHERE shared_by = $1 AND shared_for IS NULL AND file_id = $2 AND expires_at > NOW()
LIMIT 1
`

type GetExistingPublicShareParams struct {
	SharedBy sql.NullString `json:"shared_by"`
	FileID   sql.NullInt32  `json:"file_id"`
}

func (q *Queries) GetExistingPublicShare(ctx context.Context, arg GetExistingPublicShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, getExistingPublicShare, arg.SharedBy, arg.FileID)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
		&i.SharedByUserID,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}

const getFileFromPrivateToken = `-- name: GetFileFromPrivateToken :one
SELECT id, file_name, file_type, size, md5_checksum, private_download_token, owner_id, storage_mapping, created_at FROM files WHERE private_download_token = $1
`

func (q *Queries) GetFileFromPrivateToken(ctx context.Context, privateDownloadToken sql.NullString) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileFromPrivateToken, privateDownloadToken)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.PrivateDownloadToken,
		&i.OwnerID,
		&i.StorageMapping,
		&i.CreatedAt,
	)
	return i, err
}

const getFilesSharedByUser = `-- name: GetFilesSharedByUser :many
SELECT
    f.id, f.file_name, f.file_type, f.size, f.md5_checksum, f.private_download_token, f.owner_id, f.storage_mapping, f.created_at,
    s.id, s.shared_by, s.shared_for, s.sharing_token, s.file_id, s.created_at, s.expires_at, s.received_seen_at, s.shared_by_user_id, s.password_hash, s.failed_attempts
FROM shares s
JOIN files f ON s.file_id = f.id
WHERE s.shared_by = $1
`

type GetFilesSharedByUserRow struct {
	ID                   int32          `json:"id"`
	FileName             string         `json:"file_name"`
	FileType             sql.NullString `json:"file_type"`
	Size                 sql.NullInt64  `json:"size"`
	Md5Checksum          string         `json:"md5_checksum"`
	PrivateDownloadToken sql.NullString `json:"private_download_token"`
	OwnerID              uuid.UUID      `json:"owner_id"`
	StorageMapping       uuid.UUID      `json:"storage_mapping"`
	CreatedAt            time.Time      `json:"created_at"`
	ID_2                 int32          `json:"id_2"`
	SharedBy             sql.NullString `json:"shared_by"`
	SharedFor            sql.NullString `json:"shared_for"`
	SharingToken         string         `json:"sharing_token"`
	FileID               sql.NullInt32  `json:"file_id"`
	CreatedAt_2          sql.NullTime   `json:"created_at_2"`
	ExpiresAt            time.Time      `json:"expires_at"`
	ReceivedSeenAt       sql.NullTime   `json:"received_seen_at"`
	SharedByUserID       uuid.NullUUID  `json:"shared_by_user_id"`
	PasswordHash         sql.NullString `json:"password_hash"`
	FailedAttempts       int32          `json:"failed_attempts"`
}

func (q *Queries) GetFilesSharedByUser(ctx context.Context, sharedBy sql.NullString) ([]GetFilesSharedByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesSharedByUser, sharedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesSharedByUserRow
	for rows.Next() {
		var i GetFilesSharedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.PrivateDownloadToken,
			&i.OwnerID,
			&i.StorageMapping,
			&i.CreatedAt,
			&i.ID_2,
			&i.SharedBy,
			&i.SharedFor,
			&i.SharingToken,
			&i.FileID,
			&i.CreatedAt_2,
			&i.ExpiresAt,
			&i.ReceivedSeenAt,
			&i.SharedByUserID,
			&i.PasswordHash,
			&i.FailedAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesSharedWithUser = `-- name: GetFilesSharedWithUser :many
SELECT
    f.id, f.file_name, f.file_type, f.size, f.md5_checksum, f.private_download_token, f.owner_id, f.storage_mapping, f.created_at,
    s.id, s.shared_by, s.shared_for, s.sharing_token, s.file_id, s.created_at, s.expires_at, s.received_seen_at, s.shared_by_user_id, s.password_hash, s.failed_attempts
FROM shares s
JOIN files f ON s.file_id = f.id
WHERE s.shared_for = $1
`

type GetFilesSharedWithUserRow struct {
	ID                   int32          `json:"id"`
	FileName             string         `json:"file_name"`
	FileType             sql.NullString `json:"file_type"`
	Size                 sql.NullInt64  `json:"size"`
	Md5Checksum          string         `json:"md5_checksum"`
	PrivateDownloadToken sql.NullString `json:"private_download_token"`
	OwnerID              uuid.UUID      `json:"owner_id"`
	StorageMapping       uuid.UUID      `json:"storage_mapping"`
	CreatedAt            time.Time      `json:"created_at"`
	ID_2                 int32          `json:"id_2"`
	SharedBy             sql.NullString `json:"shared_by"`
	SharedFor            sql.NullString `json:"shared_for"`
	SharingToken         string         `json:"sharing_token"`
	FileID               sql.NullInt32  `json:"file_id"`
	CreatedAt_2          sql.NullTime   `json:"created_at_2"`
	ExpiresAt            time.Time      `json:"expires_at"`
	ReceivedSeenAt       sql.NullTime   `json:"received_seen_at"`
	SharedByUserID       uuid.NullUUID  `json:"shared_by_user_id"`
	PasswordHash         sql.NullString `json:"password_hash"`
	FailedAttempts       int32          `json:"failed_attempts"`
}

func (q *Queries) GetFilesSharedWithUser(ctx context.Context, sharedFor sql.NullString) ([]GetFilesSharedWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesSharedWithUser, sharedFor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesSharedWithUserRow
	for rows.Next() {
		var i GetFilesSharedWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.PrivateDownloadToken,
			&i.OwnerID,
			&i.StorageMapping,
			&i.CreatedAt,
			&i.ID_2,
			&i.SharedBy,
			&i.SharedFor,
			&i.SharingToken,
			&i.FileID,
			&i.CreatedAt_2,
			&i.ExpiresAt,
			&i.ReceivedSeenAt,
			&i.SharedByUserID,
			&i.PasswordHash,
			&i.FailedAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicShareMetadata = `-- name: GetPublicShareMetadata :one
SELECT f.file_name, s.expires_at, s.password_hash, s.failed_attempts
FROM shares s
JOIN files f ON s.file_id = f.id
WHERE s.sharing_token = $1
`

type GetPublicShareMetadataRow struct {
	FileName       string         `json:"file_name"`
	ExpiresAt      time.Time      `json:"expires_at"`
	PasswordHash   sql.NullString `json:"password_hash"`
	FailedAttempts int32          `json:"failed_attempts"`
}

func (q *Queries) GetPublicShareMetadata(ctx context.Context, sharingToken string) (GetPublicShareMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicShareMetadata, sharingToken)
	var i GetPublicShareMetadataRow
	err := row.Scan(
		&i.FileName,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}

const getSharedFileIdFromToken = `-- name: GetSharedFileIdFromToken :one
SELECT file_id FROM shares WHERE sharing_token = $1
`

func (q *Queries) GetSharedFileIdFromToken(ctx context.Context, sharingToken string) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getSharedFileIdFromToken, sharingToken)
	var file_id sql.NullInt32
	err := row.Scan(&file_id)
	return file_id, err
}

const getTokenExpirationTime = `-- name: GetTokenExpirationTime :one
SELECT expires_at FROM shares WHERE sharing_token = $1
`

func (q *Queries) GetTokenExpirationTime(ctx context.Context, sharingToken string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getTokenExpirationTime, sharingToken)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const incrementShareFailedAttempts = `-- name: IncrementShareFailedAttempts :one
UPDATE shares SET failed_attempts = failed_attempts + 1
WHERE sharing_token = $1
RETURNING failed_attempts
`

func (q *Queries) IncrementShareFailedAttempts(ctx context.Context, sharingToken string) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrementShareFailedAttempts, sharingToken)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const insertPublicShare = `-- name: InsertPublicShare :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at, sharing_token)
VALUES ($1, NULL, $2, $3, $4)
ON CONFLICT (shared_by, file_id) WHERE shared_for IS NULL
DO UPDATE SET expires_at = EXCLUDED.expires_at, sharing_token = EXCLUDED.sharing_token, password_hash = NULL
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at, shared_by_user_id, password_hash, failed_attempts
`

type InsertPublicShareParams struct {
	SharedBy     sql.NullString `json:"shared_by"`
	FileID       sql.NullInt32  `json:"file_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	SharingToken string         `json:"sharing_token"`
}

func (q *Queries) InsertPublicShare(ctx context.Context, arg InsertPublicShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertPublicShare,
		arg.SharedBy,
		arg.FileID,
		arg.ExpiresAt,
		arg.SharingToken,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
		&i.SharedByUserID,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}

const insertPublicSharePasswordProtected = `-- name: InsertPublicSharePasswordProtected :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at, sharing_token, password_hash)
VALUES ($1, NULL, $2, $3, $4, $5)
ON CONFLICT (shared_by, file_id) WHERE shared_for IS NULL
DO UPDATE SET expires_at = EXCLUDED.expires_at, sharing_token = EXCLUDED.sharing_token, password_hash = EXCLUDED.password_hash, failed_attempts = 0
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at, shared_by_user_id, password_hash, failed_attempts
`

type InsertPublicSharePasswordProtectedParams struct {
	SharedBy     sql.NullString `json:"shared_by"`
	FileID       sql.NullInt32  `json:"file_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	SharingToken string         `json:"sharing_token"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) InsertPublicSharePasswordProtected(ctx context.Context, arg InsertPublicSharePasswordProtectedParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertPublicSharePasswordProtected,
		arg.SharedBy,
		arg.FileID,
		arg.ExpiresAt,
		arg.SharingToken,
		arg.PasswordHash,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
		&i.SharedByUserID,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}

const insertShare = `-- name: InsertShare :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at, sharing_token)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (shared_by, shared_for, file_id) DO UPDATE
SET expires_at = EXCLUDED.expires_at, password_hash = NULL
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at, shared_by_user_id, password_hash, failed_attempts
`

type InsertShareParams struct {
	SharedBy     sql.NullString `json:"shared_by"`
	SharedFor    sql.NullString `json:"shared_for"`
	FileID       sql.NullInt32  `json:"file_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	SharingToken string         `json:"sharing_token"`
}

func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertShare,
		arg.SharedBy,
		arg.SharedFor,
		arg.FileID,
		arg.ExpiresAt,
		arg.SharingToken,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
		&i.SharedByUserID,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}

const insertShareWithPassword = `-- name: InsertShareWithPassword :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at, sharing_token, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (shared_by, shared_for, file_id) DO UPDATE
SET expires_at = EXCLUDED.expires_at, password_hash = EXCLUDED.password_hash, failed_attempts = 0
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at, shared_by_user_id, password_hash, failed_attempts
`

type InsertShareWithPasswordParams struct {
	SharedBy     sql.NullString `json:"shared_by"`
	SharedFor    sql.NullString `json:"shared_for"`
	FileID       sql.NullInt32  `json:"file_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	SharingToken string         `json:"sharing_token"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) InsertShareWithPassword(ctx context.Context, arg InsertShareWithPasswordParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertShareWithPassword,
		arg.SharedBy,
		arg.SharedFor,
		arg.FileID,
		arg.ExpiresAt,
		arg.SharingToken,
		arg.PasswordHash,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
		&i.SharedByUserID,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}

const markShareSeen = `-- name: MarkShareSeen :one
UPDATE shares SET received_seen_at = NOW()
WHERE sharing_token = $1 AND shared_for = $2 AND received_seen_at IS NULL
RETURNING id, shared_by, shared_for, sharing_token, file_id, created_at, expires_at, received_seen_at, shared_by_user_id, password_hash, failed_attempts
`

type MarkShareSeenParams struct {
	SharingToken string         `json:"sharing_token"`
	SharedFor    sql.NullString `json:"shared_for"`
}

func (q *Queries) MarkShareSeen(ctx context.Context, arg MarkShareSeenParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, markShareSeen, arg.SharingToken, arg.SharedFor)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.SharingToken,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReceivedSeenAt,
		&i.SharedByUserID,
		&i.PasswordHash,
		&i.FailedAttempts,
	)
	return i, err
}
