// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_email)
VALUES ($1)
RETURNING id, user_bucket, user_email, created_at
`

func (q *Queries) CreateUser(ctx context.Context, userEmail string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, userEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserBucket,
		&i.UserEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM users WHERE id = $1 RETURNING id, user_bucket, user_email, created_at
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteAccount, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserBucket,
		&i.UserEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBucketById = `-- name: GetUserBucketById :one
SELECT user_bucket FROM users WHERE id = $1
`

func (q *Queries) GetUserBucketById(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserBucketById, id)
	var user_bucket sql.NullString
	err := row.Scan(&user_bucket)
	return user_bucket, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_bucket, user_email, created_at FROM users WHERE user_email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, userEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserBucket,
		&i.UserEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, user_bucket, user_email, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserBucket,
		&i.UserEmail,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserBucketNameById = `-- name: UpdateUserBucketNameById :exec
UPDATE users SET user_bucket = $1 WHERE id = $2
`

type UpdateUserBucketNameByIdParams struct {
	UserBucket sql.NullString `json:"user_bucket"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserBucketNameById(ctx context.Context, arg UpdateUserBucketNameByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBucketNameById, arg.UserBucket, arg.ID)
	return err
}
