// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_files.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWorkspaceFile = `-- name: CreateWorkspaceFile :one
INSERT INTO workspace_files (id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
`

type CreateWorkspaceFileParams struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	UploadedBy  uuid.UUID      `json:"uploaded_by"`
	FileName    string         `json:"file_name"`
	FileType    sql.NullString `json:"file_type"`
	Size        int64          `json:"size"`
	Md5Checksum sql.NullString `json:"md5_checksum"`
	Path        string         `json:"path"`
}

func (q *Queries) CreateWorkspaceFile(ctx context.Context, arg CreateWorkspaceFileParams) (WorkspaceFile, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceFile,
		arg.ID,
		arg.WorkspaceID,
		arg.UploadedBy,
		arg.FileName,
		arg.FileType,
		arg.Size,
		arg.Md5Checksum,
		arg.Path,
	)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceFolder = `-- name: CreateWorkspaceFolder :one
INSERT INTO workspace_files (id, workspace_id, uploaded_by, file_name, file_type, size, path)
VALUES ($1, $2, $3, $4, 'inode/directory', 0, $5)
RETURNING id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
`

type CreateWorkspaceFolderParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UploadedBy  uuid.UUID `json:"uploaded_by"`
	FileName    string    `json:"file_name"`
	Path        string    `json:"path"`
}

func (q *Queries) CreateWorkspaceFolder(ctx context.Context, arg CreateWorkspaceFolderParams) (WorkspaceFile, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceFolder,
		arg.ID,
		arg.WorkspaceID,
		arg.UploadedBy,
		arg.FileName,
		arg.Path,
	)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceFileById = `-- name: DeleteWorkspaceFileById :exec
DELETE FROM workspace_files WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkspaceFileByIdParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteWorkspaceFileById(ctx context.Context, arg DeleteWorkspaceFileByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceFileById, arg.ID, arg.WorkspaceID)
	return err
}

const deleteWorkspaceFilesByPath = `-- name: DeleteWorkspaceFilesByPath :exec
DELETE FROM workspace_files WHERE workspace_id = $1 AND path = $2
`

type DeleteWorkspaceFilesByPathParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
}

func (q *Queries) DeleteWorkspaceFilesByPath(ctx context.Context, arg DeleteWorkspaceFilesByPathParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceFilesByPath, arg.WorkspaceID, arg.Path)
	return err
}

const deleteWorkspaceFilesByPathPrefix = `-- name: DeleteWorkspaceFilesByPathPrefix :exec
DELETE FROM workspace_files WHERE workspace_id = $1 AND path LIKE $2
`

type DeleteWorkspaceFilesByPathPrefixParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
}

func (q *Queries) DeleteWorkspaceFilesByPathPrefix(ctx context.Context, arg DeleteWorkspaceFilesByPathPrefixParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceFilesByPathPrefix, arg.WorkspaceID, arg.Path)
	return err
}

const getWorkspaceFileById = `-- name: GetWorkspaceFileById :one
SELECT id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
FROM workspace_files WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceFileByIdParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceFileById(ctx context.Context, arg GetWorkspaceFileByIdParams) (WorkspaceFile, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceFileById, arg.ID, arg.WorkspaceID)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceFileByName = `-- name: GetWorkspaceFileByName :one
SELECT id, file_name, md5_checksum, path
FROM workspace_files
WHERE workspace_id = $1 AND path = $2 AND file_name = $3
`

type GetWorkspaceFileByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
	FileName    string    `json:"file_name"`
}

type GetWorkspaceFileByNameRow struct {
	ID          uuid.UUID      `json:"id"`
	FileName    string         `json:"file_name"`
	Md5Checksum sql.NullString `json:"md5_checksum"`
	Path        string         `json:"path"`
}

func (q *Queries) GetWorkspaceFileByName(ctx context.Context, arg GetWorkspaceFileByNameParams) (GetWorkspaceFileByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceFileByName, arg.WorkspaceID, arg.Path, arg.FileName)
	var i GetWorkspaceFileByNameRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Md5Checksum,
		&i.Path,
	)
	return i, err
}

const getWorkspaceFiles = `-- name: GetWorkspaceFiles :many
SELECT id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
FROM workspace_files WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceFiles(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceFile, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceFiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceFile
	for rows.Next() {
		var i WorkspaceFile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFilesAtPathWithUploaders = `-- name: GetWorkspaceFilesAtPathWithUploaders :many
SELECT wf.id, wf.workspace_id, wf.uploaded_by, wf.file_name, wf.file_type,
       wf.size, wf.md5_checksum, wf.path, wf.created_at,
       COALESCE(u.user_email, '') AS uploader_email
FROM workspace_files wf
LEFT JOIN users u ON u.id = wf.uploaded_by
WHERE wf.workspace_id = $1 AND wf.file_type != 'inode/directory'
  AND (wf.path = $2 OR wf.path LIKE $2 || '/%')
`

type GetWorkspaceFilesAtPathWithUploadersParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
}

type GetWorkspaceFilesAtPathWithUploadersRow struct {
	ID            uuid.UUID      `json:"id"`
	WorkspaceID   uuid.UUID      `json:"workspace_id"`
	UploadedBy    uuid.UUID      `json:"uploaded_by"`
	FileName      string         `json:"file_name"`
	FileType      sql.NullString `json:"file_type"`
	Size          int64          `json:"size"`
	Md5Checksum   sql.NullString `json:"md5_checksum"`
	Path          string         `json:"path"`
	CreatedAt     time.Time      `json:"created_at"`
	UploaderEmail string         `json:"uploader_email"`
}

func (q *Queries) GetWorkspaceFilesAtPathWithUploaders(ctx context.Context, arg GetWorkspaceFilesAtPathWithUploadersParams) ([]GetWorkspaceFilesAtPathWithUploadersRow, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceFilesAtPathWithUploaders, arg.WorkspaceID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceFilesAtPathWithUploadersRow
	for rows.Next() {
		var i GetWorkspaceFilesAtPathWithUploadersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.Path,
			&i.CreatedAt,
			&i.UploaderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFilesByPath = `-- name: GetWorkspaceFilesByPath :many
SELECT id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
FROM workspace_files WHERE workspace_id = $1 AND path = $2
`

type GetWorkspaceFilesByPathParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
}

func (q *Queries) GetWorkspaceFilesByPath(ctx context.Context, arg GetWorkspaceFilesByPathParams) ([]WorkspaceFile, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceFilesByPath, arg.WorkspaceID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceFile
	for rows.Next() {
		var i WorkspaceFile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFolderByPathAndName = `-- name: GetWorkspaceFolderByPathAndName :one
SELECT id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
FROM workspace_files
WHERE workspace_id = $1 AND path = $2 AND file_name = $3 AND file_type = 'inode/directory'
`

type GetWorkspaceFolderByPathAndNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
	FileName    string    `json:"file_name"`
}

func (q *Queries) GetWorkspaceFolderByPathAndName(ctx context.Context, arg GetWorkspaceFolderByPathAndNameParams) (WorkspaceFile, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceFolderByPathAndName, arg.WorkspaceID, arg.Path, arg.FileName)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileType,
		&i.Size,
		&i.Md5Checksum,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceFoldersAtPathWithCreators = `-- name: GetWorkspaceFoldersAtPathWithCreators :many
SELECT wf.id, wf.workspace_id, wf.uploaded_by, wf.file_name, wf.path, wf.created_at,
       COALESCE(u.user_email, '') AS creator_email
FROM workspace_files wf
LEFT JOIN users u ON u.id = wf.uploaded_by
WHERE wf.workspace_id = $1 AND wf.path = $2 AND wf.file_type = 'inode/directory'
`

type GetWorkspaceFoldersAtPathWithCreatorsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
}

type GetWorkspaceFoldersAtPathWithCreatorsRow struct {
	ID           uuid.UUID `json:"id"`
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	UploadedBy   uuid.UUID `json:"uploaded_by"`
	FileName     string    `json:"file_name"`
	Path         string    `json:"path"`
	CreatedAt    time.Time `json:"created_at"`
	CreatorEmail string    `json:"creator_email"`
}

func (q *Queries) GetWorkspaceFoldersAtPathWithCreators(ctx context.Context, arg GetWorkspaceFoldersAtPathWithCreatorsParams) ([]GetWorkspaceFoldersAtPathWithCreatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceFoldersAtPathWithCreators, arg.WorkspaceID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceFoldersAtPathWithCreatorsRow
	for rows.Next() {
		var i GetWorkspaceFoldersAtPathWithCreatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.FileName,
			&i.Path,
			&i.CreatedAt,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFoldersByPath = `-- name: GetWorkspaceFoldersByPath :many
SELECT id, workspace_id, uploaded_by, file_name, file_type, size, md5_checksum, path, created_at
FROM workspace_files
WHERE workspace_id = $1 AND path = $2 AND file_type = 'inode/directory'
`

type GetWorkspaceFoldersByPathParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
}

func (q *Queries) GetWorkspaceFoldersByPath(ctx context.Context, arg GetWorkspaceFoldersByPathParams) ([]WorkspaceFile, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceFoldersByPath, arg.WorkspaceID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceFile
	for rows.Next() {
		var i WorkspaceFile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveWorkspaceFile = `-- name: MoveWorkspaceFile :exec
UPDATE workspace_files
SET path = $1
WHERE id = $2 AND workspace_id = $3
`

type MoveWorkspaceFileParams struct {
	Path        string    `json:"path"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) MoveWorkspaceFile(ctx context.Context, arg MoveWorkspaceFileParams) error {
	_, err := q.db.ExecContext(ctx, moveWorkspaceFile, arg.Path, arg.ID, arg.WorkspaceID)
	return err
}

const moveWorkspaceFilesByPathPrefix = `-- name: MoveWorkspaceFilesByPathPrefix :exec
UPDATE workspace_files
SET path = regexp_replace(path, $1, $2)
WHERE workspace_id = $3 AND (path = $4 OR path LIKE $4 || '/%')
`

type MoveWorkspaceFilesByPathPrefixParams struct {
	RegexpReplace   string    `json:"regexp_replace"`
	RegexpReplace_2 string    `json:"regexp_replace_2"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	Path            string    `json:"path"`
}

func (q *Queries) MoveWorkspaceFilesByPathPrefix(ctx context.Context, arg MoveWorkspaceFilesByPathPrefixParams) error {
	_, err := q.db.ExecContext(ctx, moveWorkspaceFilesByPathPrefix,
		arg.RegexpReplace,
		arg.RegexpReplace_2,
		arg.WorkspaceID,
		arg.Path,
	)
	return err
}

const updateWorkspaceFileName = `-- name: UpdateWorkspaceFileName :exec
UPDATE workspace_files
SET file_name = $1
WHERE workspace_id = $2 AND path = $3 AND file_name = $4
`

type UpdateWorkspaceFileNameParams struct {
	FileName    string    `json:"file_name"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Path        string    `json:"path"`
	FileName_2  string    `json:"file_name_2"`
}

func (q *Queries) UpdateWorkspaceFileName(ctx context.Context, arg UpdateWorkspaceFileNameParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceFileName,
		arg.FileName,
		arg.WorkspaceID,
		arg.Path,
		arg.FileName_2,
	)
	return err
}

const updateWorkspaceFolderLocation = `-- name: UpdateWorkspaceFolderLocation :exec
UPDATE workspace_files
SET path = $1, file_name = $2
WHERE id = $3 AND workspace_id = $4
`

type UpdateWorkspaceFolderLocationParams struct {
	Path        string    `json:"path"`
	FileName    string    `json:"file_name"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateWorkspaceFolderLocation(ctx context.Context, arg UpdateWorkspaceFolderLocationParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceFolderLocation,
		arg.Path,
		arg.FileName,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}
