// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkWorkspaceResourceQuota = `-- name: CheckWorkspaceResourceQuota :one
WITH plan AS (
    SELECT
        p.max_files_workspace,
        p.max_total_storage_bytes_workspace,
        p.max_users_workspace,
        p.max_workspace_folders
    FROM workspaces w
    JOIN users u ON u.id = w.owner_id
    JOIN plans p ON u.plan_id = p.id
    WHERE w.id = $1
),
usage AS (
    SELECT
        COUNT(*) FILTER (WHERE file_type != 'inode/directory') AS file_count,
        COALESCE(SUM(size), 0)::BIGINT                          AS total_bytes,
        COUNT(*) FILTER (WHERE file_type = 'inode/directory')  AS folder_count
    FROM workspace_files
    WHERE workspace_id = $1
),
members AS (
    SELECT COUNT(*) AS member_count
    FROM workspace_members
    WHERE workspace_id = $1
)
SELECT
    (u.file_count   >= pl.max_files_workspace)               AS files_exceeded,
    (u.total_bytes  >= pl.max_total_storage_bytes_workspace) AS storage_exceeded,
    (u.folder_count >= pl.max_workspace_folders)             AS folders_exceeded,
    (m.member_count >= pl.max_users_workspace)               AS users_exceeded
FROM usage u, plan pl, members m
`

type CheckWorkspaceResourceQuotaRow struct {
	FilesExceeded   bool `json:"files_exceeded"`
	StorageExceeded bool `json:"storage_exceeded"`
	FoldersExceeded bool `json:"folders_exceeded"`
	UsersExceeded   bool `json:"users_exceeded"`
}

func (q *Queries) CheckWorkspaceResourceQuota(ctx context.Context, id uuid.UUID) (CheckWorkspaceResourceQuotaRow, error) {
	row := q.db.QueryRowContext(ctx, checkWorkspaceResourceQuota, id)
	var i CheckWorkspaceResourceQuotaRow
	err := row.Scan(
		&i.FilesExceeded,
		&i.StorageExceeded,
		&i.FoldersExceeded,
		&i.UsersExceeded,
	)
	return i, err
}

const checkWorkspacesPerUserQuota = `-- name: CheckWorkspacesPerUserQuota :one
SELECT (
    SELECT COUNT(*)
    FROM workspaces
    WHERE owner_id = $1
) >= p.max_user_workspaces AS workspaces_exceeded
FROM users u
JOIN plans p ON u.plan_id = p.id
WHERE u.id = $1
`

func (q *Queries) CheckWorkspacesPerUserQuota(ctx context.Context, ownerID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkWorkspacesPerUserQuota, ownerID)
	var workspaces_exceeded bool
	err := row.Scan(&workspaces_exceeded)
	return workspaces_exceeded, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces
(slug, name, owner_id)
VALUES ($1, $2, $3)
RETURNING id, slug, name, owner_id, created_at
`

type CreateWorkspaceParams struct {
	Slug    string    `json:"slug"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Slug, arg.Name, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceInvite = `-- name: CreateWorkspaceInvite :one
INSERT INTO workspace_invites
(workspace_id, email, token, role)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, email, token, role, expires_at
`

type CreateWorkspaceInviteParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Email       string    `json:"email"`
	Token       string    `json:"token"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceInvite,
		arg.WorkspaceID,
		arg.Email,
		arg.Token,
		arg.Role,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members
(workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, joined_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :one
DELETE FROM workspaces
WHERE id = $1
RETURNING id, slug, name, owner_id, created_at
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, deleteWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceInvite = `-- name: DeleteWorkspaceInvite :exec
DELETE FROM workspace_invites
WHERE id = $1
`

func (q *Queries) DeleteWorkspaceInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceInvite, id)
	return err
}

const deleteWorkspaceInviteByToken = `-- name: DeleteWorkspaceInviteByToken :exec
DELETE FROM workspace_invites
WHERE token = $1
`

func (q *Queries) DeleteWorkspaceInviteByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceInviteByToken, token)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getUserInvitesByEmail = `-- name: GetUserInvitesByEmail :many
SELECT wi.id, wi.workspace_id, wi.email, wi.token, wi.role, wi.expires_at,
       w.name AS workspace_name, w.slug AS workspace_slug
FROM workspace_invites wi
JOIN workspaces w ON w.id = wi.workspace_id
WHERE wi.email = $1 AND wi.expires_at > now()
`

type GetUserInvitesByEmailRow struct {
	ID            uuid.UUID `json:"id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	Email         string    `json:"email"`
	Token         string    `json:"token"`
	Role          string    `json:"role"`
	ExpiresAt     time.Time `json:"expires_at"`
	WorkspaceName string    `json:"workspace_name"`
	WorkspaceSlug string    `json:"workspace_slug"`
}

func (q *Queries) GetUserInvitesByEmail(ctx context.Context, email string) ([]GetUserInvitesByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserInvitesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInvitesByEmailRow
	for rows.Next() {
		var i GetUserInvitesByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.ExpiresAt,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWorkspaceRole = `-- name: GetUserWorkspaceRole :one
SELECT role FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetUserWorkspaceRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserWorkspaceRole(ctx context.Context, arg GetUserWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserWorkspaceRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT workspaces.id, workspaces.slug, workspaces.name, workspaces.owner_id, workspaces.created_at, workspace_members.role
FROM workspaces
JOIN workspace_members ON workspaces.id = workspace_members.workspace_id
WHERE workspace_members.user_id = $1
`

type GetUserWorkspacesRow struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	OwnerID   uuid.UUID `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	Role      string    `json:"role"`
}

func (q *Queries) GetUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]GetUserWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWorkspacesRow
	for rows.Next() {
		var i GetUserWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceById = `-- name: GetWorkspaceById :one
SELECT id, slug, name, owner_id, created_at FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceById(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceById, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, name, owner_id, created_at FROM workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceInviteByToken = `-- name: GetWorkspaceInviteByToken :one
SELECT id, workspace_id, email, token, role, expires_at FROM workspace_invites
WHERE token = $1
`

func (q *Queries) GetWorkspaceInviteByToken(ctx context.Context, token string) (WorkspaceInvite, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceInviteByToken, token)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}

const getWorkspaceInvites = `-- name: GetWorkspaceInvites :many
SELECT id, workspace_id, email, token, role, expires_at FROM workspace_invites
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceInvites(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvite, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceInvite
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, joined_at FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT u.user_email, u.id, wm.role, wm.joined_at
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
`

type GetWorkspaceMembersRow struct {
	UserEmail string    `json:"user_email"`
	ID        uuid.UUID `json:"id"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joined_at"`
}

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]GetWorkspaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceMembersRow
	for rows.Next() {
		var i GetWorkspaceMembersRow
		if err := rows.Scan(
			&i.UserEmail,
			&i.ID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceQuotaDetails = `-- name: GetWorkspaceQuotaDetails :one
WITH plan AS (
    SELECT
        p.max_files_workspace,
        p.max_total_storage_bytes_workspace,
        p.max_users_workspace,
        p.max_workspace_folders
    FROM workspaces w
    JOIN users u ON u.id = w.owner_id
    JOIN plans p ON u.plan_id = p.id
    WHERE w.id = $1
),
usage AS (
    SELECT
        COUNT(*) FILTER (WHERE file_type != 'inode/directory') AS file_count,
        COALESCE(SUM(size), 0)::BIGINT                          AS total_bytes,
        COUNT(*) FILTER (WHERE file_type = 'inode/directory')  AS folder_count
    FROM workspace_files
    WHERE workspace_id = $1
),
members AS (
    SELECT COUNT(*) AS member_count
    FROM workspace_members
    WHERE workspace_id = $1
)
SELECT
    u.file_count,
    u.total_bytes,
    u.folder_count,
    m.member_count,
    pl.max_files_workspace,
    pl.max_total_storage_bytes_workspace,
    pl.max_users_workspace,
    pl.max_workspace_folders
FROM usage u, plan pl, members m
`

type GetWorkspaceQuotaDetailsRow struct {
	FileCount                     int64 `json:"file_count"`
	TotalBytes                    int64 `json:"total_bytes"`
	FolderCount                   int64 `json:"folder_count"`
	MemberCount                   int64 `json:"member_count"`
	MaxFilesWorkspace             int64 `json:"max_files_workspace"`
	MaxTotalStorageBytesWorkspace int64 `json:"max_total_storage_bytes_workspace"`
	MaxUsersWorkspace             int64 `json:"max_users_workspace"`
	MaxWorkspaceFolders           int64 `json:"max_workspace_folders"`
}

func (q *Queries) GetWorkspaceQuotaDetails(ctx context.Context, id uuid.UUID) (GetWorkspaceQuotaDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceQuotaDetails, id)
	var i GetWorkspaceQuotaDetailsRow
	err := row.Scan(
		&i.FileCount,
		&i.TotalBytes,
		&i.FolderCount,
		&i.MemberCount,
		&i.MaxFilesWorkspace,
		&i.MaxTotalStorageBytesWorkspace,
		&i.MaxUsersWorkspace,
		&i.MaxWorkspaceFolders,
	)
	return i, err
}

const renameWorkspace = `-- name: RenameWorkspace :one
UPDATE workspaces
SET name = $2
WHERE id = $1
RETURNING id, slug, name, owner_id, created_at
`

type RenameWorkspaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, renameWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const renameWorkspaceWithSlug = `-- name: RenameWorkspaceWithSlug :one
UPDATE workspaces
SET name = $2, slug = $3
WHERE id = $1
RETURNING id, slug, name, owner_id, created_at
`

type RenameWorkspaceWithSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) RenameWorkspaceWithSlug(ctx context.Context, arg RenameWorkspaceWithSlugParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, renameWorkspaceWithSlug, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
SET role = $1
WHERE workspace_id = $2 AND user_id = $3
`

type UpdateWorkspaceMemberRoleParams struct {
	Role        string    `json:"role"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceMemberRole, arg.Role, arg.WorkspaceID, arg.UserID)
	return err
}
