name: Push to registries

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-multiarch:
    uses: ./.github/workflows/_build.yaml
    permissions:
        contents: read
        packages: write
        id-token: write
    with:
      runner-name: arm64-runner
      image-name-dockerhub: bobaklabs/fluxsend-backend
      image-name-github: tscrond/fluxsend-backend
      arch: "linux/amd64,linux/arm64"
    secrets:
        docker-hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker-hub-token: ${{ secrets.DOCKERHUB_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
